// "Van Basis tot Pro", de Thuisbar-cursus, in-app versie.
// Volledig eigen geschreven lesprogramma (zie ook de PDF-versie), gebaseerd op
// algemene, vakgebied-brede bartending-kennis; geen enkel onderdeel is
// overgenomen uit een bestaand boek of bestaande cursus.
//
// Elk lesson-object: { id, part, number, title, intro, blocks[], takeaways[], quiz[] }
// Praktijkopbouw (format: "praktijk"): intro = waarom, core[], taste { title, rows[] },
// steps[], mistake, tryIt { text, recipeId }; blocks/takeaways blijven leeg.
// blocks: { type: "p" } | { type: "h3", text } | { type: "box", kind, label, text } | { type: "table", headers, rows }
// quiz: { q, options[4], correct (index), explain } — zie courseQuiz.js

import { LESSON_QUIZZES, FINAL_EXAM_QUESTIONS } from "./courseQuiz.js";

export const COURSE_PARTS = [
  { id: "fundamenten", title: "Fundamenten", subtitle: "Deel I" },
  { id: "ingredienten", title: "De ingrediënten", subtitle: "Deel II" },
  { id: "techniek", title: "Techniek", subtitle: "Deel III" },
  { id: "smaak", title: "Smaak & compositie", subtitle: "Deel IV" },
  { id: "vak", title: "Het vak van bartender", subtitle: "Deel V" },
  { id: "geavanceerd", title: "Geavanceerde technieken", subtitle: "Deel VI" },
];

export const COURSE_LESSONS = [
  {
    id: "geschiedenis",
    part: "fundamenten",
    number: 1,
    title: "De geschiedenis van de cocktail",
    intro: "Elke cocktail die je ooit zult maken staat in een lijn die terugloopt tot scheepsartsen, apothekers en barmannen die problemen oplosten, niet tot mensen die simpelweg lekkere drankjes wilden bedenken.",
    blocks: [
      { type: "h3", text: "Vóór de cocktail: punch en medicinale mengsels" },
      { type: "p", text: "Lang voordat het woord \"cocktail\" bestond, mengden zeevarende naties al drank met andere ingrediënten. De punch, vermoedelijk vernoemd naar het Hindi-woord voor \"vijf\" (pānch) naar de vijf ingrediënten sterkedrank, suiker, citrus, water en specerijen, reisde vanaf de zeventiende eeuw met de Britse Oost-Indische Compagnie mee naar Europa." },
      { type: "p", text: "Citrus en suiker waren geen luxe maar praktische noodzaak: ruwe sterkedrank was scherp om te drinken, en scheurbuik was een reëel gevaar op lange zeereizen. Een scheutje citroen in de dagelijkse rum- of jeneverrantsoen loste twee problemen tegelijk op. Bijna niets in de cocktailgeschiedenis is ooit puur voor de lol bedacht." },
      { type: "h3", text: "1806: het jaar dat het woord een definitie kreeg" },
      { type: "p", text: "Pas in 1806 gaf een Amerikaanse krant, The Balance and Columbian Repository, een expliciete definitie: een cocktail was \"sterkedrank van welke soort dan ook, suiker, water en bitters.\" Dat is, in de kern, nog steeds de Old Fashioned, en alles wat we sindsdien cocktail noemen is een variatie op die vierdelige formule." },
      { type: "p", text: "Zie je die verwantschap, dan wordt de hele cocktailwereld overzichtelijk: een Manhattan is een Old Fashioned met vermout, een Sazerac is een Old Fashioned met een absint-wassing en een eigen bitter. Je leert geen honderden losse recepten, je leert een klein aantal families en hun varianten." },
      { type: "h3", text: "De Gouden Eeuw en de drooglegging" },
      { type: "p", text: "De tweede helft van de negentiende eeuw was de eerste grote bloeiperiode: Jerry Thomas' \"How to Mix Drinks\" (1862) was het eerste echte cocktailboek. Van 1920 tot 1933 verbood de Amerikaanse drooglegging alcohol volledig, een ramp die onbedoeld wereldwijd effect had: duizenden Amerikaanse barmannen verhuisden naar Europa en Cuba, waar bars als Harry's New York Bar en El Floridita uitgroeiden tot broedplaatsen van nieuwe klassiekers." },
      { type: "h3", text: "Tiki, de dip, en de renaissance" },
      { type: "p", text: "Na de oorlog ontstond tiki, een complete fantasiewereld rond Polynesische exotiek, bedacht door pioniers als Donn Beach en Trader Vic. De jaren '70-'80 gelden als dieptepunt (kant-en-klare mixen, verlies van vakmanschap), tot eind jaren '90 een kleine groep bartenders in New York en Londen terugkeerde naar negentiende-eeuwse technieken en verse ingrediënten: de \"craft cocktail-revival\" waar jij nu, met deze cursus, het resultaat van leert." },
      { type: "box", kind: "history", label: "Tijdlijn in het kort", text: "1650-1800 punch · 1806 eerste definitie van \"cocktail\" · 1862 Jerry Thomas' eerste barboek · 1920-1933 drooglegging & de Europese uittocht · jaren '30-'50 tiki-opkomst · jaren '70-'80 kwaliteitsdip · sinds ~2000 craft-cocktailrevival." },
    ],
    takeaways: [
      "De vierdelige formule uit 1806 (sterkedrank, suiker, water, bitters) is de wortel van bijna elke cocktail die je later leert.",
      "Citrus en suiker waren ooit functionele oplossingen, geen smaakgrapjes, dat verklaart waarom balans nog steeds centraal staat.",
      "Cocktailgeschiedenis verloopt in golven van bloei en verval; de stijl die je nu leert is zelf een reactie op een eerdere periode van verval.",
    ],
  },
  {
    id: "uitrusting",
    part: "fundamenten",
    number: 2,
    title: "De bar-uitrusting: jouw gereedschapskist",
    intro: "Je hebt geen dure barwagen nodig om goed te beginnen, maar met de verkeerde tools kost elke stap onnodig veel moeite. Dit is de uitrusting die er echt toe doet.",
    blocks: [
      { type: "h3", text: "De shaker: drie families, één doel" },
      { type: "p", text: "Een shaker mengt, koelt en verdunt ingrediënten met ijs. De Boston shaker (metalen beker + glazen/metalen tin) is de keuze van vrijwel elke professional vanwege snelheid en afdichting. De cobbler shaker (driedelig, met ingebouwde zeef) is prima voor beginners maar lekt sneller en verstopt bij munt of vruchtvlees. De Franse shaker zit er qua vorm tussen in." },
      { type: "h3", text: "De jigger: nauwkeurigheid is geen luxe" },
      { type: "p", text: "Een jigger is een dubbelzijdig maatbekertje. Vrijhandig schenken oogt indrukwekkend maar zelfs ervaren bartenders wijken zonder jigger tot 20% af van hun bedoelde receptuur. Bij een cocktail die op een precieze zoet-zuur-balans steunt, is dat het verschil tussen geweldig en matig." },
      { type: "h3", text: "De bar spoon en zeven" },
      { type: "p", text: "Een bar spoon heeft een lange, gedraaide steel zodat hij soepel tussen je vingers ronddraait tijdens het roeren. De hawthorne-zeef (met veerrand) hoort op een shaker; de julep-zeef hoort op een roerglas; een fijne theezeef gebruik je voor \"dubbel zeven\" bij muntblaadjes of vruchtvlees." },
      { type: "h3", text: "Overige onmisbare stukken" },
      { type: "p", text: "Een muddler (stamper zonder gelakte afwerking) voor kruiden of fruit, een channel knife of dunschiller voor citrusschil, een zwaar mixing glass specifiek voor stirred-down-cocktails, en losse ijsvormen voor grote ijsblokken." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Begin met vier dingen: een Boston-shaker-set, een jigger, een bar spoon en een hawthorne-zeef. Dat dekt letterlijk elk recept in deze cursus." },
    ],
    takeaways: [
      "Een jigger is geen beginnershulpmiddel maar de manier waarop professionals consistent goede cocktails maken.",
      "Elk zeeftype heeft een eigen taak: hawthorne voor shaken, julep voor roeren, fijne zeef voor de laatste polish.",
      "Vier basisstukken dekken vrijwel alles; investeer pas verder als je merkt waar je zelf tegenaan loopt.",
    ],
  },
  {
    id: "glaswerk",
    part: "fundamenten",
    number: 3,
    title: "Glaswerk: de juiste vorm voor het juiste doel",
    intro: "Een glas is geen decoratie: de vorm bepaalt hoe snel een drank opwarmt, hoe aroma je neus bereikt, en hoeveel ijs er logisch in past.",
    blocks: [
      { type: "h3", text: "De coupe en Nick & Nora" },
      { type: "p", text: "De coupe, een ondiepe, brede schaal op een steel, is het glas voor \"up\" geserveerde cocktails zoals een Daiquiri of Martini. De brede opening laat aroma snel vrijkomen. Het Nick & Nora-glas (kleiner, meer gebogen) behoudt de koude langer en wordt door veel moderne bartenders geprefereerd." },
      { type: "h3", text: "Rocks, highball en Collins" },
      { type: "p", text: "Een rocks-glas (kort, dikke bodem) is voor drankjes over ijs, met ruimte om te muddelen zonder te breken. Highball en Collins-glazen zijn hoog en rechte, met genoeg volume voor voldoende koelend ijs bij longdrinks." },
      { type: "h3", text: "Specialistische vormen" },
      { type: "p", text: "Een flute behoudt koolzuurbubbels langer dan een breed glas, essentieel voor champagnecocktails. Een koperen beker bij een Moscow Mule geleidt kou uitzonderlijk goed, waardoor de buitenkant zichtbaar beslaat. Tiki-cocktails krijgen vaak thematische bekers, puur voor de theatrale traditie van dat genre." },
      { type: "table", headers: ["Glas", "Gebruik voor", "Waarom"], rows: [
        ["Coupe / Nick&Nora", "\"Up\" cocktails zonder ijs", "Aroma vrij, geen ijs nodig na schudden/roeren"],
        ["Rocks", "On-the-rocks, muddled", "Stevige bodem, ruimte voor groot ijsblok"],
        ["Highball/Collins", "Longdrinks", "Volume voor voldoende koelend ijs"],
        ["Flute", "Champagnecocktails", "Behoudt koolzuur"],
      ] },
    ],
    takeaways: [
      "Glasvorm bepaalt aroma-afgifte, opwarmsnelheid én hoeveelheid ijs. Het is functioneel, niet decoratief.",
      "\"Up\" cocktails zijn al gekoeld vóór het inschenken; longdrinks hebben juist volume nodig om zelf koud te blijven.",
      "Een set van 4 (coupe, rocks, highball, wijnglas) dekt vrijwel elk recept.",
    ],
  },
  {
    id: "ijs",
    part: "fundamenten",
    number: 4,
    title: "IJs: de onderschatte hoofdingrediënt",
    intro: "Beginnende thuisbartenders behandelen ijs als bijzaak. Professionals behandelen het als een ingrediënt met een eigen receptuur.",
    blocks: [
      { type: "h3", text: "Waarom verdunning geen fout is" },
      { type: "p", text: "Een cocktail zonder verdunning smaakt onaangenaam geconcentreerd. Tijdens shaken of roeren smelt bewust 20-30% van het ijs mee in de drank; die waterlaag \"opent\" de smaken en houdt alcohol, zuur en zoet in balans. Dit is waarom bartenders een exacte schud- of roertijd aanhouden in plaats van \"tot het koud aanvoelt.\"" },
      { type: "h3", text: "IJsvormen en hun functie" },
      { type: "p", text: "Standaard kubusijs is het werkpaard voor shaken en de meeste longdrinks. Groot-formaat ijs (één blok van 4-5 cm) smelt trager en is de standaard voor Old Fashioned-achtige drankjes: langer goed gekoeld zonder snel waterig te worden. Crushed ijs smelt juist razendsnel en wordt bewust gebruikt bij Mojito's, Juleps en tiki-cocktails voor een intense, snelle verdunning." },
      { type: "h3", text: "Praktische vuistregel" },
      { type: "p", text: "Reken op ongeveer 150 gram ijs per geserveerde cocktail. Dit dekt zowel het ijs in de shaker als het ijs waarover je serveert. Kom je ijs tekort tijdens een feest, dan verwatert elke volgende ronde merkbaar sneller." },
      { type: "box", kind: "warning", label: "Veelgemaakte fout", text: "IJs hergebruiken dat al in een glas heeft gezeten. Dat ijs is al deels gesmolten en verdund met de vorige drank. Gebruik voor elke stap vers ijs." },
    ],
    takeaways: [
      "Verdunning door ijs is een opzettelijk onderdeel van de receptuur, niet een neveneffect om te minimaliseren.",
      "Grof ijs = trage verdunning (Old Fashioned-stijl), fijn/crushed ijs = snelle verdunning (Mojito/tiki-stijl).",
      "Reken ruim: te weinig ijs tijdens een feest verpest elke volgende ronde.",
    ],
  },

  {
    id: "gedistilleerd",
    part: "ingredienten",
    number: 5,
    format: "praktijk",
    title: "Sterke drank: wat elke fles meebrengt",
    intro: "De sterke drank is het grootste deel van je cocktail. Weet je wat hij meebrengt, dan weet je welke kant de cocktail op gaat, en waarmee je kunt wisselen.",
    core: ["Twee dingen bepalen hoe een sterke drank smaakt: waar hij van gemaakt is (graan, suikerriet, agave, druiven) en of hij op een houten vat heeft gelegen.", "Ongerijpt is fris en licht: wodka, witte rum, tequila blanco, gin. Op hout gerijpt is warmer en ronder, met vanille en karamel: bourbon, donkere rum, cognac.", "Lichte dranken passen bij fris en fruitig, zoals citrus en munt. Gerijpte dranken passen bij warm en kruidig, zoals bitters, vermout en honing."],
    taste: { title: "Wat je proeft", rows: [{ label: "Licht", tone: "groen", text: "Wodka, witte rum, gin, tequila. Fris en strak; de rest mag spreken." }, { label: "Gerijpt", tone: "bruin", text: "Bourbon, rye, donkere rum, cognac. Vanille, karamel en hout." }, { label: "Karakter", tone: "rood", text: "Mezcal, gin, rokerige whisky. Een kleine scheut zet de toon." }] },
    steps: ["Proef de sterke drank eerst puur, met een paar druppels water. Dat is wat je cocktail draagt.", "Kies een lichte drank voor frisse cocktails en een gerijpte voor sterke, geroerde cocktails.", "Wissel binnen dezelfde familie: rye voor bourbon, of rum voor tequila in een sour."],
    mistake: "Denken dat een dure fles een slechte cocktail redt. Balans en verse citrus doen meer; een degelijke middenklassefles is voor cocktails meestal genoeg.",
    tryIt: { text: "Maak een Daiquiri met witte rum en daarna een met donkere rum. Zelfde verhouding, heel andere drank.", recipeId: "daiquiri" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "likeuren-bitters",
    part: "ingredienten",
    number: 6,
    format: "praktijk",
    title: "Vermout, likeur en bitters: kleine scheut, groot effect",
    intro: "Een paar milliliter likeur of een dash bitters bepaalt vaak meer dan de sterke drank zelf. Hier zit het verschil tussen prima en raak.",
    core: ["Vermout is wijn met kruiden en een beetje extra alcohol. Rood is zoet en kruidig, droog is licht en fris. Omdat het wijn is, wordt een open fles na een tijd vlak en zurig.", "Likeuren brengen zoet én smaak tegelijk: sinaasappel, kers, koffie, kruiden. Daarom tellen ze mee als het zoete deel van je balans.", "Bitters gebruik je in druppels. Ze maken een drankje niet bitter, maar verbinden de smaken en geven diepte, zoals zout in eten."],
    taste: { title: "Wat je proeft", rows: [{ label: "Vermout", tone: "bruin", text: "Kruidig en wijnachtig. Vlak of zurig? Dan staat de fles te lang open." }, { label: "Likeur", tone: "rood", text: "Zoet met een duidelijke smaak. Te veel en het wordt stroperig." }, { label: "Bitters", tone: "groen", text: "Apart proef je ze niet, maar zonder smaakt een Old Fashioned plat." }] },
    steps: ["Zet vermout na het openen in de koelkast en maak hem binnen een maand of twee op.", "Gebruik je een zoete likeur, neem dan minder siroop.", "Begin met 1 of 2 dashes bitters, proef, en voeg er zo nodig één toe."],
    mistake: "Een oude, open fles vermout blijven gebruiken. Een Negroni of Manhattan smaakt dan vlak en zurig, terwijl de rest klopt.",
    tryIt: { text: "Maak een Old Fashioned zonder bitters en een met 2 dashes Angostura. Proef ze naast elkaar.", recipeId: "old_fashioned" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "vers",
    part: "ingredienten",
    number: 7,
    format: "praktijk",
    title: "Vers: citrus, siroop en eiwit",
    intro: "Hier zit de grootste winst. Vers geperst citroensap maakt meer verschil dan een dure fles.",
    core: ["Vers sap is fris en geurig door de oliën uit de schil. Sap uit een fles mist die frisheid, en na een dag in de koelkast is het ook al grotendeels weg.", "Suikersiroop is suiker opgelost in water, half om half. Losse suiker lost in een koude shaker slecht op en blijft knarsen.", "Eiwit geeft geen smaak maar textuur: een zachte schuimkraag. Schud daarvoor eerst zonder ijs, zodat het eiwit kan opschuimen."],
    taste: { title: "Wat je proeft", rows: [{ label: "Vers sap", tone: "groen", text: "Fris, geurig en levendig." }, { label: "Flessensap", tone: "rood", text: "Plat, soms wat bitter of kunstmatig." }, { label: "Met eiwit", tone: "bruin", text: "Zacht en romig, met een dikke schuimlaag." }] },
    steps: ["Pers citroen of limoen op de dag zelf, liefst vlak voor gebruik.", "Maak siroop: suiker en heet water half om half, roeren tot het helder is, koel bewaren.", "Met eiwit: eerst 15 seconden schudden zonder ijs, dan met ijs, en dubbel zeven."],
    mistake: "Sap van gisteren of uit een fles gebruiken en het recept de schuld geven als de sour plat smaakt.",
    tryIt: { text: "Maak een Whiskey Sour met eiwit: eerst zonder ijs schudden, dan met ijs. Kijk naar de schuimkraag.", recipeId: "whiskey_sour" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "garnering",
    part: "ingredienten",
    number: 8,
    format: "praktijk",
    title: "Garnering: geur eerst",
    intro: "Je ruikt een cocktail voordat je hem proeft. Een goede garnering doet daarom iets voor je neus, niet alleen voor het oog.",
    core: ["Knijp je een stukje sinaasappel- of citroenschil uit boven het glas, dan spuiten de oliën over de drank. De eerste geur verandert, en daarmee hoe de hele drank smaakt.", "Munt klap je tussen je handen in plaats van te pletten. Dan komt de geur vrij zonder bittere, kapotte blaadjes.", "Sommige garneringen geven smaak: een olijf maakt een Martini hartig, een kers voegt zoet toe. Kies bewust."],
    taste: { title: "Wat het doet", rows: [{ label: "Citrusschil", tone: "groen", text: "Frisse eerste geur. Mooi op sterke, geroerde cocktails." }, { label: "Munt", tone: "groen", text: "Fris en koel. Klappen, niet kneuzen." }, { label: "Olijf of kers", tone: "bruin", text: "Een klein smaakaccent: hartig of zoet." }] },
    steps: ["Snijd een stuk schil zonder het witte deel; dat is bitter.", "Houd de buitenkant naar het glas en knijp het uit boven de drank.", "Wrijf het daarna langs de rand en leg het erin, of laat het weg."],
    mistake: "Een schijfje citroen op de rand leggen en denken dat het iets doet. Het oogt mooi, maar de geur komt pas vrij als je de schil uitknijpt.",
    tryIt: { text: "Maak twee Negroni's en knijp bij één een stukje sinaasappelschil uit. Ruik en proef het verschil.", recipeId: "negroni" },
    blocks: [],
    takeaways: [],
  },

  {
    id: "basistechnieken",
    part: "techniek",
    number: 9,
    format: "praktijk",
    title: "Shaken, roeren of bouwen?",
    intro: "Waarom shake je de ene cocktail en roer je de andere? Dat hangt niet af van smaak of stijl, maar van wat er in het glas gaat.",
    core: ["Shaken doe je als er sap, ei of room in zit. Je mengt hard, koelt snel en klopt er lucht in. De drank wordt fris en licht troebel.", "Roeren doe je als er alleen heldere, alcoholische dingen in zitten, zoals in een Martini of Negroni. Je koelt en verdunt zonder lucht; de drank blijft helder en zijdezacht.", "Bouwen is direct in het glas: ijs, drank, aanvullen en één keer roeren. Voor longdrinks met prik, zodat het koolzuur blijft."],
    taste: { title: "Wanneer wat", rows: [{ label: "Shaken", tone: "groen", text: "Sap, eiwit, room. Fris en licht, met schuim." }, { label: "Roeren", tone: "bruin", text: "Alleen drank. Helder, zacht en sterk." }, { label: "Bouwen", tone: "rood", text: "Met prik. Het koolzuur blijft." }] },
    steps: ["Kijk naar de ingrediënten: sap of ei? Shaken. Alleen drank? Roeren. Prik erin? Bouwen.", "Shaken: shaker voor twee derde vol ijs, 10 tot 15 seconden kort en hard.", "Roeren: mengglas vol ijs, rustig 20 tot 30 seconden, dan zeven."],
    mistake: "Een Martini shaken omdat het stoer oogt. Hij wordt troebel en vol luchtbelletjes, en verliest zijn zijdezachte textuur.",
    demos: ["shaken", "stirred", "muddle"],
    tryIt: { text: "Maak een Martini één keer geroerd en één keer geschud. Kijk en proef het verschil in helderheid en textuur.", recipeId: "martini" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "verdunning-temperatuur",
    part: "techniek",
    number: 10,
    format: "praktijk",
    title: "Koud en verdund: water als ingrediënt",
    intro: "Smeltwater is geen bijzaak, het hoort bij het recept. Zonder smaakt een cocktail scherp en heet, met te veel waterig.",
    core: ["Als je shaket of roert, koelt het ijs de drank en smelt er een deel. Dat water maakt de alcohol zachter en laat de smaken opengaan.", "Veel ijs koelt snel met precies genoeg water. Weinig ijs smelt weg voordat de drank koud is, en dan wordt hij juist waterig.", "Een koud glas houdt de drank koud. Een warm glas trekt er meteen de kou uit."],
    taste: { title: "Wat je proeft", rows: [{ label: "Te weinig", tone: "rood", text: "Scherp, de alcohol brandt, de smaken zitten op elkaar." }, { label: "Te veel", tone: "bruin", text: "Dun en waterig, de smaken vervagen." }, { label: "Goed", tone: "groen", text: "Koud, zacht en helder van smaak." }] },
    steps: ["Gebruik veel, droog en hard ijs: een volle shaker, niet een paar losse blokjes.", "Tel: 10 tot 15 seconden shaken of 20 tot 30 seconden roeren. Ga niet af op hoe koud de shaker voelt.", "Zet het glas in de vriezer, of vul het met ijswater terwijl je mixt."],
    mistake: "Stoppen zodra de shaker koud aanvoelt. Het metaal is binnen seconden koud, de drank nog lang niet.",
    tryIt: { text: "Roer een Manhattan 10 seconden en proef met een rietje. Roer daarna nog 20 seconden en proef opnieuw.", recipeId: "manhattan" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "sour-formule",
    part: "techniek",
    number: 11,
    format: "praktijk",
    title: "De sour: één skelet, veel cocktails",
    intro: "Whiskey Sour, Daiquiri, Margarita, Gimlet, Sidecar: steeds dezelfde opbouw met een andere basis. Snap je het skelet, dan ken je ze allemaal.",
    core: ["Een sour bestaat uit drie delen: sterke drank, zuur (citroen of limoen) en zoet (siroop of likeur). De sterke drank is het grootste deel; zuur en zoet zijn ongeveer even groot.", "Zuur en zoet houden elkaar in toom. Zo houdt de sterke drank de hoofdrol en wordt de drank fris, maar niet scherp.", "Met prik erbij wordt een sour lang en licht, zoals een Tom Collins. Met eiwit wordt hij zacht en romig, zoals een Whiskey Sour of Clover Club."],
    taste: { title: "De familie", rows: [{ label: "Kort", tone: "groen", text: "Daiquiri, Margarita, Gimlet. Strak en fris, zonder ijs geserveerd." }, { label: "Met eiwit", tone: "bruin", text: "Whiskey Sour, Clover Club. Zacht en romig." }, { label: "Lang", tone: "rood", text: "Tom Collins, Gin Fizz. Licht en bruisend." }] },
    steps: ["Herken de drie delen in een recept: wat is sterk, wat is zuur, wat is zoet?", "Houd ze in die verhouding: veel sterk, zuur en zoet in balans.", "Kies je stijl: kort in een coupe, met eiwit, of lang met soda over ijs."],
    mistake: "Een likeur vergeten mee te tellen als zoet. In een Margarita is de triple sec het zoet; extra siroop maakt hem te zoet.",
    tryIt: { text: "Maak een Tom Collins: in feite een gin-sour, lang gemaakt met soda over ijs. Proef hoe de prik hem lichter maakt.", recipeId: "tom_collins" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "finesse",
    part: "techniek",
    number: 12,
    format: "praktijk",
    title: "De afwerking: zeven, laagjes en de laatste geur",
    intro: "Twee cocktails met hetzelfde recept kunnen er heel anders uitzien en aanvoelen. Het verschil zit in de laatste tien seconden.",
    core: ["Dubbel zeven, door de gewone zeef én een fijn theezeefje, haalt ijssplinters en stukjes fruit eruit. Een geschudde cocktail zonder ijs wordt zo glad in plaats van korrelig.", "Een drijflaag blijft liggen omdat zware, zoete vloeistof zinkt en lichte drijft. Giet daarom langzaam over de bolle kant van een lepel.", "Een uitgeknepen schil boven het glas is het laatste wat jij doet en het eerste wat je gast ruikt."],
    taste: { title: "Wat het doet", rows: [{ label: "Dubbel zeven", tone: "groen", text: "Glad mondgevoel, geen ijssplinters." }, { label: "Drijflaag", tone: "rood", text: "Mooi beeld, en een eerste slok die anders smaakt." }, { label: "Uitgeknepen schil", tone: "bruin", text: "Een frisse eerste geur." }] },
    steps: ["Geschud en zonder ijs geserveerd? Altijd dubbel zeven.", "Voor een drijflaag: houd een lepel met de bolle kant boven, vlak boven de drank, en giet heel langzaam.", "Rond af met een uitgeknepen schil en serveer meteen; een cocktail wacht niet."],
    mistake: "Snel gieten bij een drijflaag. De lagen mengen meteen; langzaam over de lepel is het hele geheim.",
    tryIt: { text: "Maak een Whiskey Sour en giet er langzaam een drijflaag rode wijn op. Zo heb je een New York Sour.", recipeId: "whiskey_sour" },
    blocks: [],
    takeaways: [],
  },

  // Deel IV in de praktijkopbouw: waarom, de kern, wat je proeft, zo doe je
  // het, een veelgemaakte fout en iets om zelf te maken. Kort en toepasbaar.
  {
    id: "families",
    part: "smaak",
    number: 13,
    format: "praktijk",
    title: "Zoet en zuur in balans",
    intro: "Bijna elke cocktail die \"net niet\" smaakt, is uit balans tussen zoet en zuur. Snap je dit, dan kun je elk recept zelf bijsturen.",
    core: [
      "Zuur, van citroen of limoen, maakt een drankje fris en levendig. Zoet, van siroop of likeur, maakt het rond en zacht en dempt de scherpte van de alcohol.",
      "Ze houden elkaar in evenwicht: meer zuur vraagt om meer zoet, en andersom. In balans proef je allebei, maar springt geen van de twee eruit.",
    ],
    taste: {
      title: "Wat je proeft",
      rows: [
        { label: "Te zuur", tone: "rood", text: "Prikt en trekt je wangen samen. De drank smaakt dun." },
        { label: "Te zoet", tone: "bruin", text: "Plakkerig. De alcohol valt weg en de laatste slok is zwaar." },
        { label: "In balans", tone: "groen", text: "Fris begin, zachte afdronk, en je hebt zin in nog een slok." },
      ],
    },
    steps: [
      "Begin met ongeveer 2 delen sterke drank, 1 deel citroen of limoen en ¾ deel siroop.",
      "Proef met een rietje voordat je inschenkt.",
      "Stuur bij in kleine stapjes van 5 ml: te zuur, wat siroop erbij; te zoet, wat citroen.",
    ],
    mistake: "Alles tegelijk aanpassen. Verander één ding en proef opnieuw. En citroenen verschillen per stuk: proeven gaat altijd boven het recept.",
    tryIt: { text: "Maak twee Daiquiri's: één volgens het recept en één met 5 ml extra siroop. Proef ze naast elkaar. Welke vind jij lekkerder?", recipeId: "daiquiri" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "smaakcombinatie",
    part: "smaak",
    number: 14,
    format: "praktijk",
    title: "Bitter, zout en sterk: wat ze doen",
    intro: "Zoet en zuur zijn de basis. Bitter, zout en de alcohol zelf bepalen of een drankje vlak blijft of diepte krijgt.",
    core: [
      "Bitter remt zoet af en maakt een drankje droger. Een paar dashes bitters of een scheut Campari zorgen dat de smaak blijft hangen na het slikken.",
      "Zout proef je niet als zout, maar alles wordt voller: bitter wordt zachter, fruit en citrus springen meer naar voren.",
      "Alcohol geeft warmte en draagt de geuren. Te weinig en het drankje voelt waterig, te veel en het brandt. Kou en water van het ijs temperen dat.",
    ],
    taste: {
      title: "Wat je proeft",
      rows: [
        { label: "Bitter", tone: "rood", text: "Droog en lang op de tong. Te veel: hard en medicinaal." },
        { label: "Zout", tone: "bruin", text: "Alles smaakt voller. Te veel: dan proef je het wél." },
        { label: "Sterk", tone: "groen", text: "Warmte in je keel. Te veel: het brandt en overstemt de rest." },
      ],
    },
    steps: [
      "Te zoet, maar wordt hij met meer citroen te zuur? Voeg 1 of 2 dashes bitters toe.",
      "Smaakt hij vlak of te bitter? Probeer een paar korrels zout. Dat merk je meteen.",
      "Brandt hij? Roer of shake iets langer, zodat er meer water bij komt, in plaats van meer siroop.",
    ],
    mistake: "Bitter of alcohol wegpoetsen met suiker. Dan wordt het drankje zwaar en plakkerig. Een beetje zout of wat meer verdunning doet vaak meer.",
    tryIt: { text: "Maak een Negroni volgens het recept en proef. Doe er dan een paar korrels zout bij en proef opnieuw. Merk hoe het bitter zachter wordt.", recipeId: "negroni" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "ontwerpen",
    part: "smaak",
    number: 15,
    format: "praktijk",
    title: "Je eigen twist: één ding tegelijk",
    intro: "Je hoeft geen nieuwe cocktail te verzinnen om iets eigens te maken. Veel bekende cocktails zijn een klassieker waarin één ding is gewisseld.",
    core: [
      "Een klassieker is een skelet dat al werkt. Wissel je één onderdeel voor iets dat dezelfde rol speelt, dan blijft de balans grotendeels kloppen en verandert alleen het karakter.",
      "Twijfel je of twee smaken samengaan? Proef ze los na elkaar. Smaken die op elkaar lijken versterken elkaar (gin en citroen). Smaken die tegen elkaar ingaan maken het spannend (rokerig met fruit, bitter met sinaasappel).",
    ],
    taste: {
      title: "Wat je kunt wisselen",
      rows: [
        { label: "Sterk", tone: "groen", text: "Rum, tequila, gin of whisky. De balans blijft, het karakter verandert." },
        { label: "Zoet", tone: "bruin", text: "Siroop, honing, agave of een likeur. Een likeur is minder zoet: neem er iets meer van." },
        { label: "Zuur", tone: "rood", text: "Citroen, limoen of grapefruit. Grapefruit is milder en iets bitter." },
      ],
    },
    steps: [
      "Kies een klassieker die je al lekker vindt.",
      "Wissel één onderdeel voor iets met dezelfde rol.",
      "Proef, stuur bij in stapjes van 5 ml en schrijf op wat je deed.",
    ],
    mistake: "Drie dingen tegelijk wisselen. Smaakt het niet, dan weet je niet waardoor. Smaakt het wel, dan weet je niet waarom.",
    tryIt: { text: "Maak een Whiskey Sour, maar met honingsiroop (honing en warm water, half om half) in plaats van suikersiroop. Wat verandert er? Zo ontstond de Gold Rush.", recipeId: "whiskey_sour" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "menu",
    part: "smaak",
    number: 16,
    format: "praktijk",
    title: "Een menu dat voor iedereen werkt",
    intro: "Je gasten hebben allemaal een andere smaak. Een goed menu geeft iedereen iets, en laat jou ook nog van de avond genieten.",
    core: [
      "Denk in smaken, niet in favorieten: iets fris en lichts, iets sterks of bitters, iets zachts of zoets, en altijd een volwaardige optie zonder alcohol.",
      "Drie tot vijf cocktails is genoeg. Meer keuze betekent meer flessen, meer werk en langer wachten aan de bar.",
      "Kies cocktails die ingrediënten delen, en minstens één die je vooraf kunt mengen. Alles zonder sap, ei of room, zoals een Negroni, kan uren eerder in een fles in de koelkast.",
    ],
    taste: {
      title: "Zo dek je de smaken",
      rows: [
        { label: "Fris", tone: "groen", text: "Paloma, Gin Tonic, Mojito." },
        { label: "Sterk", tone: "rood", text: "Negroni, Old Fashioned." },
        { label: "Zacht", tone: "bruin", text: "Espresso Martini, Whiskey Sour." },
        { label: "Zonder", tone: "groen", text: "Een eigen limonade of een Shirley Temple." },
      ],
    },
    steps: [
      "Kies één cocktail per smaak, plus een alcoholvrije.",
      "Vraagt een cocktail een fles die je verder nergens voor gebruikt? Kies dan iets met wat je al hebt.",
      "Zet één cocktail vooraf klaar, zodat je niet de hele avond aan het shaken bent.",
    ],
    mistake: "Alleen kiezen wat je zelf lekker vindt. Jij drinkt er één van, je gasten de rest.",
    tryIt: { text: "Kies vier cocktails voor je volgende avond: een frisse, een sterke, een zachte en een zonder alcohol. Maak de sterke vooraf klaar en proef hem voordat de gasten komen.", recipeId: "negroni" },
    blocks: [],
    takeaways: [],
  },

  {
    id: "mise-en-place",
    part: "vak",
    number: 17,
    title: "Mise en place: voorbereiding is alles",
    intro: "\"Mise en place\", Frans voor \"alles op zijn plek\", is een keukentraditie die professionele bars één op één hebben overgenomen.",
    blocks: [
      { type: "h3", text: "Wat hoort er bij bar-mise en place?" },
      { type: "p", text: "Vóór de eerste gast arriveert: alle benodigde flessen binnen handbereik en in de juiste volgorde, citrus geperst (zo dicht mogelijk bij het moment zelf), siropen klaar, garneringen gesneden en op ijs bewaard, voldoende ijs binnen handbereik, glazen voorgekoeld waar nodig, en een schone werkplek." },
      { type: "h3", text: "Recepten uit je hoofd en een logische werkplek" },
      { type: "p", text: "Voor een feest van meer dan een paar gasten is het onhoudbaar om bij elke cocktail een recept op te zoeken. Oefen je menu vooraf tot je de verhoudingen kent. Een efficiënte bar-opstelling volgt de volgorde van bereiding: sterkedrank het dichtst bij je shaker, dan versterkte wijnen/likeuren, dan bitters, dan verse ingrediënten, met glaswerk en ijs binnen een armlengte." },
      { type: "h3", text: "Wat kan wachten, wat niet" },
      { type: "p", text: "Siropen en de meeste garneringen kunnen uren tot een dag vooraf klaar worden gemaakt en gekoeld bewaard. Citrussap en muntblaadjes juist niet: die verliezen binnen uren aan kwaliteit. Ken dit onderscheid en je voorkomt zowel onnodig laatste-moment-werk als kwaliteitsverlies." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Maak een checklist per feest met daarop: ijs, glazen per type, te snijden garnering, en welke cocktails je vooraf kunt batchen. Tien minuten planning scheelt uren improviseren." },
    ],
    takeaways: [
      "Mise en place is geen keukenjargon voor bartenders: het is dezelfde discipline, direct toepasbaar aan de bar.",
      "Ken je recepten uit je hoofd voor het menu dat je die avond serveert.",
      "Onderscheid wat vooraf kan (siropen, de meeste garnering) van wat pas op het laatste moment mag (citrussap, munt).",
    ],
  },
  {
    id: "batchen-groepen",
    part: "vak",
    number: 18,
    title: "Batchen en grote groepen bedienen",
    intro: "Zodra je voor meer dan een handvol gasten schenkt, verandert de opgave: je maakt niet langer één cocktail perfect, je maakt tientallen cocktails consistent.",
    blocks: [
      { type: "h3", text: "Wat batchen wél en niet oplost" },
      { type: "p", text: "Batchen (vooraf mengen zonder ijs, gekoeld bewaard tot het serveermoment) bespaart tijd en zorgt voor consistente kwaliteit. Het werkt het best bij gestirde cocktails zonder vers sap, eiwit of zuivel. Cocktails die afhankelijk zijn van net-geshakete textuur verliezen die kwaliteit zodra je ze te vroeg klaarmaakt." },
      { type: "h3", text: "Hoe je een batch berekent" },
      { type: "p", text: "Vermenigvuldig de verhoudingen van je recept met het gewenste aantal porties, en voeg apart een berekende hoeveelheid water toe (doorgaans 20-25% van het totale drankvolume) om het verdunningseffect van ijs te simuleren, aangezien de batch zelf zonder ijs wordt gemengd." },
      { type: "h3", text: "Tempo, ijs-logistiek en taakverdeling" },
      { type: "p", text: "Reken op ongeveer twee drankjes per gast in het eerste uur, daarna gemiddeld één per uur. Reken op 150 gram ijs per cocktail. Bij grote groepen is ijs vaak de eerste bottleneck, niet drank. Bij grotere groepen werkt het beter om taken te splitsen (iemand die schenkt, iemand die garneert en serveert) dan om alles door één persoon te laten doen." },
      { type: "box", kind: "warning", label: "Veelgemaakte fout", text: "Een volledige batch, inclusief de verdunningswater-toevoeging, te vroeg klaarmaken en uren laten wachten. Maak een batch idealiter dezelfde dag." },
    ],
    takeaways: [
      "Batchen werkt het best bij gestirde cocktails zonder vers sap, eiwit of zuivel.",
      "Reken vooraf: 2 drankjes per gast het eerste uur, daarna 1 per uur, en 150 g ijs per drankje.",
      "Splits taken bij grotere groepen: één persoon die alles doet, is een gegarandeerde bottleneck.",
    ],
  },
  {
    id: "gastvrijheid",
    part: "vak",
    number: 19,
    title: "Gastvrijheid: het onzichtbare ingrediënt",
    intro: "De beste bartenders ter wereld worden niet alleen geroemd om technische vaardigheid, maar om hoe ze gasten laten voelen.",
    blocks: [
      { type: "h3", text: "Vragen stellen en het verhaal vertellen" },
      { type: "p", text: "In plaats van een cocktail op te leggen, vraag je naar voorkeuren: bitter of zoet, sterk of licht. Een cocktail met een kort, oprecht verhaal (waar hij vandaan komt, waarom je 'm hebt gekozen) wordt door gasten anders gewaardeerd dan exact dezelfde drank zonder die context. Kennis delen is zelf onderdeel van de gastvrijheidservaring." },
      { type: "h3", text: "Tempo lezen en iedereen een volwaardige optie geven" },
      { type: "p", text: "Een goede gastheer voelt aan wanneer een gezelschap toe is aan de volgende ronde. Gasten die niet drinken verdienen een even doordachte, volwaardige optie als de rest, geen fris uit een pak terwijl iedereen anders een zorgvuldig gemaakte cocktail krijgt." },
      { type: "h3", text: "Jezelf niet vergeten" },
      { type: "p", text: "Een gastheer die de hele avond alleen maar drankjes voor anderen maakt en zelf nooit kan genieten, is geen duurzaam model. Batchtechnieken bestaan voor een groot deel precies om dit te voorkomen: hoe meer je vooraf voorbereidt, hoe meer ruimte je zelf overhoudt." },
    ],
    takeaways: [
      "Vragen naar voorkeur vóór het serveren voorkomt een misser en toont aandacht.",
      "Een kort verhaal bij een cocktail verandert hoe gasten 'm waarderen: kennis delen is onderdeel van de ervaring.",
      "Gastvrijheid geldt ook richting jezelf: goede voorbereiding is wat jou in staat stelt om ook zelf van het feest te genieten.",
    ],
  },
  {
    id: "signature",
    part: "vak",
    number: 20,
    title: "Je eigen signature cocktail",
    intro: "De laatste les is geen nieuwe theorie, maar een opdracht: alles wat je hebt geleerd samenbrengen in één cocktail die echt van jou is.",
    blocks: [
      { type: "h3", text: "Stap 1 & 2: verhaal en basisspirit" },
      { type: "p", text: "Een signature cocktail begint niet bij een ingrediënt, maar bij een idee: een herinnering, een seizoen, een gevoel dat je wilt oproepen. Dat verhaal stuurt daarna je ingrediëntkeuzes. Gebruik de bouwstenen-methode uit Les 15 om een familie en basisspirit te kiezen die bij dat verhaal passen." },
      { type: "h3", text: "Stap 3 & 4: bouwen en benoemen" },
      { type: "p", text: "Volg het iteratieve proces: eerst de kernformule, dan pas finesse, telkens één variabele per keer aanpassen, en noteer elke versie. Reken op minstens vijf tot tien testrondes; zelfs professionals bereiken zelden hun beste versie in de eerste poging. Geef je cocktail daarna een naam en een kort, authentiek ontstaansverhaal." },
      { type: "h3", text: "Stap 5: vastleggen" },
      { type: "p", text: "Voeg je definitieve recept toe aan je eigen receptenverzameling zodat het niet verloren gaat, en zodat je het net zo makkelijk kunt opschalen voor een groep als elke andere cocktail in je collectie." },
      { type: "box", kind: "tip", label: "Laatste pro-tip van deze cursus", text: "De beste signature cocktails ontstaan zelden uit een poging om origineel te zijn om het origineel-zijn. Ze ontstaan uit een oprechte poging om een specifiek probleem op te lossen of een specifiek gevoel op te roepen." },
    ],
    takeaways: [
      "Een goede cocktail begint bij een idee of gevoel, niet bij een willekeurige ingrediëntenlijst.",
      "Elke techniek en elk principe uit de vorige negentien lessen komt hier samen in één praktische opdracht.",
      "Van basis naar pro is geen eindpunt maar een herhaalbaar proces: proeven, bijstellen, vastleggen, en opnieuw beginnen.",
    ],
  },

  // Deel VI is een optionele, verdiepende module: technieken die je in high-end
  // bars ziet maar niet nodig zijn om een goede thuisbartender te worden. Wie
  // de cursus na Les 20 afsluit, heeft al "van basis tot pro" doorlopen.
  {
    id: "infusies",
    part: "geavanceerd",
    number: 21,
    format: "praktijk",
    title: "Infusies: je eigen smaak in een fles",
    intro: "Wil je een smaak die je niet kunt kopen, zoals rozemarijngin of kaneelbourbon? Laat de drank het werk doen.",
    core: ["Alcohol trekt geur en smaak uit kruiden, specerijen, schil en fruit. Jij hoeft alleen te wachten en te proeven.", "Fijne dingen, zoals verse kruiden en bloemen, trekken snel: in een paar uur. Harde dingen, zoals kaneel of vanille, hebben dagen nodig. Te lang wordt bitter.", "Droge ingrediënten in sterke drank kunnen buiten de koelkast. Met vers fruit of verse kruiden hoort de fles in de koelkast en moet hij snel op."],
    taste: { title: "Hoe lang", rows: [{ label: "Verse kruiden", tone: "groen", text: "Een paar uur. Daarna bitter." }, { label: "Citrusschil", tone: "bruin", text: "Een tot drie dagen, zonder het witte deel." }, { label: "Specerijen", tone: "rood", text: "Een paar dagen tot een week." }] },
    steps: ["Begin klein, met een flesje van 100 à 200 ml.", "Proef elke dag, of bij verse kruiden elk uur.", "Zeef zodra het lekker is, niet later."],
    mistake: "De pot vergeten en een week later een bittere drank vinden. Proeven is het hele proces.",
    tryIt: { text: "Doe een paar repen sinaasappelschil in een klein flesje bourbon. Proef na een en na twee dagen, en maak er een Old Fashioned mee.", recipeId: "old_fashioned" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "fat-washing",
    part: "geavanceerd",
    number: 22,
    format: "praktijk",
    title: "Fat-washing: boter of olijfolie in je drank",
    intro: "Met vet krijg je een smaak in een sterke drank die anders niet bestaat, zoals bruine boter in rum of olijfolie in gin.",
    core: ["Vet neemt smaken op die alcohol alleen niet goed vasthoudt. Meng je warm vet door een sterke drank, dan geeft het die smaken af.", "In de vriezer wordt vet hard en blijft alcohol vloeibaar. Zo schep je het vet eraf en houd je de smaak over.", "Wat overblijft is zachter en voller, met een duidelijke hartige of nootachtige toon."],
    taste: { title: "Klassieke combinaties", rows: [{ label: "Bruine boter", tone: "bruin", text: "Met rum of bourbon: nootachtig en warm." }, { label: "Spek", tone: "rood", text: "Met bourbon: rokerig en hartig." }, { label: "Olijfolie", tone: "groen", text: "Met gin of wodka: fris en hartig, voor een Martini." }] },
    steps: ["Meng een klein beetje gesmolten vet door de drank en laat het een paar uur trekken.", "Zet het een nacht in de vriezer, tot het vet hard is.", "Schep het vet eraf en zeef de drank door een koffiefilter."],
    mistake: "Te vroeg zeven, voordat het vet echt hard is. Dan blijven er vette druppels in je drank.",
    tryIt: { text: "Probeer bruine boter in een klein flesje donkere rum en maak er een Old Fashioned met rum van.", recipeId: "old_fashioned" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "clarificatie",
    part: "geavanceerd",
    number: 23,
    format: "praktijk",
    title: "Clarificatie: helder als water",
    intro: "Een cocktail die eruitziet als water, maar smaakt naar fruit en citrus. Clarificatie is theater, en het maakt de drank ook zachter.",
    core: ["Bij melk-clarificatie giet je een zure cocktail in melk. Het zuur laat de melk schiften, en die vlokken vangen alle troebelheid. Wat erdoor druppelt, is helder.", "Je proeft geen melk, maar de drank wordt zachter en ronder: de scherpe randjes zijn eraf.", "Het kost vooral geduld: rustig laten druppelen door een koffiefilter, soms twee keer."],
    taste: { title: "Wat je proeft", rows: [{ label: "Ervoor", tone: "rood", text: "Troebel, fris en scherp." }, { label: "Erna", tone: "groen", text: "Helder, zacht en rond, iets minder zuur." }, { label: "Bewaren", tone: "bruin", text: "Een paar dagen in de koelkast." }] },
    steps: ["Giet de cocktail (met citrus) langzaam in een kleinere hoeveelheid melk en laat het even staan.", "Laat het door een koffiefilter druppelen. Giet het eerste, troebele deel nog een keer terug door het filter.", "Bewaar het heldere resultaat in de koelkast en serveer over een groot ijsblok."],
    mistake: "Roeren of drukken om het sneller te laten gaan. Dan komen de vlokken door het filter en wordt het weer troebel.",
    tryIt: { text: "Maak een kleine milk punch: een Whiskey Sour zonder eiwit, gegoten in melk, en laat het een nacht druppelen.", recipeId: "whiskey_sour" },
    blocks: [],
    takeaways: [],
  },
  {
    id: "carbonatie-rook",
    part: "geavanceerd",
    number: 24,
    format: "praktijk",
    title: "Bubbels, rook en de eerste indruk",
    intro: "Prik, een vleugje rook, het juiste glas: de laatste details maken een goede cocktail onvergetelijk. Maar ze redden nooit een slechte.",
    core: ["Prik voeg je toe met een sodasifon, of door aan te vullen met soda of mousserende wijn. Hoe kouder alles is, hoe beter de prik blijft.", "Rook is geur, geen smaak. Een paar seconden onder een omgekeerd glas is genoeg; langer en je proeft alleen nog as.", "Het eerste wat je gast ziet en ruikt, bepaalt de verwachting: een schoon, koud glas en een verse garnering."],
    taste: { title: "Wat het doet", rows: [{ label: "Prik", tone: "groen", text: "Frisser en lichter; de smaak springt meer naar voren." }, { label: "Rook", tone: "bruin", text: "Een warme, houtige eerste geur." }, { label: "Presentatie", tone: "rood", text: "Bepaalt hoe je de eerste slok beleeft." }] },
    steps: ["Koel alles goed voordat je prik toevoegt: drank, glas en soda.", "Rook een omgekeerd glas een paar seconden en schenk de cocktail er dan in.", "Kijk kritisch naar je glas voordat je serveert: schoon, koud en de juiste vorm."],
    mistake: "Rook of andere trucs gebruiken om een cocktail te redden die niet in balans is. Eerst moet het recept kloppen.",
    tryIt: { text: "Maak een French 75: gin, citroen en siroop, aangevuld met koude mousserende wijn. Proef hoe de prik de drank optilt.", recipeId: "french_75" },
    blocks: [],
    takeaways: [],
  },
];

// Toetsvragen staan in courseQuiz.js (5 per les + eindtoets van 30).
COURSE_LESSONS.forEach(l => { l.quiz = LESSON_QUIZZES[l.id] || []; });
export const FINAL_EXAM = FINAL_EXAM_QUESTIONS;
