// Toetsvragen voor de cursus: 5 per les + een eindtoets van 30.
// Bewust pittig: rekenvragen, praktijksituaties, "welke klopt níet" en
// foute antwoorden die echt aannemelijk klinken (vaak een waarheid uit een
// andere les, of een bekende misvatting) in plaats van evidente onzin.
//
// Formaat: { q, options, explain } — het GOEDE antwoord staat in de data
// altijd als eerste optie; de app husselt de volgorde bij elke poging
// (zie QuizBlock), dus de positie verraadt niets.

const q = (question, correct, wrong, explain) => ({ q: question, options: [correct, ...wrong], correct: 0, explain });

export const LESSON_QUIZZES = {
  geschiedenis: [
    q("Een Sazerac is volgens de logica van deze les het best te omschrijven als…", "Een Old Fashioned met een absint-wassing en een eigen bitter",
      ["Een Manhattan zonder vermout, met cognac en een scheut absint als basis", "Een sour waarin absint de plaats van het citrussap volledig inneemt", "Een punch waarvan de citrus, het water en de specerijen zijn weggelaten"],
      "Bijna elke klassieker is een variatie op sterkedrank, suiker, water en bitters. De Sazerac voegt daar een absint-wassing en Peychaud's aan toe."),
    q("Waar verwijst het woord \"punch\" volgens de gangbaarste verklaring naar?", "Het Hindi-woord voor vijf, naar het aantal ingrediënten",
      ["Het Engelse werkwoord voor slaan, naar de sterke werking", "De Portugese naam voor de kom waarin het werd geserveerd", "Een Britse scheepsofficier die het recept vastlegde"],
      "Pānch betekent vijf: sterkedrank, suiker, citrus, water en specerijen."),
    q("Welke volgorde van gebeurtenissen klopt?", "Eerste definitie van \"cocktail\" → eerste cocktailboek → begin van de drooglegging",
      ["Eerste cocktailboek → eerste definitie van \"cocktail\" → begin van de drooglegging", "Eerste definitie van \"cocktail\" → begin van de drooglegging → eerste cocktailboek", "Begin van de drooglegging → eerste definitie van \"cocktail\" → eerste cocktailboek"],
      "1806 de definitie, 1862 Jerry Thomas' \"How to Mix Drinks\", 1920 de drooglegging."),
    q("Welke bar noemt de les als broedplaats van nieuwe klassiekers tijdens de drooglegging?", "El Floridita in Havana",
      ["Trader Vic's in Californië", "Harry's Bar in Venetië", "The Balance and Columbian Repository in New York"],
      "El Floridita en Harry's New York Bar in Parijs. Trader Vic hoort bij tiki (na de oorlog), Harry's Bar in Venetië is een andere bar, en The Balance is de krant uit 1806."),
    q("Waarom noemt de les de jaren '70-'80 een dieptepunt?", "Kant-en-klare mixen verdrongen vers werken en vakmanschap",
      ["Tiki verdrong in die jaren de klassiekers bijna volledig van de kaart", "Europa voerde een eigen drooglegging in die de bars leegtrok", "Bitters waren tijdelijk niet meer te krijgen door een importverbod"],
      "Het verlies van vers werken en vakmanschap leidde tot de craft-revival rond 2000."),
  ],
  uitrusting: [
    q("Je shaket een South Side met verse munt in een cobbler shaker. Welk probleem ligt het meest voor de hand?", "De ingebouwde zeef raakt verstopt door de munt",
      ["De cocktail wordt niet koud genoeg door het dikke metaal", "Er past te weinig ijs in om goed te verdunnen", "Het metaal reageert met het citroensap"],
      "De cobbler lekt sneller en zijn ingebouwde zeef verstopt bij munt of vruchtvlees."),
    q("Welke combinatie van zeef en gereedschap klopt?", "Hawthorne op de shaker, julep op het roerglas",
      ["Julep op de shaker, hawthorne op het roerglas", "Hawthorne op het roerglas, fijne zeef als vervanger van de hawthorne op de shaker", "Julep-zeef voor dubbel zeven, hawthorne voor het roerglas"],
      "Hawthorne (met veerrand) hoort op de shaker, de julep-zeef op het roerglas; de fijne zeef komt er bij dubbel zeven bovenop."),
    q("Waarom meet je met een jigger, ook als je al ervaren bent?", "Bij een cocktail op balans maakt een scheutje meer of minder al verschil",
      ["Vrijhandig schenken is achter een bar niet toegestaan", "Een jigger koelt de drank alvast een beetje voor", "Met een jigger mengt de alcohol beter met het sap"],
      "Een sour met een scheut te veel citroen is meteen te scherp; meten maakt een goede drank herhaalbaar."),
    q("Waarom kies je een muddler zonder lak?", "Lak kan door het stampen afbladderen en in je drank belanden",
      ["Gelakt hout is te glad om kruiden en fruit goed mee te kneuzen", "Onbehandeld hout neemt aroma's op, en dat maakt elke volgende drank rijker", "Een gelakte muddler is te zwaar en beschadigt daardoor de munt"],
      "Een muddler wordt hard gebruikt; een laklaag hoort niet in je glas terecht te komen."),
    q("Met welke vier stukken raadt de les aan te beginnen?", "Boston-shaker-set, jigger, bar spoon en hawthorne-zeef",
      ["Cobbler shaker, jigger, muddler en julep-zeef", "Boston-shaker-set, mixing glass, julep-zeef en channel knife", "Jigger, bar spoon, fijne zeef en muddler"],
      "Met deze vier maak je elk recept uit de cursus."),
  ],
  glaswerk: [
    q("Waarom kiezen veel moderne bartenders een Nick & Nora boven een coupe?", "Kleiner en meer gebogen, waardoor de cocktail langer koud blijft",
      ["Hij laat het aroma sneller vrijkomen dan een brede coupe doet", "Er past een groot ijsblok in, zodat de cocktail langer koud blijft", "Hij houdt koolzuur langer vast dan een flute, handig voor fizzes"],
      "Snelle aroma-afgifte is juist de kracht van de brede coupe; de Nick & Nora behoudt de koude langer."),
    q("Waarom beslaat een koperen Moscow Mule-beker zo zichtbaar?", "Koper geleidt kou uitzonderlijk goed naar de buitenkant",
      ["Koper reageert met het gemberbier en vormt zo condens aan de buitenkant", "De beker is dunner dan glas en voelt daardoor altijd natter aan", "Het ijs smelt sneller in koper en het smeltwater trekt naar buiten"],
      "Het is geleiding: de kou van de inhoud zit binnen seconden aan de buitenkant."),
    q("Waarom gaat een longdrink in een highball en niet in een coupe?", "Er is volume nodig voor genoeg ijs, omdat de drank in het glas zelf koud moet blijven",
      ["Een highball laat het aroma van de mixer sneller vrijkomen dan een coupe", "Een hoog glas houdt koolzuur altijd beter vast dan een flute of coupe", "Frisdrank mag volgens de bartraditie niet in een glas op een steel worden geserveerd"],
      "\"Up\" cocktails zijn al gekoeld vóór het inschenken; longdrinks moeten in het glas koud blijven."),
    q("Welke cocktail hoort volgens de logica van deze les in een rocks-glas?", "Een Old Fashioned over een groot ijsblok",
      ["Een Daiquiri, geschud en up geserveerd", "Een French 75, aangevuld met champagne", "Een Tom Collins, aangevuld met veel soda"],
      "Rocks: kort, stevige bodem, ruimte voor een groot ijsblok of om te muddelen."),
    q("Welke uitspraak over \"up\" geserveerde cocktails klopt?", "Ze zijn al gekoeld en verdund vóór het inschenken en gaan zonder ijs het glas in",
      ["Ze worden altijd over één groot ijsblok in een rocks-glas geserveerd", "Ze worden pas in het glas zelf gekoeld, met een paar ijsblokjes erin", "Ze bevatten per definitie koolzuur en worden daarom in een coupe geschonken"],
      "Daarom werkt een glas zonder ijs, zoals een coupe."),
  ],
  ijs: [
    q("Je shaker is maar half gevuld met ijs. Wat is het gevolg?", "Het ijs smelt snel weg: de drank wordt minder koud en eerder waterig",
      ["De drank wordt kouder, omdat het ijs meer ruimte heeft", "Er verandert niets, zolang je even lang schudt", "De drank wordt sterker, omdat er minder ijs smelt"],
      "Veel ijs koelt snel met gecontroleerde verdunning; weinig ijs smelt weg voordat de drank goed koud is."),
    q("Je hebt weinig ijs voor een feest. Waar bespaar je het slimst?", "Bewaar het voor shaken en serveren, en koel flessen en glazen op een andere manier",
      ["Shake met minder ijs, dat maakt geen verschil", "Gebruik het ijs uit de shaker opnieuw in het glas", "Laat bij longdrinks het ijs in het glas weg"],
      "IJs uit de shaker is al half gesmolten en koelt slecht; flessen in de koelkast of in een emmer met water en ijs sparen veel."),
    q("Waarom gebruik je voor een Julep juist crushed ijs?", "Het smelt snel en geeft een intense, snelle koeling en verdunning",
      ["Het smelt trager dan kubusijs, zodat de drank niet waterig wordt", "Het voorkomt dat de munt oxideert en bitter wordt in het glas", "Het houdt het koolzuur van de soda langer vast dan kubusijs"],
      "Crushed ijs = snelle verdunning, bewust gekozen voor Mojito, Julep en tiki."),
    q("Je gebruikt het ijs uit de shaker opnieuw om over te serveren. Wat is daar mis mee?", "Het is al deels gesmolten en verdunt je drank sneller",
      ["Niets, het is al koud en koelt de drank daardoor juist sneller", "Het maakt de cocktail troebel door resten eiwit en citrus", "Het is te koud geworden en bevriest daardoor de garnering"],
      "Gebruik voor elke stap vers ijs."),
    q("Waarom houden bartenders een vaste schud- of roertijd aan?", "Verdunning hoort bij het recept en tijd is de betrouwbaarste maat",
      ["Anders wordt de shaker te koud om nog goed vast te kunnen houden", "Langer schudden maakt een cocktail altijd sterker en minder zoet", "Anders smelt het ijs helemaal niet en blijft de cocktail te geconcentreerd"],
      "\"Tot het koud aanvoelt\" is geen maatstaf; een vaste tijd geeft een vaste verdunning."),
  ],
  gedistilleerd: [
    q("Je wilt een frisse, lichte sour. Welke basis past het best?", "Witte rum of gin",
      ["Een gerijpte cognac", "Een rokerige whisky", "Een donkere, zoete rum"],
      "Ongerijpte dranken laten citrus en fruit spreken."),
    q("Waarom smaakt bourbon ronder en zoeter dan wodka?", "Hij heeft op een houten vat gelegen; dat geeft vanille en karamel",
      ["Er is suiker aan toegevoegd", "Hij bevat meer alcohol", "Hij is van druiven gemaakt"],
      "Rijping op hout brengt die warme, zoete tonen."),
    q("Je recept vraagt rye, maar je hebt alleen bourbon. Wat gebeurt er als je wisselt?", "De cocktail wordt iets zoeter en ronder, maar blijft in balans",
      ["De cocktail werkt niet meer", "Hij wordt veel zuurder", "Je moet dan de vermout weglaten"],
      "Zelfde familie, net een ander karakter."),
    q("Waarom kiezen bartenders vaak voor wodka in een fruitige cocktail?", "Hij is neutraal en laat de andere smaken het werk doen",
      ["Hij geeft de meeste eigen smaak", "Hij hoeft niet gekoeld te worden", "Hij maakt fruit zoeter"],
      "Neutraal is hier een kracht, geen gebrek."),
    q("Is een dure single malt de beste keuze voor een Whiskey Sour?", "Meestal niet: citroen en suiker overstemmen de fijne smaken; een goede blend werkt net zo goed",
      ["Ja, een duurdere fles maakt elke cocktail beter", "Ja, single malt is zoeter", "Nee, whisky hoort nooit in een sour"],
      "Bewaar je beste fles om puur te drinken."),
  ],
  "likeuren-bitters": [
    q("Je Manhattan smaakt vlak en een beetje zurig, terwijl je het recept volgt. Wat is de waarschijnlijke oorzaak?", "De vermout staat te lang open",
      ["Te weinig bitters", "De whisky is te sterk", "Je hebt te kort geroerd"],
      "Vermout is wijn: open en buiten de koelkast wordt hij vlak en zurig."),
    q("Je vervangt de siroop in een sour door een sinaasappellikeur. Wat doe je met het zoet?", "Niets extra toevoegen: de likeur levert het zoet",
      ["Ook nog siroop toevoegen voor de balans", "De citroen weglaten", "Meer sterke drank toevoegen"],
      "Een likeur telt mee als het zoete deel."),
    q("Wat doen een paar dashes bitters in een Old Fashioned?", "Ze verbinden de smaken en geven diepte, zonder de drank bitter te maken",
      ["Ze maken hem duidelijk bitter", "Ze maken hem sterker", "Ze geven vooral kleur"],
      "Zoals zout in eten."),
    q("Waar bewaar je een geopende fles vermout?", "In de koelkast, en binnen een paar weken opmaken",
      ["In de kast, net als sterke drank", "In de vriezer", "Op kamertemperatuur, dan blijft de smaak het best"],
      "Koud en snel op, net als een open fles wijn."),
    q("Je cocktail is stroperig zoet geworden door een likeur. Wat is de beste oplossing?", "Een scheutje citroen erbij, of de volgende keer minder likeur",
      ["Nog wat siroop voor de balans", "Meer ijs in het glas", "Een andere garnering"],
      "Te zoet vraagt om zuur, of om minder zoet."),
  ],
  vers: [
    q("Je sour smaakt plat, terwijl de verhouding klopt. Wat is de waarschijnlijkste oorzaak?", "Sap uit een fles of van gisteren",
      ["Te veel ijs", "Te weinig sterke drank", "Een te koud glas"],
      "Vers sap geeft de frisheid; die verdwijnt snel."),
    q("Waarom gebruik je siroop in plaats van losse suiker?", "Losse suiker lost in een koude shaker slecht op",
      ["Siroop is minder zoet", "Siroop maakt de drank sterker", "Losse suiker kleurt de drank"],
      "Opgeloste suiker mengt meteen."),
    q("Je schuimkraag op een sour met eiwit is dun. Wat ging er waarschijnlijk mis?", "Je sloeg het schudden zonder ijs over",
      ["Je gebruikte te veel ijs", "Het eiwit was te vers", "Je hebt te lang met ijs geschud"],
      "Zonder ijs kan het eiwit eerst opschuimen."),
    q("Wat geeft eiwit aan een cocktail?", "Textuur: een zachte, romige schuimlaag",
      ["Een eiachtige smaak", "Meer zoetheid", "Meer alcohol"],
      "Smaak geeft het nauwelijks; het draait om het mondgevoel."),
    q("Je wilt sap klaarzetten voor een feest. Wanneer pers je het het best?", "Op de dag zelf, zo kort mogelijk van tevoren",
      ["Een week eerder, ingevroren", "De avond ervoor is net zo goed", "Pas als een gast bestelt, per glas"],
      "Vers is fris; per glas persen houd je op een feest niet vol."),
  ],
  garnering: [
    q("Waarom knijp je een citrusschil uit boven het glas?", "De oliën geven een frisse eerste geur, en die bepaalt hoe je de drank proeft",
      ["Om er sap bij te doen", "Om de drank kouder te maken", "Alleen voor het mooie plaatje"],
      "Je ruikt voordat je proeft."),
    q("Je Mojito smaakt bitter en grasachtig. Wat deed je waarschijnlijk fout?", "De munt te hard gekneusd",
      ["Te weinig munt gebruikt", "De munt alleen geklapt", "Te veel ijs gebruikt"],
      "Kapotte blaadjes worden bitter."),
    q("Waarom snijd je de schil zonder het witte deel?", "Het wit is bitter",
      ["Het wit maakt de drank troebel", "In het wit zit de meeste geur", "Het past anders niet in het glas"],
      "Alleen de gekleurde schil bevat de geurige oliën."),
    q("Je wilt een Martini hartiger maken. Welke garnering kies je?", "Een olijf",
      ["Een citroentwist", "Een kers", "Een takje munt"],
      "Een olijf geeft een zoutig accent."),
    q("Een tiki-cocktail met parasolletje en ananas: wat doet die garnering?", "Vooral sfeer en beleving; prima, zolang je het bewust kiest",
      ["Hij verandert de smaak flink", "Hij houdt de drank koud", "Hij is verplicht volgens het recept"],
      "Niet elke garnering hoeft smaak te geven."),
  ],
  basistechnieken: [
    q("Je maakt een Daiquiri (rum, limoen, siroop). Shaken of roeren?", "Shaken: er zit sap in",
      ["Roeren: het is een klassieker", "Bouwen in het glas", "Dat maakt niet uit"],
      "Sap mengt en koelt het best door te shaken."),
    q("Waarom roer je een Martini in plaats van hem te shaken?", "Alleen heldere drank: roeren houdt hem helder en zijdezacht",
      ["Shaken maakt hem te koud", "Roeren gaat sneller", "Door roeren wordt hij sterker"],
      "Shaken klopt lucht in de drank en maakt hem troebel."),
    q("Waarom shake je een Gin Tonic niet?", "Dan verdwijnt het koolzuur",
      ["Gin wordt bitter van shaken", "Tonic wordt troebel van ijs", "Het glas is te klein"],
      "Prik bouw je in het glas."),
    q("Je shaket lang en voorzichtig in plaats van kort en hard. Wat merk je?", "Een slappere, minder frisse drank",
      ["Een sterkere drank", "Meer schuim", "Geen verschil"],
      "Kort en hard koelt en mengt goed, zonder dat het een waterig drankje wordt."),
    q("Hoe begin je aan een Mojito met verse munt?", "Munt licht aandrukken met siroop en limoen in het glas",
      ["De munt fijnhakken", "De munt met ijs hard shaken en zeven", "De munt koken in de siroop"],
      "Licht aandrukken geeft geur zonder bitterheid."),
  ],
  "verdunning-temperatuur": [
    q("Je Manhattan brandt en smaakt scherp. Wat ontbreekt waarschijnlijk?", "Verdunning: langer roeren met ijs",
      ["Meer vermout", "Een andere whisky", "Een garnering"],
      "Smeltwater maakt de alcohol zachter."),
    q("Waarom is 'de shaker voelt koud' geen goede maatstaf?", "Het metaal is snel koud, de drank nog niet",
      ["Een shaker voelt nooit koud", "Koude handen misleiden je", "Hoe kouder de shaker, hoe sterker de drank"],
      "Tel liever de seconden."),
    q("Je gebruikt halfgesmolten ijs uit de vriezerbak. Wat gebeurt er?", "Meer water en minder koeling: een waterige drank",
      ["Een koudere drank", "Een sterkere drank", "Geen verschil"],
      "Nat ijs smelt snel en koelt slecht."),
    q("Wat doet smeltwater met de smaak?", "Het maakt de alcohol zachter en laat de smaken beter naar voren komen",
      ["Het maakt alles alleen maar slapper", "Het voegt zoet toe", "Het maakt de drank troebel"],
      "Daarom hoort het bij het recept."),
    q("Je schenkt een geschudde cocktail zonder ijs in een warm glas. Wat merk je?", "Hij is snel lauw",
      ["Hij wordt sterker", "Hij wordt zoeter", "Er verandert niets"],
      "Een koud glas houdt de kou vast."),
  ],
  "sour-formule": [
    q("Wat hebben een Margarita en een Daiquiri gemeen?", "Hetzelfde skelet: sterke drank, zuur en zoet",
      ["Ze zijn allebei op basis van rum", "Ze worden allebei geroerd", "Er gaat allebei eiwit in"],
      "Andere basis, zelfde opbouw."),
    q("Waarom heeft een Margarita geen suikersiroop nodig?", "De triple sec levert het zoete deel",
      ["Tequila is van zichzelf al zoet", "Limoen is minder zuur dan citroen", "Het zout maakt hem zoet"],
      "Een likeur telt mee als het zoet."),
    q("Je wilt een sour lang en licht maken voor een zomerse middag. Wat doe je?", "Over ijs serveren en aanvullen met soda",
      ["Meer siroop toevoegen", "Langer shaken", "De citroen weglaten"],
      "Zo wordt een sour een Collins."),
    q("Je maakt een Whiskey Sour met eiwit. Wat verandert er?", "Hij wordt zachter en romiger, met een schuimkraag",
      ["Hij wordt zuurder", "Hij wordt sterker", "Hij wordt helder"],
      "Eiwit gaat om textuur."),
    q("Je wisselt de citroen in een sour voor limoen. Waar let je op?", "Proef en stuur bij: limoen smaakt anders en kan scherper zijn",
      ["Er verandert niets", "Limoen is zoeter, dus doe er meer citroen bij", "Limoen kun je niet shaken"],
      "Proeven gaat boven het recept."),
  ],
  finesse: [
    q("Wanneer zeef je dubbel?", "Bij een geschudde cocktail die zonder ijs wordt geserveerd",
      ["Bij elke longdrink", "Alleen bij cocktails met munt", "Bij een geroerde Martini"],
      "Zo blijven er geen ijssplinters drijven."),
    q("Waarom blijft een drijflaag drijven?", "Het lichtere ligt boven op het zwaardere, zoetere",
      ["Door het ijs", "Omdat het kouder is", "De lepel houdt de lagen gescheiden, ook als je snel giet"],
      "Langzaam gieten laat dat verschil zijn werk doen."),
    q("Je laagjesshooter mengt meteen. Wat ging er mis?", "Te snel gegoten, of in de verkeerde volgorde",
      ["De likeuren waren te koud", "Het glas was te smal", "Er zaten te veel likeuren in"],
      "Zwaarste onderop, en langzaam over een lepel."),
    q("Wat doet een uitgeknepen schil vlak voor het serveren?", "Hij geeft een frisse eerste geur die de beleving verandert",
      ["De drank wordt zuurder", "Hij blijft langer koud", "Het is alleen voor het plaatje"],
      "De eerste indruk komt via je neus."),
    q("Er drijven kleine ijssplinters op je cocktail. Wat helpt?", "Dubbel zeven door een fijne zeef",
      ["Langer shaken", "Minder ijs gebruiken", "Er een garnering op leggen"],
      "Een fijne zeef vangt wat de gewone doorlaat."),
  ],
  // Deel IV: praktijkvragen. Geen rekenwerk of weetjes, wel: wat proef je,
  // waarom, en wat doe je eraan.
  families: [
    q("Je Whiskey Sour smaakt plakkerig en de whiskey valt weg. Wat doe je?", "Een scheutje citroen erbij, of de volgende keer minder siroop",
      ["Meer ijs in de shaker, zodat hij meer verdunt", "Extra whiskey erbij schenken", "Langer shaken"],
      "Plakkerig betekent te zoet. Met meer zuur trek je hem terug in balans, zonder dat hij slapper wordt."),
    q("Je Margarita trekt je wangen samen en smaakt dun. Wat is er aan de hand?", "Te zuur: er mag iets meer zoet bij",
      ["Te zoet: er mag meer limoen bij", "Te sterk: er moet meer ijs bij", "Te koud: laat hem even staan"],
      "Prikken en dun smaken is zuur dat geen tegenwicht krijgt."),
    q("Waarom proef je met een rietje voordat je inschenkt?", "Citrus verschilt per vrucht, en nu kun je nog bijsturen",
      ["Zo controleer je of hij koud genoeg is", "Zo proef je of de alcohol goed is opgelost", "Zo blijft er minder in de shaker achter"],
      "Het recept is een startpunt; jouw citroen bepaalt de rest."),
    q("Je cocktail is net te zuur. Hoe stuur je bij?", "Een klein beetje siroop erbij, ongeveer 5 ml, en opnieuw proeven",
      ["Meteen een flinke scheut siroop, dan merk je het tenminste", "De hoeveelheid siroop verdubbelen", "Opnieuw beginnen met minder citroen en meer drank"],
      "Kleine stappen voorkomen dat je doorschiet naar te zoet."),
    q("Wat doet zoet in een cocktail, behalve zoet maken?", "Het maakt hem ronder en dempt de scherpte van de alcohol",
      ["Het maakt hem frisser en lichter", "Het zorgt dat het ijs langzamer smelt", "Het laat de citrus scherper naar voren komen"],
      "Daarom voelt een sour zonder siroop zo hard aan."),
  ],
  smaakcombinatie: [
    q("Je drankje is te zoet, maar met meer citroen wordt hij te zuur. Wat probeer je?", "Een of twee dashes bitters",
      ["Meer siroop om het zuur te maskeren", "Meer ijs, zodat het zoet verdwijnt", "Een scheut sinaasappelsap"],
      "Bitter remt zoet af zonder dat het drankje zuurder wordt."),
    q("Wat doet een paar korrels zout in een cocktail?", "Het verzacht bitter en laat fruit en citrus voller proeven",
      ["Het maakt de cocktail merkbaar zout, zoals een zoutrand", "Het haalt de alcoholsmaak weg", "Het maakt de cocktail zoeter zonder suiker"],
      "In kleine hoeveelheid proef je zout niet als zout, maar als meer smaak."),
    q("Je Old Fashioned brandt in je keel. Wat is de beste eerste stap?", "Langer roeren met ijs, zodat er meer water bij komt",
      ["Meer suikersiroop toevoegen", "Er een scheut cola bij doen", "Een andere garnering kiezen"],
      "Water en kou temperen de alcohol; suiker maakt hem alleen zwaarder."),
    q("Waarom smaakt een Negroni die niet geroerd is zo hard?", "Zonder water en kou komen alcohol en bitter vol naar voren",
      ["De vermout is dan nog niet goed gemengd", "Campari wordt pas zoet als hij koud is", "De sinaasappel heeft zijn smaak nog niet afgegeven"],
      "Roeren met ijs is geen detail: het maakt de drank zachter."),
    q("Een gast vindt je cocktail \"plat\". Wat helpt meestal het meest?", "Een tegenwicht, zoals een bittere noot of een paar korrels zout",
      ["Meer van hetzelfde zoete ingrediënt", "Een sterkere drank als basis", "Hem langer laten staan"],
      "Plat betekent vaak: er is niets wat tegen de rest ingaat."),
  ],
  ontwerpen: [
    q("Je wilt een eigen versie van een Daiquiri maken. Wat is de slimste start?", "Eén onderdeel wisselen, bijvoorbeeld de rum voor een andere drank",
      ["Alle drie de ingrediënten vervangen", "Er twee likeuren bij doen voor meer smaak", "De verhoudingen omdraaien"],
      "Het skelet werkt al; met één wissel blijft de balans grotendeels kloppen."),
    q("Je vervangt de suikersiroop door een sinaasappellikeur. Waar let je op?", "Likeur is minder zoet dan siroop, dus je hebt er meer van nodig",
      ["Likeur is zoeter, dus neem de helft", "Er verandert niets, zoet is zoet", "Je moet dan ook de citroen weglaten"],
      "Een likeur is deels alcohol en deels suiker: minder zoet per scheut."),
    q("Je wisselt citroen voor grapefruit. Wat gebeurt er waarschijnlijk?", "Het wordt minder zuur en iets bitterder, dus misschien minder siroop",
      ["Het wordt zuurder, dus je hebt meer siroop nodig", "Er verandert niets aan de balans", "Het wordt zoeter, dus er moeten bitters bij"],
      "Grapefruit is milder dan citroen en heeft een eigen bitter."),
    q("Je twist smaakt goed, maar je hebt drie dingen tegelijk veranderd. Wat is het probleem?", "Je weet niet wat het verschil maakte, dus je kunt het lastig herhalen of verbeteren",
      ["Er is geen probleem: smaakt het goed, dan is het goed", "Drie wijzigingen maken een drankje altijd onstabiel", "Hij telt dan niet meer als twist op een klassieker"],
      "Eén ding tegelijk is langzamer, maar je leert er van elke versie iets."),
    q("Je werkt met rokerige mezcal. Waarmee maak je het spannend in plaats van zwaar?", "Iets fris en fruitigs, zoals ananas of grapefruit",
      ["Nog iets rokerigs, zoals een Islay-whisky", "Een zware koffielikeur", "Zo min mogelijk andere smaken"],
      "Een tegenhanger houdt het levendig; meer van hetzelfde maakt het log."),
  ],
  menu: [
    q("Je maakt een menu voor een gemengd gezelschap. Wat kies je?", "Paloma, Negroni, Espresso Martini en een alcoholvrije optie",
      ["Negroni, Manhattan, Old Fashioned en Boulevardier", "Daiquiri, Margarita, Whiskey Sour en Pisco Sour", "De vier cocktails die jij zelf het lekkerst vindt"],
      "Fris, sterk, zacht en zonder alcohol: iedereen vindt iets."),
    q("Waarom is drie tot vijf cocktails meestal beter dan tien?", "Minder flessen en werk, en gasten kiezen makkelijker",
      ["Met meer cocktails drinken gasten te veel", "Met meer cocktails raakt je ijs sneller op", "Tien cocktails passen niet op een menukaart"],
      "Een kleine kaart die goed is, werkt beter dan een grote die je niet bijhoudt."),
    q("Welke cocktail kun je uren vooraf in een fles klaarzetten?", "Een Negroni: alleen drank, geen sap of ei",
      ["Een Whiskey Sour met eiwit", "Een Mojito met verse munt", "Een Daiquiri met vers limoensap"],
      "Sap, ei en verse kruiden verliezen snel hun frisheid."),
    q("Twee cocktails op je menu vragen elk een fles die je verder nergens voor gebruikt. Wat doe je?", "Eén van de twee vervangen door iets met wat je al hebt",
      ["Beide flessen kopen: variatie gaat altijd voor", "Ze houden en de porties kleiner maken", "Ze maken zonder die fles en de rest verdubbelen"],
      "Gedeelde ingrediënten houden het betaalbaar zonder dat het menu saai wordt."),
    q("Waarom hoort er altijd een volwaardige alcoholvrije optie op je menu?", "Er is bijna altijd iemand die niet drinkt, en die verdient meer dan frisdrank",
      ["Zo spaar je je dure flessen", "Het is verplicht op een feest", "Dan blijf je zelf ook nuchter"],
      "Een gast zonder alcohol hoort net zo goed iets bijzonders in het glas te krijgen."),
  ],
  "mise-en-place": [
    q("Welke opstelling volgt de volgorde van bereiding?", "Sterkedrank vooraan bij de shaker, dan likeuren, bitters en vers",
      ["Vers ingrediënten het dichtst bij de shaker, sterkedrank achteraan", "Bitters vooraan, omdat die er als eerste in de shaker gaan", "Alles op alfabet, zodat je elke fles snel terugvindt"],
      "De volgorde van bereiding voorkomt heen-en-weer lopen."),
    q("Wat kun je uren tot een dag van tevoren klaarmaken?", "Siropen en de meeste garneringen",
      ["Vers citrussap en muntblaadjes", "Opgeklopt eiwit voor de sours van die avond", "Geschudde sours zonder ijs, gekoeld bewaard"],
      "Citrussap en munt verliezen binnen uren aan kwaliteit."),
    q("Waar bewaar je gesneden garnering tijdens de avond?", "Op ijs",
      ["Op kamertemperatuur, zodat het aroma sterker is", "In de vriezer", "In een glas water op het aanrecht"],
      "Koel en binnen handbereik."),
    q("Wat hoort volgens de pro-tip op je feest-checklist?", "IJs, glazen, te snijden garnering en wat je kunt batchen",
      ["De afspeellijst, de verlichting en de zitplaatsen", "De prijs per fles en het totale budget", "Het alcoholpercentage per cocktail op het menu"],
      "Tien minuten plannen scheelt uren improviseren."),
    q("Welk ingrediënt verliest volgens de les binnen uren aan kwaliteit?", "Munt",
      ["Suikersiroop", "Kaneelstokjes", "Angostura"],
      "Net als citrussap: zo dicht mogelijk bij het serveren."),
  ],
  "batchen-groepen": [
    q("Je maakt een Negroni vooraf in een fles. Waarom doe je er water bij?", "Zonder roeren met ijs mist de batch de verdunning die normaal van het ijs komt",
      ["Water maakt de batch langer houdbaar", "Water voorkomt dat de Campari uitzakt", "Zo kun je met minder flessen meer glazen schenken"],
      "Smeltwater hoort bij de smaak; in een batch voeg je het vooraf toe, zodat de drank meteen klopt."),
    q("Waarom werkt een gebatchte Negroni beter dan een gebatchte Whiskey Sour met eiwit?", "Geen vers sap, eiwit of zuivel, dus de kwaliteit blijft gelijk",
      ["Een Negroni is sterker en daardoor vanzelf langer houdbaar", "Een sour kun je niet opschalen zonder de verhouding te verliezen", "Eiwit wordt in de koelkast binnen een paar uur onveilig"],
      "Net-geshakete textuur gaat verloren als je te vroeg maakt."),
    q("Halverwege het feest loopt je bar vast. Wat helpt het meest?", "Overschakelen op een cocktail die je vooraf hebt klaargezet",
      ["Sneller shaken en minder proeven", "Meer verschillende cocktails aanbieden", "Gasten vragen te wachten tot iedereen een drankje heeft"],
      "Een batch schenk je in seconden; zo houd je tijd over voor de rest."),
    q("Wat is bij grote groepen volgens de les vaak de eerste bottleneck?", "IJs",
      ["Sterkedrank", "Glazen", "Citrus"],
      "Reken op 150 g per drankje."),
    q("Wanneer maak je een batch idealiter klaar?", "Dezelfde dag",
      ["Een week van tevoren", "Een maand van tevoren, gekoeld", "Pas als de gasten er zijn, per glas"],
      "Uren wachten met de verdunning erin gaat ten koste van de kwaliteit."),
  ],
  gastvrijheid: [
    q("Een gast weet niet wat hij wil. Wat is de beste eerste stap?", "Vragen: bitter of zoet, sterk of licht?",
      ["Je eigen favoriet serveren", "De sterkste cocktail van het menu aanbieden", "Een shot geven om het ijs te breken"],
      "Een paar seconden vragen voorkomt een misser en toont aandacht."),
    q("Een gast drinkt geen alcohol. Wat past bij de les?", "Een even doordachte, volwaardige alcoholvrije cocktail",
      ["Fris uit een pak, zodat de gast snel iets heeft", "Water, dat is het meest neutraal en past bij alles", "Een cocktail met de helft minder alcohol dan normaal"],
      "Niet-drinkers verdienen dezelfde zorg als de rest."),
    q("Waarom vertel je een kort verhaal bij een cocktail?", "Het verandert hoe gasten dezelfde drank waarderen",
      ["Om tijd te winnen terwijl je de cocktail schudt", "Omdat een verhaal de smaak van de drank echt verandert", "Het hoort verplicht bij elke klassieke cocktail"],
      "Kennis delen is zelf onderdeel van de gastvrijheid."),
    q("Een gastheer staat de hele avond achter de bar. Welke oplossing noemt de les?", "Meer vooraf voorbereiden en batchen",
      ["Minder gasten uitnodigen", "Alleen bier schenken", "Gasten zelf laten mixen zonder uitleg"],
      "Voorbereiding is ook gastvrijheid naar jezelf."),
    q("Wat betekent \"tempo lezen\"?", "Aanvoelen wanneer een gezelschap toe is aan de volgende ronde",
      ["Zo snel mogelijk nieuwe drankjes blijven serveren aan iedereen", "Elke twintig minuten vast een nieuwe ronde maken", "Wachten tot de gasten er zelf om komen vragen"],
      "Niet te snel en niet te traag: het gezelschap bepaalt het ritme."),
  ],
  signature: [
    q("Waar begin je bij een signature cocktail?", "Bij een idee, herinnering of gevoel",
      ["Bij de duurste fles in huis", "Bij een bestaand recept dat je precies kopieert", "Bij de garnering"],
      "Het verhaal stuurt de ingrediëntkeuze."),
    q("Je eerste versie van een eigen cocktail is net niet goed. Wat doe je?", "Eén ding aanpassen, opnieuw proeven en opschrijven wat je deed",
      ["Hem weggooien en iets heel anders bedenken", "Meer ingrediënten toevoegen voor complexiteit", "Hem toch serveren; gasten proeven het verschil niet"],
      "Bijna niemand heeft het in één keer goed; kleine stappen brengen je er."),
    q("Hoe begin je het makkelijkst aan een eigen cocktail?", "Met een klassieker die werkt, waarin je één onderdeel wisselt",
      ["Met een leeg vel en vijf ingrediënten die je lekker vindt", "Met de duurste fles die je in huis hebt", "Met een naam, en daarna de ingrediënten erbij zoeken"],
      "Les 15: een werkend skelet, één wissel, proeven en opschrijven."),
    q("Wat doe je met elke testversie?", "Noteren, en per keer één variabele aanpassen",
      ["Weggooien als hij niet meteen perfect is", "Meerdere dingen tegelijk aanpassen om tijd te sparen", "Alleen de laatste versie onthouden"],
      "Zo weet je welke aanpassing het verschil maakte."),
    q("Waaruit ontstaan de beste signature cocktails volgens de laatste pro-tip?", "Uit een oprechte poging een probleem op te lossen of een gevoel op te roepen",
      ["Uit een poging zo origineel en verrassend mogelijk te zijn", "Uit het combineren van zo veel mogelijk zeldzame ingrediënten", "Uit het nauwkeurig volgen van de nieuwste bartrends"],
      "Origineel-zijn om het origineel-zijn werkt zelden."),
  ],
  infusies: [
    q("Je rozemarijngin smaakt na twee dagen bitter. Wat ging er mis?", "Verse kruiden trekken in uren; dit was te lang",
      ["Er zat te weinig rozemarijn in", "Gin is daar niet geschikt voor", "De fles stond te koud"],
      "Fijne kruiden zijn snel klaar en worden daarna bitter."),
    q("Hoe weet je wanneer een infusie klaar is?", "Door regelmatig te proeven, en te zeven als het lekker is",
      ["Na precies een week", "Als de kleur verandert", "Als het bezinksel zakt"],
      "Elke infusie is anders; je smaak beslist."),
    q("Je infuseert met vers fruit. Waar bewaar je de fles?", "In de koelkast, en snel opmaken",
      ["In de kast, alcohol houdt alles goed", "In de zon, dan trekt het sneller", "In de vriezer, zonder te zeven"],
      "Vers en waterig materiaal bederft sneller."),
    q("Waarom laat je het witte deel van de citrusschil weg?", "Het maakt de infusie bitter",
      ["Het kleurt de drank wit", "Het trekt te snel", "Het maakt de drank troebel"],
      "Alleen de gekleurde schil geeft de geurige oliën."),
    q("Waarom begin je met een klein flesje?", "Elke infusie is anders; zo verpest je geen hele fles",
      ["Een klein flesje trekt sneller", "Grote flessen werken niet", "Kleine flessen blijven langer goed"],
      "Eerst proberen, dan opschalen."),
  ],
  "fat-washing": [
    q("Waarom zet je de fles na het mengen in de vriezer?", "Het vet wordt hard en is dan makkelijk te scheiden",
      ["Dan trekt de smaak sneller", "Dan wordt de drank sterker", "Om bacteriën te doden"],
      "Vet stolt, alcohol niet."),
    q("Je drank heeft vette druppels bovenop. Wat ging er mis?", "Te vroeg of niet fijn genoeg gezeefd",
      ["Er zat te weinig vet in", "De drank was te sterk", "Hij stond te lang in de vriezer"],
      "Laat het vet echt hard worden en zeef door een koffiefilter."),
    q("Welke combinatie past bij een hartige Martini?", "Olijfolie met gin",
      ["Spek met gin", "Bruine boter met wodka", "Kokosvet met vermout"],
      "Olijfolie geeft een frisse, hartige toon."),
    q("Hoe bewaar je een fat-washed drank?", "Gekoeld, en binnen een paar weken opmaken",
      ["Onbeperkt in de kast", "In de zon", "Altijd ingevroren"],
      "Er blijven sporen vet in die kunnen bederven."),
    q("Wat geeft fat-washing aan een drank, naast smaak?", "Een zachter, voller mondgevoel",
      ["Meer alcohol", "Een heldere kleur", "Meer zuur"],
      "Daarom werkt het zo goed in sterke, geroerde cocktails."),
  ],
  clarificatie: [
    q("Waarom wordt een cocktail helder na melk-clarificatie?", "Het zuur laat de melk schiften, en die vlokken vangen de troebelheid",
      ["De melk verdunt de kleur", "De kou maakt hem helder", "Het filter haalt de alcohol eruit"],
      "De vlokken werken als een filter."),
    q("Je gefilterde drank is nog troebel. Wat doe je?", "Het eerste deel nog een keer door hetzelfde filter gieten",
      ["Er meer melk bij doen", "Hard roeren", "Het opwarmen"],
      "Het filter wordt beter naarmate de vlokken erin liggen."),
    q("Wat merk je aan de smaak na clarificatie?", "Zachter en ronder, iets minder scherp",
      ["Je proeft duidelijk melk", "Veel zuurder", "Veel sterker"],
      "De scherpe randjes zijn eraf."),
    q("Waarom heb je een zure cocktail nodig voor melk-clarificatie?", "Zonder zuur schift de melk niet",
      ["Zuur maakt hem zoeter", "Zuur haalt de alcohol eruit", "Dat hoeft niet"],
      "Het zuur is wat het proces op gang brengt."),
    q("Waar bewaar je een geclarificeerde cocktail?", "In de koelkast, en binnen een paar dagen opmaken",
      ["Onbeperkt in de kast", "In de zon", "Bij de sterke drank"],
      "Helder betekent niet houdbaar."),
  ],
  "carbonatie-rook": [
    q("Je bruisende cocktail verliest snel zijn prik. Wat helpt?", "Alles goed koud maken: drank, glas en soda",
      ["Meer suiker", "Langer schudden na het toevoegen", "Soda op kamertemperatuur gebruiken"],
      "Kou houdt koolzuur vast."),
    q("Je gerookte cocktail smaakt naar as. Wat ging er mis?", "Te lang gerookt; een paar seconden is genoeg",
      ["Te weinig rook", "Het verkeerde glas", "Te weinig ijs"],
      "Rook is een geur; te veel wordt smaak, en die is niet lekker."),
    q("Waarom shake je soda of mousserende wijn niet mee?", "Dan verdwijnt de prik",
      ["Dan wordt het bitter", "Dan bevriest het", "Dat maakt geen verschil"],
      "Prik voeg je op het eind toe."),
    q("Wat doet rook vooral aan een cocktail?", "Hij voegt geur toe",
      ["Hij maakt de drank sterker", "Hij maakt de drank kouder", "Hij maakt de drank zoeter"],
      "Je ruikt het bij elke slok."),
    q("Je cocktail is niet in balans. Lost een rookwolk dat op?", "Nee: eerst het recept in balans brengen",
      ["Ja, rook verbergt alles", "Ja, als je maar lang genoeg rookt", "Alleen bij whiskycocktails"],
      "Trucs maken een goede drank beter, geen slechte goed."),
  ],
};

// Eindtoets: 5 vragen per deel, geïntegreerd en met rekenwerk; niet
// dezelfde vragen als in de lessen.
export const FINAL_EXAM_QUESTIONS = [
  // Deel I
  q("Wat hebben een Manhattan en een Sazerac met de definitie uit 1806 te maken?", "Beide zijn varianten op sterkedrank, suiker, water en bitters",
    ["Beide zijn eigenlijk punches waarvan de citrus is weggelaten", "Beide zijn ontstaan tijdens de drooglegging in Parijs en Havana", "Beide stammen uit de tiki-traditie van Donn Beach"],
    "Wie de vierdelige formule kent, herkent de familie."),
  q("Waarom koel je een coupe voordat je een geschudde cocktail inschenkt?", "Er zit geen ijs in het glas, dus anders warmt de drank snel op",
    ["Een koud glas maakt de cocktail zoeter", "Zo blijft het schuim van eiwit beter staan", "Het voorkomt dat het glas breekt"],
    "Een cocktail zonder ijs heeft niets meer om hem koud te houden; het glas helpt een handje."),
  q("Welke combinatie is functioneel het minst logisch?", "Een Mojito met crushed ijs in een coupe",
    ["Een Daiquiri up in een coupe", "Een Old Fashioned op een groot blok in een rocks-glas", "Een champagnecocktail in een flute"],
    "Een coupe is voor cocktails zonder ijs."),
  q("Je schenkt de siroop in een sour op gevoel en het wordt een flinke scheut te veel. Wat proef je?", "Een te zoete, platte sour waarin de sterke drank wegvalt",
    ["Geen verschil, een scheutje maakt niets uit", "Een zuurdere sour", "Een sterkere sour"],
    "Bij een cocktail op balans maakt een scheut te veel al duidelijk verschil."),
  q("Een Clover Club met eiwit wordt up geserveerd. Welke zeven gebruik je?", "Hawthorne-zeef plus fijne zeef (dubbel zeven)",
    ["Alleen de julep-zeef, want die is fijner", "Geen zeef: het schuim moet er helemaal in", "Alleen de fijne zeef, zonder hawthorne"],
    "Geschud en up: dubbel zeven."),
  // Deel II
  q("Je wilt een warme, ronde Old Fashioned. Welke basis past het best?", "Een gerijpte drank, zoals bourbon",
    ["Wodka", "Witte rum", "Tequila blanco"],
    "Rijping op hout geeft de vanille en karamel die bij een Old Fashioned horen."),
  q("Wat telt mee als het zoete deel van je balans?", "Siroop én zoete likeuren, zoals triple sec",
    ["Alleen suikersiroop", "Alleen vruchtensap", "Bitters"],
    "Vergeet je een likeur mee te tellen, dan wordt de cocktail te zoet."),
  q("Welke geopende fles verliest het snelst aan kwaliteit?", "Droge vermout",
    ["Campari", "Angostura bitters", "London Dry gin"],
    "Vermout is wijn en oxideert; de rest is sterk genoeg om stabiel te blijven."),
  q("Welke garnering heeft een smaakfunctie en niet alleen een aromafunctie?", "Een olijf in een Dirty Martini",
    ["Een uitgeknepen citroentwist", "Een parasolletje met kersen", "Een ananasblad op de rand"],
    "De twist werkt via de neus; de olijf voegt een zoute noot toe aan de smaak."),
  q("Waarom smaakt een sour met limoensap uit een fles platter, ook als de verhouding klopt?", "De vluchtige aromatische oliën ontbreken",
    ["Flessensap bevat nauwelijks zuur", "Flessensap is geconcentreerd en dus te sterk", "Flessensap laat het ijs sneller smelten"],
    "De verhouding klopt, de aroma's niet."),
  // Deel III
  q("Recept: 50 ml gin, 25 ml citroen, 20 ml siroop en een eiwit. Wat is de juiste bereiding?", "Dry shake, dan met ijs schudden, dan dubbel zeven in een coupe",
    ["Roeren met ijs in een mengglas en zeven in een coupe", "Bouwen op ijs in een highball en kort doorroeren", "Alleen 30 seconden met ijs schudden en ongezeefd serveren"],
    "Eiwit vraagt om een dry shake; geschud en up vraagt om dubbel zeven."),
  q("Waarom roer je een Manhattan in plaats van hem te shaken?", "Alleen sterke drank en vermout: roeren geeft een heldere, zijdezachte drank",
    ["Shaken is alleen voor cocktails met ijs in het glas", "Roeren koelt sneller dan shaken", "Vermout wordt bitter als je hem shaket"],
    "Shaken lucht op en maakt troebel; dat past bij sap en ei, niet bij een heldere, sterke cocktail."),
  q("Je sour proeft dun en scherp, terwijl je precies volgens recept werkte. Wat is de waarschijnlijkste oorzaak?", "Je citroen of limoen is zuurder dan gemiddeld: proeven en bijsturen",
    ["Je hebt te lang geshaket", "De sterke drank is te oud", "Je glas was niet koud genoeg"],
    "Citrus verschilt per vrucht; het recept is een startpunt."),
  q("Je maakt een Tom Collins. Hoe gaat de soda erin?", "Op het eind in het glas, en één keer kort roeren",
    ["Meeshaken met de rest", "Vooraf mengen met de siroop", "Eerst in het glas, en de rest er hard op shaken"],
    "Prik voeg je op het eind toe; shaken laat het koolzuur ontsnappen."),
  q("Na 15 seconden hard schudden schud je nog 30 seconden door. Wat is het resultaat?", "Vooral extra water, en nauwelijks kouder",
    ["Veel kouder, en daardoor ook sterker", "Meer schuim bij dezelfde verdunning", "Warmer door de wrijving van het ijs"],
    "De koelcapaciteit is dan al grotendeels op."),
  // Deel IV
  q("Een sour smaakt dun en trekt je wangen samen. Wat doe je?", "Een klein beetje siroop erbij en opnieuw proeven",
    ["Meer citroen erbij, voor meer frisheid", "Langer shaken voor meer verdunning", "Een sterkere drank als basis kiezen"],
    "Te zuur vraagt om iets meer zoet, in kleine stappen."),
  q("Een gast vindt je nieuwe cocktail \"plat\". Welke aanpassing past het best bij de lessen?", "Een tegenwicht toevoegen, bijvoorbeeld een bittere noot of een paar korrels zout",
    ["Meer van hetzelfde zoete ingrediënt toevoegen", "Vijf nieuwe ingrediënten tegelijk proberen", "De cocktail langer laten staan voor meer smaak"],
    "Plat betekent vaak: geen tegenwicht."),
  q("Je drankje is te bitter. Wat helpt zonder dat het zwaar en zoet wordt?", "Een paar korrels zout",
    ["Een flinke scheut suikersiroop", "Meer van de bittere likeur", "Een andere garnering"],
    "Zout verzacht bitter; suiker maakt het snel plakkerig."),
  q("Je maakt een twist op een Margarita. Wat is de beste aanpak?", "Eén onderdeel wisselen, proeven en opschrijven wat je deed",
    ["Alles tegelijk vervangen, dan is het echt nieuw", "Twee extra likeuren toevoegen voor diepte", "De verhoudingen omdraaien: meer limoen dan tequila"],
    "Eén wissel tegelijk, zodat je weet wat het verschil maakt."),
  q("Een menu van vijf cocktails voor twintig gasten. Wat past bij de lessen?", "Fris, sterk en zacht, één alcoholvrije optie en minstens één cocktail die je vooraf klaarzet",
    ["Vijf sours, omdat die snel en voor iedereen lekker zijn", "Vijf sterke cocktails, omdat die allemaal vooraf kunnen", "Alleen wat jij zelf het lekkerst vindt, met één alcoholvrije"],
    "Iets voor iedereen, en werkbaar voor jou."),
  // Deel V
  q("Wat kun je NIET goed de dag van tevoren doen?", "Limoensap persen",
    ["Suikersiroop maken", "Glazen per type klaarzetten", "Kaneelstokjes klaarleggen"],
    "Citrussap verliest binnen 24 uur merkbaar aan frisheid."),
  q("Wat is de belangrijkste reden om voor een groot feest vooraf te mixen?", "Je bent sneller en elke drank smaakt hetzelfde",
    ["Vooraf gemixte cocktails zijn sterker", "Je hebt dan geen ijs meer nodig", "Zo hoef je niet meer te proeven"],
    "Gelijke kwaliteit en tijd over voor je gasten."),
  q("Welke taakverdeling helpt het meest bij een groot feest?", "Eén persoon schenkt, een ander garneert en serveert",
    ["Iedereen maakt zijn eigen cocktail met jouw uitleg", "Eén persoon doet alles, dat voorkomt verwarring", "Gasten wachten tot een hele ronde tegelijk klaar is"],
    "Eén persoon voor alles is een gegarandeerde bottleneck."),
  q("Welke volgorde hoort bij een signature cocktail?", "Idee → familie en basisspirit → kernformule → finesse → naam en verhaal → vastleggen",
    ["Naam → garnering → ingrediënten → idee → kernformule → vastleggen", "Finesse → kernformule → idee → familie → naam → vastleggen", "Duurste fles → vijf ingrediënten → naam → verhaal → proeven"],
    "Het idee stuurt; de finesse komt pas na een werkende kern."),
  q("Waarom verpest ijstekort volgens de lessen elke volgende ronde?", "Je gaat ijs hergebruiken of zuinig doen, waardoor elke ronde sneller verwatert",
    ["Minder ijs maakt cocktails sterker, en dat valt bij gasten juist in de smaak", "Het glas kan knappen als je te weinig ijs gebruikt voor warme dranken", "Hergebruikt ijs maakt de volgende drank zoeter door suikerresten"],
    "Reken ruim: 150 g per drankje."),
  // Deel VI
  q("Wat trekt langer: steranijs of verse tijm?", "Steranijs: dagen tot weken; tijm: uren",
    ["Tijm: dagen tot weken; steranijs: uren", "Beide ongeveer precies 24 uur", "Beide een aantal weken"],
    "Harde, houtige ingrediënten trekken langzaam; delicate kruiden snel."),
  q("Wat betekenen de vetsporen die na fat-washing achterblijven?", "Het eindproduct moet gekoeld worden en binnen weken op",
    ["Het wordt daardoor juist onbeperkt houdbaar", "Het blijft troebel, maar is wel langer houdbaar", "Het kan daarna niet meer in de vriezer"],
    "Vet wordt sneller ranzig dan pure alcohol."),
  q("Wat heb je minimaal nodig om een cocktail met melk helder te maken?", "Een zure cocktail, melk en een koffiefilter",
    ["Een sodasifon", "Eiwit en een shaker", "Een rookpistool"],
    "Het zuur laat de melk schiften; het filter doet de rest."),
  q("Hoe houd je de prik in een cocktail met soda?", "Alles goed koud, soda op het eind en niet meeshaken",
    ["Soda op kamertemperatuur, dan schuimt het minder", "De soda meeshaken voor een betere menging", "Eerst de soda, dan de rest erop shaken"],
    "Kou houdt koolzuur vast en shaken laat het ontsnappen."),
  q("Hoe maak je een matige cocktail beter?", "Eerst de balans op orde brengen, pas daarna technieken inzetten",
    ["Er een paar seconden rook overheen blazen onder een cloche", "Hem clarificeren, zodat hij zachter en ronder wordt", "Hem carboneren, zodat hij frisser en levendiger smaakt"],
    "Geavanceerde technieken redden geen slecht recept."),
];
