// Toetsvragen voor de cursus: 5 per les + een eindtoets van 30.
// Bewust pittig: rekenvragen, praktijksituaties, "welke klopt níet" en
// foute antwoorden die echt aannemelijk klinken (vaak een waarheid uit een
// andere les, of een bekende misvatting) in plaats van evidente onzin.
//
// Formaat: { q, options, explain } — het GOEDE antwoord staat in de data
// altijd als eerste optie; de app husselt de volgorde bij elke poging
// (zie QuizBlock), dus de positie verraadt niets.

const q = (question, correct, wrong, explain) => ({ q: question, options: [correct, ...wrong], correct: 0, explain });

export const LESSON_QUIZZES = {
  geschiedenis: [
    q("Een Sazerac is volgens de logica van deze les het best te omschrijven als…", "Een Old Fashioned met een absint-wassing en een eigen bitter",
      ["Een Manhattan zonder vermout, met cognac en een scheut absint als basis", "Een sour waarin absint de plaats van het citrussap volledig inneemt", "Een punch waarvan de citrus, het water en de specerijen zijn weggelaten"],
      "Bijna elke klassieker is een variatie op sterkedrank, suiker, water en bitters. De Sazerac voegt daar een absint-wassing en Peychaud's aan toe."),
    q("Waar verwijst het woord \"punch\" volgens de gangbaarste verklaring naar?", "Het Hindi-woord voor vijf, naar het aantal ingrediënten",
      ["Het Engelse werkwoord voor slaan, naar de sterke werking", "De Portugese naam voor de kom waarin het werd geserveerd", "Een Britse scheepsofficier die het recept vastlegde"],
      "Pānch betekent vijf: sterkedrank, suiker, citrus, water en specerijen."),
    q("Welke volgorde van gebeurtenissen klopt?", "Eerste definitie van \"cocktail\" → eerste cocktailboek → begin van de drooglegging",
      ["Eerste cocktailboek → eerste definitie van \"cocktail\" → begin van de drooglegging", "Eerste definitie van \"cocktail\" → begin van de drooglegging → eerste cocktailboek", "Begin van de drooglegging → eerste definitie van \"cocktail\" → eerste cocktailboek"],
      "1806 de definitie, 1862 Jerry Thomas' \"How to Mix Drinks\", 1920 de drooglegging."),
    q("Welke bar noemt de les als broedplaats van nieuwe klassiekers tijdens de drooglegging?", "El Floridita in Havana",
      ["Trader Vic's in Californië", "Harry's Bar in Venetië", "The Balance and Columbian Repository in New York"],
      "El Floridita en Harry's New York Bar in Parijs. Trader Vic hoort bij tiki (na de oorlog), Harry's Bar in Venetië is een andere bar, en The Balance is de krant uit 1806."),
    q("Waarom noemt de les de jaren '70-'80 een dieptepunt?", "Kant-en-klare mixen verdrongen vers werken en vakmanschap",
      ["Tiki verdrong in die jaren de klassiekers bijna volledig van de kaart", "Europa voerde een eigen drooglegging in die de bars leegtrok", "Bitters waren tijdelijk niet meer te krijgen door een importverbod"],
      "Het verlies van vers werken en vakmanschap leidde tot de craft-revival rond 2000."),
  ],
  uitrusting: [
    q("Je shaket een South Side met verse munt in een cobbler shaker. Welk probleem ligt het meest voor de hand?", "De ingebouwde zeef raakt verstopt door de munt",
      ["De cocktail wordt niet koud genoeg door het dikke metaal", "Er past te weinig ijs in om goed te verdunnen", "Het metaal reageert met het citroensap"],
      "De cobbler lekt sneller en zijn ingebouwde zeef verstopt bij munt of vruchtvlees."),
    q("Welke combinatie van zeef en gereedschap klopt?", "Hawthorne op de shaker, julep op het roerglas",
      ["Julep op de shaker, hawthorne op het roerglas", "Hawthorne op het roerglas, fijne zeef als vervanger van de hawthorne op de shaker", "Julep-zeef voor dubbel zeven, hawthorne voor het roerglas"],
      "Hawthorne (met veerrand) hoort op de shaker, de julep-zeef op het roerglas; de fijne zeef komt er bij dubbel zeven bovenop."),
    q("Een recept vraagt 22,5 ml citroensap. Je schenkt vrijhandig en zit 20% te hoog. Hoeveel schenk je dan?", "Ongeveer 27 ml",
      ["Ongeveer 24,5 ml", "Ongeveer 25 ml", "Ongeveer 20 ml"],
      "22,5 × 1,2 = 27 ml. Bij een recept dat op balans steunt is dat het verschil tussen goed en scherp."),
    q("Waarom kies je een muddler zonder lak?", "Lak kan door het stampen afbladderen en in je drank belanden",
      ["Gelakt hout is te glad om kruiden en fruit goed mee te kneuzen", "Onbehandeld hout neemt aroma's op, en dat maakt elke volgende drank rijker", "Een gelakte muddler is te zwaar en beschadigt daardoor de munt"],
      "Een muddler wordt hard gebruikt; een laklaag hoort niet in je glas terecht te komen."),
    q("Met welke vier stukken raadt de les aan te beginnen?", "Boston-shaker-set, jigger, bar spoon en hawthorne-zeef",
      ["Cobbler shaker, jigger, muddler en julep-zeef", "Boston-shaker-set, mixing glass, julep-zeef en channel knife", "Jigger, bar spoon, fijne zeef en muddler"],
      "Met deze vier maak je elk recept uit de cursus."),
  ],
  glaswerk: [
    q("Waarom kiezen veel moderne bartenders een Nick & Nora boven een coupe?", "Kleiner en meer gebogen, waardoor de cocktail langer koud blijft",
      ["Hij laat het aroma sneller vrijkomen dan een brede coupe doet", "Er past een groot ijsblok in, zodat de cocktail langer koud blijft", "Hij houdt koolzuur langer vast dan een flute, handig voor fizzes"],
      "Snelle aroma-afgifte is juist de kracht van de brede coupe; de Nick & Nora behoudt de koude langer."),
    q("Waarom beslaat een koperen Moscow Mule-beker zo zichtbaar?", "Koper geleidt kou uitzonderlijk goed naar de buitenkant",
      ["Koper reageert met het gemberbier en vormt zo condens aan de buitenkant", "De beker is dunner dan glas en voelt daardoor altijd natter aan", "Het ijs smelt sneller in koper en het smeltwater trekt naar buiten"],
      "Het is geleiding: de kou van de inhoud zit binnen seconden aan de buitenkant."),
    q("Waarom gaat een longdrink in een highball en niet in een coupe?", "Er is volume nodig voor genoeg ijs, omdat de drank in het glas zelf koud moet blijven",
      ["Een highball laat het aroma van de mixer sneller vrijkomen dan een coupe", "Een hoog glas houdt koolzuur altijd beter vast dan een flute of coupe", "Frisdrank mag volgens de bartraditie niet in een glas op een steel worden geserveerd"],
      "\"Up\" cocktails zijn al gekoeld vóór het inschenken; longdrinks moeten in het glas koud blijven."),
    q("Welke cocktail hoort volgens de logica van deze les in een rocks-glas?", "Een Old Fashioned over een groot ijsblok",
      ["Een Daiquiri, geschud en up geserveerd", "Een French 75, aangevuld met champagne", "Een Tom Collins, aangevuld met veel soda"],
      "Rocks: kort, stevige bodem, ruimte voor een groot ijsblok of om te muddelen."),
    q("Welke uitspraak over \"up\" geserveerde cocktails klopt?", "Ze zijn al gekoeld en verdund vóór het inschenken en gaan zonder ijs het glas in",
      ["Ze worden altijd over één groot ijsblok in een rocks-glas geserveerd", "Ze worden pas in het glas zelf gekoeld, met een paar ijsblokjes erin", "Ze bevatten per definitie koolzuur en worden daarom in een coupe geschonken"],
      "Daarom werkt een glas zonder ijs, zoals een coupe."),
  ],
  ijs: [
    q("Je schudt 90 ml ingrediënten met ijs. Bij 25% verdunning: hoeveel vloeistof komt er uit de shaker?", "Ongeveer 112 ml",
      ["Ongeveer 90 ml", "Ongeveer 100 ml", "Ongeveer 135 ml"],
      "90 × 1,25 = 112,5 ml. Reken daarom met die extra 20-30% als je een glasmaat kiest."),
    q("12 gasten drinken gemiddeld 4 cocktails. Hoeveel ijs heb je volgens de vuistregel nodig?", "Ongeveer 7,2 kg",
      ["Ongeveer 1,8 kg", "Ongeveer 4,8 kg", "Ongeveer 12 kg"],
      "48 cocktails × 150 g = 7,2 kg."),
    q("Waarom gebruik je voor een Julep juist crushed ijs?", "Het smelt snel en geeft een intense, snelle koeling en verdunning",
      ["Het smelt trager dan kubusijs, zodat de drank niet waterig wordt", "Het voorkomt dat de munt oxideert en bitter wordt in het glas", "Het houdt het koolzuur van de soda langer vast dan kubusijs"],
      "Crushed ijs = snelle verdunning, bewust gekozen voor Mojito, Julep en tiki."),
    q("Je gebruikt het ijs uit de shaker opnieuw om over te serveren. Wat is daar mis mee?", "Het is al deels gesmolten en verdunt je drank sneller",
      ["Niets, het is al koud en koelt de drank daardoor juist sneller", "Het maakt de cocktail troebel door resten eiwit en citrus", "Het is te koud geworden en bevriest daardoor de garnering"],
      "Gebruik voor elke stap vers ijs."),
    q("Waarom houden bartenders een vaste schud- of roertijd aan?", "Verdunning hoort bij het recept en tijd is de betrouwbaarste maat",
      ["Anders wordt de shaker te koud om nog goed vast te kunnen houden", "Langer schudden maakt een cocktail altijd sterker en minder zoet", "Anders smelt het ijs helemaal niet en blijft de cocktail te geconcentreerd"],
      "\"Tot het koud aanvoelt\" is geen maatstaf; een vaste tijd geeft een vaste verdunning."),
  ],
  gedistilleerd: [
    q("Een Amerikaanse whiskey met 60% maïs rijpt op gebruikte vaten. Waarom mag hij geen bourbon heten?", "Bourbon moet rijpen in nieuwe, verkoolde eikenvaten",
      ["Bourbon moet voor minstens 75% uit maïs bestaan", "Bourbon mag uitsluitend in Kentucky gemaakt worden", "Bourbon moet driemaal gedistilleerd worden, net als Irish"],
      "Minstens 51% maïs én nieuwe, verkoolde eikenvaten. Dat bourbon uit Kentucky moet komen is een bekende misvatting."),
    q("Welke whiskey noemt de les als klassieke basis voor Manhattan en Sazerac?", "Rye",
      ["Bourbon", "Irish whiskey", "Rokerige Islay-scotch"],
      "Rye is droger en pittiger dan bourbon; daarom de klassieke keuze voor deze twee."),
    q("Waarom verdampt alcohol eerder dan water tijdens het distilleren?", "Alcohol heeft een lager kookpunt dan water",
      ["Alcohol is zwaarder dan water", "Water bindt zich aan de suikers in het beslag", "De koperen ketel trekt het water aan"],
      "Daardoor kun je de alcoholdamp apart opvangen en weer vloeibaar maken."),
    q("Welke uitspraak over mezcal klopt?", "Mag van meerdere agavesoorten zijn en wordt traditioneel ondergronds geroosterd",
      ["Het is in feite tequila, maar dan met een hoger alcoholpercentage en langer gerijpt", "Mag alleen van blauwe agave gemaakt worden, net als tequila, maar uit een andere streek", "Krijgt zijn rokerige smaak door lange rijping in sterk verkoolde eikenhouten vaten"],
      "De rook komt van het roosteren, niet van het vat. Alleen blauwe agave is de regel voor tequila."),
    q("Waarom werden sommige negentiende-eeuwse klassiekers oorspronkelijk met cognac gemaakt?", "Vóór de druifluis phylloxera was cognac de dominante cocktailbasis in Amerika",
      ["Whiskey was in die periode in grote delen van Amerika verboden", "Cognac was destijds goedkoper dan rum en whiskey samen", "De drooglegging maakte whiskey onbereikbaar, cognac niet"],
      "Phylloxera verwoestte eind negentiende eeuw de wijngaarden; de drooglegging kwam pas in 1920."),
  ],
  "likeuren-bitters": [
    q("Een geopende fles zoete vermout staat al drie maanden buiten de koelkast. Wat is het meest waarschijnlijk?", "Hij is geoxideerd en vlak geworden: vervangen",
      ["Prima, vermout is door de extra alcohol onbeperkt houdbaar", "Hij is iets sterker geworden doordat water verdampt", "Alleen de kleur is veranderd, de smaak niet"],
      "Vermout is wijn en oxideert na opening, zelfs gekoeld binnen weken."),
    q("Welke vermout hoort in een klassieke Martini, en welke in een Manhattan?", "Droge in de Martini, zoete in de Manhattan",
      ["Zoete in de Martini, droge in de Manhattan", "Droge in beide", "Zoete in beide"],
      "Droog en kruidig voor de Martini, vol en zoet als ruggengraat van Manhattan en Negroni."),
    q("Wat onderscheidt Peychaud's van Angostura?", "Lichter en anijsachtig, tegenover kruidig en kaneelachtig",
      ["Peychaud's is een likeur die je in milliliters doseert, geen bitter", "Angostura is juist de lichtere, anijsachtige van de twee", "Peychaud's bevat geen alcohol en is daardoor milder van smaak"],
      "Beide zijn bitters in dashes; Peychaud's is lichter en anijsachtig."),
    q("Waarom vergelijkt de les bitters met zout in de keuken?", "Ze benadrukken andere smaken in plaats van zelf te overheersen",
      ["Ze maken de cocktail merkbaar zouter, net als een zoutrand", "Ze conserveren de cocktail, zodat je hem langer kunt bewaren", "Ze vervangen de suiker, zodat de cocktail minder zoet wordt"],
      "Een paar dashes scherpen de hele cocktail aan."),
    q("Hoe vaak raadt de les aan geopende vermout, sherry en port te vervangen bij regelmatig gebruik?", "Elke 4-6 weken",
      ["Elke 1-2 weken", "Elke 4-6 maanden", "Pas als de fles leeg is, zolang hij gekoeld staat"],
      "Gekoeld bewaren en elke 4-6 weken vervangen: de goedkoopste verbetering van je bar."),
  ],
  vers: [
    q("Wat is volgens de les dé reden dat professionele sours anders smaken dan een thuisversie?", "Vers geperst citrussap in plaats van flessensap",
      ["Duurdere, langer gerijpte sterkedrank uit de speciaalzaak", "Meer en rijkere suikersiroop, zoals honing", "Langer en harder schudden met meer ijs"],
      "Vers sap heeft vluchtige aromatische oliën die flessensap mist."),
    q("Wat zit er in orgeat?", "Amandel en oranjebloesemwater",
      ["Limoen, gember, amandel en kruidnagel", "Honing en gember", "Granaatappel en suiker"],
      "Limoen, gember, amandel en kruidnagel is falernum; granaatappel en suiker is grenadine."),
    q("Je slaat bij een Whiskey Sour met eiwit de dry shake over. Wat gebeurt er?", "Je krijgt een dunnere schuimlaag",
      ["Het eiwit stolt door de kou", "De cocktail wordt zoeter", "Niets, zolang je maar lang genoeg met ijs schudt"],
      "Zonder ijs emulgeert het eiwit beter; daarna pas met ijs koelen."),
    q("Hoe maak je gewone suikersiroop volgens de les?", "Gelijke delen suiker en water",
      ["Twee delen suiker op één deel water", "Eén deel suiker op drie delen water", "Suiker opgelost in citroensap"],
      "1:1 lost direct en volledig op in een koude cocktail."),
    q("Wat kun je het verst van tevoren klaarmaken voor een feest?", "Suikersiroop",
      ["Citroensap", "Limoensap", "Opgeklopt eiwit"],
      "Citrussap verliest binnen 24 uur al merkbaar aan frisheid."),
  ],
  garnering: [
    q("Twee identieke Old Fashioneds, één met een uitgeknepen sinaasappelschil. Wat verandert er?", "De geur, en daarmee de beleving, niet de vloeistof zelf",
      ["De cocktail wordt merkbaar zuurder door het sap uit de schil", "Hij wordt zoeter doordat de schil suikers afgeeft", "Niets, een twist is puur visueel en verandert de ervaring niet"],
      "De oliën liggen als aromawolk op het drankoppervlak."),
    q("Wat gebeurt er als je munt fijnstampt in plaats van klapt?", "De beschadigde blaadjes oxideren en worden bitter",
      ["De munt geeft juist meer frisse smaak af, dus dat is beter", "Het ijs smelt sneller door de fijne muntdeeltjes", "De drank wordt troebel, maar de smaak blijft precies hetzelfde"],
      "Een korte klap activeert het aroma zonder de blaadjes te beschadigen."),
    q("Welke garnering hoort bij een Gibson?", "Een zilveruitje",
      ["Een olijf", "Een citroentwist", "Een cocktailkers"],
      "Olijf bij de (Dirty) Martini, zilveruitje bij de Gibson."),
    q("Een parasolletje en drie kersen op een Zombie: welke functie heeft dat volgens de les?", "Sfeer en beleving, passend bij de tiki-traditie",
      ["Aroma, net zoals een uitgeknepen citrustwist doet", "Een zoete tegenhanger voor de sterke rum", "Temperatuurbeheersing door de koude kersen"],
      "Bij tiki is garnering vaak sfeer, en dat is een legitieme keuze."),
    q("Welke vraag stel je volgens de pro-tip bij elke garnering?", "Voegt dit aroma, smaak, temperatuur of sfeer toe?",
      ["Past de kleur van de garnering bij het glas?", "Is de garnering goedkoop genoeg voor een feest?", "Kan een gast de garnering veilig opeten?"],
      "Een bewuste keuze levert altijd een overtuigender resultaat."),
  ],
  basistechnieken: [
    q("Welke cocktail roer je in plaats van hem te schudden?", "Manhattan",
      ["Daiquiri", "Whiskey Sour", "Cosmopolitan"],
      "Alleen heldere, alcoholische ingrediënten: roeren. Zit er sap in, dan schud je."),
    q("Hoe lang schud je kort en hard volgens de les?", "10-15 seconden",
      ["3-5 seconden", "30-45 seconden", "Tot de shaker bevroren aanvoelt"],
      "Kort en hard; lang en zacht voegt vooral water toe."),
    q("Wat is de juiste volgorde bij een eiwitcocktail volgens de les?", "Eerst zonder ijs schudden, daarna met ijs",
      ["Eerst met ijs schudden, daarna zonder ijs", "Alleen met ijs schudden, maar twee keer zo lang", "Eerst roeren met ijs, dan kort schudden"],
      "De dry shake emulgeert het eiwit vóór het ijs erbij komt."),
    q("Met welke techniek maak je een Gin Tonic?", "Bouwen",
      ["Shaken", "Roeren in een roerglas", "Swizzelen"],
      "Direct in het glas over ijs, eventueel kort roeren."),
    q("Waarom schud je een Martini niet?", "Je klopt er lucht in en hij wordt troebel",
      ["Hij wordt dan te warm door je handen", "De vermout gaat dan schuimen en scheiden", "Hij verdunt dan veel minder dan bij roeren"],
      "Roeren koelt en verdunt zonder troebelheid."),
  ],
  "verdunning-temperatuur": [
    q("Hoe lang roer je volgens de les?", "20-30 seconden, rustig",
      ["10-15 seconden, hard", "5 seconden", "Tot het glas beslaat, ongeacht de tijd"],
      "10-15 seconden hard is de schudtijd; roeren duurt langer."),
    q("Welke drie variabelen stuur je bij elke shake- of roerbeweging?", "Tijd, ijshoeveelheid en beweging",
      ["Tijd, glasvorm en garnering", "IJsvorm, suiker en de temperatuur van de fles", "Beweging, alcoholpercentage en zuur"],
      "Samen bepalen ze verdunning én temperatuur."),
    q("Na een bepaald punt levert langer schudden vooral… op.", "Extra water, en nauwelijks nog extra kou",
      ["Een steeds koudere cocktail, dus langer is beter", "Meer schuim en daardoor een sterkere drank", "Een warmere cocktail door de wrijving van het ijs"],
      "De koelcapaciteit is dan grotendeels op; het ijs smelt alleen nog."),
    q("Je koelt een coupe voor met ijswater. Wanneer giet je dat weg?", "Vlak vóór het inschenken",
      ["Laten staan als extra verdunning", "Na het inschenken", "Voordat je begint met schudden"],
      "Giet je het te vroeg weg, dan warmt het glas alweer op."),
    q("Waarom proef je uit de shaker vóór het zeven?", "Je kunt nog bijstellen voordat de cocktail in het glas zit",
      ["Om te controleren of het ijs al helemaal gesmolten is", "Om de temperatuur van het voorgekoelde glas te meten", "Dat raadt de les juist af, omdat het de cocktail verdunt"],
      "Met oefening proef je precies wanneer een drank \"af\" is."),
  ],
  "sour-formule": [
    q("Hoeveel citrus hoort volgens de formule bij 60 ml sterkedrank?", "22-25 ml",
      ["10-12 ml", "30-35 ml", "60 ml"],
      "2 : ¾ : ¾ → bij 60 ml sterk ongeveer 22-25 ml zuur en 20-25 ml zoet."),
    q("Je maakt een sour met 45 ml sterkedrank volgens 2 : ¾ : ¾. Hoeveel zuur en zoet?", "Ongeveer 17 ml zuur en 17 ml zoet",
      ["Ongeveer 22 ml zuur en 22 ml zoet", "Ongeveer 11 ml zuur en 11 ml zoet", "Ongeveer 34 ml zuur en 34 ml zoet"],
      "45 ÷ 2 × ¾ ≈ 17 ml."),
    q("Je vervangt citroensap door limoensap in hetzelfde recept. Wat verwacht je?", "Een scherper resultaat; misschien iets meer zoet nodig",
      ["Een zoeter resultaat, waardoor je minder siroop nodig hebt", "Geen verschil: zuur is zuur, de verhouding blijft kloppen", "Minder zuur, waardoor je meer citrus moet toevoegen"],
      "Limoensap is scherper dan citroensap."),
    q("Een Margarita met 50 ml tequila, 20 ml triple sec en 20 ml limoen heeft geen suikersiroop. Waarom is hij toch in balans?", "Triple sec levert het zoete element",
      ["Tequila is van zichzelf zoet genoeg", "Limoensap is zoeter dan citroensap", "Het zoutrandje vervangt het zoet"],
      "Een zoete likeur telt deels mee als zoet."),
    q("Je gebruikt honingsiroop in plaats van suikersiroop, in dezelfde hoeveelheid. Wat is het effect?", "Het wordt zoeter: iets minder gebruiken of bijstellen",
      ["Het wordt minder zoet: iets meer gebruiken", "Precies hetzelfde resultaat, zoet is zoet", "Het wordt zuurder door de zuren in honing"],
      "Honingsiroop is intenser dan neutrale suikersiroop."),
  ],
  finesse: [
    q("Welke cocktail heeft het meeste baat bij dubbel zeven?", "Een geschudde Daiquiri, up in een coupe",
      ["Een Old Fashioned op één groot ijsblok", "Een Gin Tonic, gebouwd in het glas", "Een geroerde Negroni, geserveerd op ijs"],
      "Zonder ijs in het glas vallen splinters en vruchtvlees direct op."),
    q("In een B-52 liggen koffielikeur, Irish cream en Grand Marnier van onder naar boven. Wat bepaalt die volgorde?", "Dichtheid: de zwaarste, suikerrijkste likeur onderin",
      ["Kleur: van donker naar licht", "Alcoholpercentage: de sterkste onderin", "Smaak: de sterkste smaak bovenop voor de eerste slok"],
      "Dat de kleur toevallig mooi verloopt is een bijeffect; dichtheid bepaalt of de laag blijft liggen."),
    q("Hoe krijg je een drijflaag rode wijn op een New York Sour?", "Langzaam over de bolle kant van een bar spoon gieten",
      ["De wijn eerst koelen, zodat hij zwaarder wordt dan de sour", "Snel uit de fles gieten, zodat de wijn bovenop blijft liggen", "De wijn kort meeschudden en daarna laten bezinken in het glas"],
      "De lepel breekt de val; door het dichtheidsverschil blijft de wijn drijven."),
    q("Waarom oefen je een citrus-expressie eerst boven de gootsteen?", "Hoek en druk vragen een paar pogingen",
      ["De oliën zijn in grote hoeveelheden giftig", "Om de schil eerst te laten drogen", "Anders wordt de cocktail te zuur"],
      "Beter een paar mislukte pogingen boven de gootsteen dan boven een net gemaakte cocktail."),
    q("Waarom dubbel zeef je een geroerde cocktail zoals een Martini meestal niet?", "Bij roeren ontstaan geen splinters of vruchtvlees",
      ["Dubbel zeven zou hem te veel verdunnen en koelen", "Een fijne zeef houdt een deel van de vermout tegen", "Omdat een geroerde cocktail altijd op ijs wordt geserveerd"],
      "Dubbel zeven is de standaard voor geschudde \"up\" cocktails."),
  ],
  // Deel IV: praktijkvragen. Geen rekenwerk of weetjes, wel: wat proef je,
  // waarom, en wat doe je eraan.
  families: [
    q("Je Whiskey Sour smaakt plakkerig en de whiskey valt weg. Wat doe je?", "Een scheutje citroen erbij, of de volgende keer minder siroop",
      ["Meer ijs in de shaker, zodat hij meer verdunt", "Extra whiskey erbij schenken", "Langer shaken"],
      "Plakkerig betekent te zoet. Met meer zuur trek je hem terug in balans, zonder dat hij slapper wordt."),
    q("Je Margarita trekt je wangen samen en smaakt dun. Wat is er aan de hand?", "Te zuur: er mag iets meer zoet bij",
      ["Te zoet: er mag meer limoen bij", "Te sterk: er moet meer ijs bij", "Te koud: laat hem even staan"],
      "Prikken en dun smaken is zuur dat geen tegenwicht krijgt."),
    q("Waarom proef je met een rietje voordat je inschenkt?", "Citrus verschilt per vrucht, en nu kun je nog bijsturen",
      ["Zo controleer je of hij koud genoeg is", "Zo proef je of de alcohol goed is opgelost", "Zo blijft er minder in de shaker achter"],
      "Het recept is een startpunt; jouw citroen bepaalt de rest."),
    q("Je cocktail is net te zuur. Hoe stuur je bij?", "Een klein beetje siroop erbij, ongeveer 5 ml, en opnieuw proeven",
      ["Meteen een flinke scheut siroop, dan merk je het tenminste", "De hoeveelheid siroop verdubbelen", "Opnieuw beginnen met minder citroen en meer drank"],
      "Kleine stappen voorkomen dat je doorschiet naar te zoet."),
    q("Wat doet zoet in een cocktail, behalve zoet maken?", "Het maakt hem ronder en dempt de scherpte van de alcohol",
      ["Het maakt hem frisser en lichter", "Het zorgt dat het ijs langzamer smelt", "Het laat de citrus scherper naar voren komen"],
      "Daarom voelt een sour zonder siroop zo hard aan."),
  ],
  smaakcombinatie: [
    q("Je drankje is te zoet, maar met meer citroen wordt hij te zuur. Wat probeer je?", "Een of twee dashes bitters",
      ["Meer siroop om het zuur te maskeren", "Meer ijs, zodat het zoet verdwijnt", "Een scheut sinaasappelsap"],
      "Bitter remt zoet af zonder dat het drankje zuurder wordt."),
    q("Wat doet een paar korrels zout in een cocktail?", "Het verzacht bitter en laat fruit en citrus voller proeven",
      ["Het maakt de cocktail merkbaar zout, zoals een zoutrand", "Het haalt de alcoholsmaak weg", "Het maakt de cocktail zoeter zonder suiker"],
      "In kleine hoeveelheid proef je zout niet als zout, maar als meer smaak."),
    q("Je Old Fashioned brandt in je keel. Wat is de beste eerste stap?", "Langer roeren met ijs, zodat er meer water bij komt",
      ["Meer suikersiroop toevoegen", "Er een scheut cola bij doen", "Een andere garnering kiezen"],
      "Water en kou temperen de alcohol; suiker maakt hem alleen zwaarder."),
    q("Waarom smaakt een Negroni die niet geroerd is zo hard?", "Zonder water en kou komen alcohol en bitter vol naar voren",
      ["De vermout is dan nog niet goed gemengd", "Campari wordt pas zoet als hij koud is", "De sinaasappel heeft zijn smaak nog niet afgegeven"],
      "Roeren met ijs is geen detail: het maakt de drank zachter."),
    q("Een gast vindt je cocktail \"plat\". Wat helpt meestal het meest?", "Een tegenwicht, zoals een bittere noot of een paar korrels zout",
      ["Meer van hetzelfde zoete ingrediënt", "Een sterkere drank als basis", "Hem langer laten staan"],
      "Plat betekent vaak: er is niets wat tegen de rest ingaat."),
  ],
  ontwerpen: [
    q("Je wilt een eigen versie van een Daiquiri maken. Wat is de slimste start?", "Eén onderdeel wisselen, bijvoorbeeld de rum voor een andere drank",
      ["Alle drie de ingrediënten vervangen", "Er twee likeuren bij doen voor meer smaak", "De verhoudingen omdraaien"],
      "Het skelet werkt al; met één wissel blijft de balans grotendeels kloppen."),
    q("Je vervangt de suikersiroop door een sinaasappellikeur. Waar let je op?", "Likeur is minder zoet dan siroop, dus je hebt er meer van nodig",
      ["Likeur is zoeter, dus neem de helft", "Er verandert niets, zoet is zoet", "Je moet dan ook de citroen weglaten"],
      "Een likeur is deels alcohol en deels suiker: minder zoet per scheut."),
    q("Je wisselt citroen voor grapefruit. Wat gebeurt er waarschijnlijk?", "Het wordt minder zuur en iets bitterder, dus misschien minder siroop",
      ["Het wordt zuurder, dus je hebt meer siroop nodig", "Er verandert niets aan de balans", "Het wordt zoeter, dus er moeten bitters bij"],
      "Grapefruit is milder dan citroen en heeft een eigen bitter."),
    q("Je twist smaakt goed, maar je hebt drie dingen tegelijk veranderd. Wat is het probleem?", "Je weet niet wat het verschil maakte, dus je kunt het lastig herhalen of verbeteren",
      ["Er is geen probleem: smaakt het goed, dan is het goed", "Drie wijzigingen maken een drankje altijd onstabiel", "Hij telt dan niet meer als twist op een klassieker"],
      "Eén ding tegelijk is langzamer, maar je leert er van elke versie iets."),
    q("Je werkt met rokerige mezcal. Waarmee maak je het spannend in plaats van zwaar?", "Iets fris en fruitigs, zoals ananas of grapefruit",
      ["Nog iets rokerigs, zoals een Islay-whisky", "Een zware koffielikeur", "Zo min mogelijk andere smaken"],
      "Een tegenhanger houdt het levendig; meer van hetzelfde maakt het log."),
  ],
  menu: [
    q("Je maakt een menu voor een gemengd gezelschap. Wat kies je?", "Paloma, Negroni, Espresso Martini en een alcoholvrije optie",
      ["Negroni, Manhattan, Old Fashioned en Boulevardier", "Daiquiri, Margarita, Whiskey Sour en Pisco Sour", "De vier cocktails die jij zelf het lekkerst vindt"],
      "Fris, sterk, zacht en zonder alcohol: iedereen vindt iets."),
    q("Waarom is drie tot vijf cocktails meestal beter dan tien?", "Minder flessen en werk, en gasten kiezen makkelijker",
      ["Met meer cocktails drinken gasten te veel", "Met meer cocktails raakt je ijs sneller op", "Tien cocktails passen niet op een menukaart"],
      "Een kleine kaart die goed is, werkt beter dan een grote die je niet bijhoudt."),
    q("Welke cocktail kun je uren vooraf in een fles klaarzetten?", "Een Negroni: alleen drank, geen sap of ei",
      ["Een Whiskey Sour met eiwit", "Een Mojito met verse munt", "Een Daiquiri met vers limoensap"],
      "Sap, ei en verse kruiden verliezen snel hun frisheid."),
    q("Twee cocktails op je menu vragen elk een fles die je verder nergens voor gebruikt. Wat doe je?", "Eén van de twee vervangen door iets met wat je al hebt",
      ["Beide flessen kopen: variatie gaat altijd voor", "Ze houden en de porties kleiner maken", "Ze maken zonder die fles en de rest verdubbelen"],
      "Gedeelde ingrediënten houden het betaalbaar zonder dat het menu saai wordt."),
    q("Waarom hoort er altijd een volwaardige alcoholvrije optie op je menu?", "Er is bijna altijd iemand die niet drinkt, en die verdient meer dan frisdrank",
      ["Zo spaar je je dure flessen", "Het is verplicht op een feest", "Dan blijf je zelf ook nuchter"],
      "Een gast zonder alcohol hoort net zo goed iets bijzonders in het glas te krijgen."),
  ],
  "mise-en-place": [
    q("Welke opstelling volgt de volgorde van bereiding?", "Sterkedrank vooraan bij de shaker, dan likeuren, bitters en vers",
      ["Vers ingrediënten het dichtst bij de shaker, sterkedrank achteraan", "Bitters vooraan, omdat die er als eerste in de shaker gaan", "Alles op alfabet, zodat je elke fles snel terugvindt"],
      "De volgorde van bereiding voorkomt heen-en-weer lopen."),
    q("Wat kun je uren tot een dag van tevoren klaarmaken?", "Siropen en de meeste garneringen",
      ["Vers citrussap en muntblaadjes", "Opgeklopt eiwit voor de sours van die avond", "Geschudde sours zonder ijs, gekoeld bewaard"],
      "Citrussap en munt verliezen binnen uren aan kwaliteit."),
    q("Waar bewaar je gesneden garnering tijdens de avond?", "Op ijs",
      ["Op kamertemperatuur, zodat het aroma sterker is", "In de vriezer", "In een glas water op het aanrecht"],
      "Koel en binnen handbereik."),
    q("Wat hoort volgens de pro-tip op je feest-checklist?", "IJs, glazen, te snijden garnering en wat je kunt batchen",
      ["De afspeellijst, de verlichting en de zitplaatsen", "De prijs per fles en het totale budget", "Het alcoholpercentage per cocktail op het menu"],
      "Tien minuten plannen scheelt uren improviseren."),
    q("Welk ingrediënt verliest volgens de les binnen uren aan kwaliteit?", "Munt",
      ["Suikersiroop", "Kaneelstokjes", "Angostura"],
      "Net als citrussap: zo dicht mogelijk bij het serveren."),
  ],
  "batchen-groepen": [
    q("Je batcht 10 Negroni's van 90 ml zonder ijs. Hoeveel water voeg je toe bij 20% verdunning?", "180 ml",
      ["90 ml", "20 ml", "300 ml"],
      "900 ml × 20% = 180 ml."),
    q("Waarom werkt een gebatchte Negroni beter dan een gebatchte Whiskey Sour met eiwit?", "Geen vers sap, eiwit of zuivel, dus de kwaliteit blijft gelijk",
      ["Een Negroni is sterker en daardoor vanzelf langer houdbaar", "Een sour kun je niet opschalen zonder de verhouding te verliezen", "Eiwit wordt in de koelkast binnen een paar uur onveilig"],
      "Net-geshakete textuur gaat verloren als je te vroeg maakt."),
    q("20 gasten, een feest van 3 uur. Hoeveel drankjes volgens de vuistregel?", "Ongeveer 80",
      ["Ongeveer 60", "Ongeveer 40", "Ongeveer 120"],
      "Per gast 2 + 1 + 1 = 4 drankjes → 80."),
    q("Wat is bij grote groepen volgens de les vaak de eerste bottleneck?", "IJs",
      ["Sterkedrank", "Glazen", "Citrus"],
      "Reken op 150 g per drankje."),
    q("Wanneer maak je een batch idealiter klaar?", "Dezelfde dag",
      ["Een week van tevoren", "Een maand van tevoren, gekoeld", "Pas als de gasten er zijn, per glas"],
      "Uren wachten met de verdunning erin gaat ten koste van de kwaliteit."),
  ],
  gastvrijheid: [
    q("Een gast weet niet wat hij wil. Wat is de beste eerste stap?", "Vragen: bitter of zoet, sterk of licht?",
      ["Je eigen favoriet serveren", "De sterkste cocktail van het menu aanbieden", "Een shot geven om het ijs te breken"],
      "Een paar seconden vragen voorkomt een misser en toont aandacht."),
    q("Een gast drinkt geen alcohol. Wat past bij de les?", "Een even doordachte, volwaardige alcoholvrije cocktail",
      ["Fris uit een pak, zodat de gast snel iets heeft", "Water, dat is het meest neutraal en past bij alles", "Een cocktail met de helft minder alcohol dan normaal"],
      "Niet-drinkers verdienen dezelfde zorg als de rest."),
    q("Waarom vertel je een kort verhaal bij een cocktail?", "Het verandert hoe gasten dezelfde drank waarderen",
      ["Om tijd te winnen terwijl je de cocktail schudt", "Omdat een verhaal de smaak van de drank echt verandert", "Het hoort verplicht bij elke klassieke cocktail"],
      "Kennis delen is zelf onderdeel van de gastvrijheid."),
    q("Een gastheer staat de hele avond achter de bar. Welke oplossing noemt de les?", "Meer vooraf voorbereiden en batchen",
      ["Minder gasten uitnodigen", "Alleen bier schenken", "Gasten zelf laten mixen zonder uitleg"],
      "Voorbereiding is ook gastvrijheid naar jezelf."),
    q("Wat betekent \"tempo lezen\"?", "Aanvoelen wanneer een gezelschap toe is aan de volgende ronde",
      ["Zo snel mogelijk nieuwe drankjes blijven serveren aan iedereen", "Elke twintig minuten vast een nieuwe ronde maken", "Wachten tot de gasten er zelf om komen vragen"],
      "Niet te snel en niet te traag: het gezelschap bepaalt het ritme."),
  ],
  signature: [
    q("Waar begin je bij een signature cocktail?", "Bij een idee, herinnering of gevoel",
      ["Bij de duurste fles in huis", "Bij een bestaand recept dat je precies kopieert", "Bij de garnering"],
      "Het verhaal stuurt de ingrediëntkeuze."),
    q("Hoeveel testrondes raadt de les aan?", "Vijf tot tien",
      ["Eén of twee", "Twintig tot dertig", "Doorgaan tot vijftig"],
      "Ook professionals halen zelden in de eerste poging hun beste versie."),
    q("Hoe begin je het makkelijkst aan een eigen cocktail?", "Met een klassieker die werkt, waarin je één onderdeel wisselt",
      ["Met een leeg vel en vijf ingrediënten die je lekker vindt", "Met de duurste fles die je in huis hebt", "Met een naam, en daarna de ingrediënten erbij zoeken"],
      "Les 15: een werkend skelet, één wissel, proeven en opschrijven."),
    q("Wat doe je met elke testversie?", "Noteren, en per keer één variabele aanpassen",
      ["Weggooien als hij niet meteen perfect is", "Meerdere dingen tegelijk aanpassen om tijd te sparen", "Alleen de laatste versie onthouden"],
      "Zo weet je welke aanpassing het verschil maakte."),
    q("Waaruit ontstaan de beste signature cocktails volgens de laatste pro-tip?", "Uit een oprechte poging een probleem op te lossen of een gevoel op te roepen",
      ["Uit een poging zo origineel en verrassend mogelijk te zijn", "Uit het combineren van zo veel mogelijk zeldzame ingrediënten", "Uit het nauwkeurig volgen van de nieuwste bartrends"],
      "Origineel-zijn om het origineel-zijn werkt zelden."),
  ],
  infusies: [
    q("Welk ingrediënt trekt het snelst over en wordt daarna bitter?", "Verse rozemarijn",
      ["Kaneelstokjes", "Steranijs", "Gedroogde citrusschil"],
      "Verse kruiden: 2-6 uur; specerijen: dagen."),
    q("Welke trektijd geeft de tabel voor specerijen zoals kaneel en kardemom?", "3-7 dagen",
      ["2-6 uur", "1-3 dagen", "4-6 weken"],
      "2-6 uur is voor verse kruiden, 1-3 dagen voor citrusschil en vers fruit."),
    q("Waarom gebruik je bij citrusschil alleen het gekleurde deel?", "Het witte deel is bitter",
      ["Het witte deel lost niet op in alcohol", "De gekleurde schil bevat het meeste suiker", "Het witte deel maakt de infusie troebel maar smaakt hetzelfde"],
      "Alleen de gele of oranje schil."),
    q("Hoe bewaar je een infusie met verse aardbeien in wodka?", "In de koelkast, en binnen een week opmaken",
      ["Op kamertemperatuur: alcohol conserveert alles", "In de zon, voor snellere extractie", "Maandenlang in een donkere kast"],
      "Vers, waterig materiaal maakt van de infusie een vers product."),
    q("Vanaf wanneer proef je een infusie?", "Vanaf dag één, dagelijks",
      ["Pas na een week", "Pas aan het eind van de trektijd uit de tabel", "Niet: je volgt de tabel exact"],
      "Trektijden verschillen per merk en oogst; zeef zodra de smaak goed is."),
  ],
  "fat-washing": [
    q("Wat is de juiste volgorde bij fat-washing?", "Warm mengen, laten trekken, invriezen, afscheppen, zeven",
      ["Invriezen, warm mengen, zeven, afscheppen, laten trekken", "Zeven, warm mengen, laten trekken, invriezen, afscheppen", "Warm mengen, zeven, invriezen, laten trekken, afscheppen"],
      "Invriezen maakt het vet vast, zodat je het kunt afscheppen."),
    q("Hoe lang moet het mengsel minimaal in de vriezer?", "6 uur",
      ["30 minuten", "2 dagen", "1 week"],
      "Lang genoeg om het vet volledig vast te laten worden."),
    q("Welke aroma's haal je met fat-washing binnen?", "Vetoplosbare aroma's die water en alcohol alleen niet goed vasthouden",
      ["Zuren die alleen in vet oplossen en de drank frisser maken", "Suikers uit het vet die de spirit zoeter en ronder maken", "Eiwitten uit het vet die zorgen voor een romig mondgevoel"],
      "Denk aan gebakken boter of spek."),
    q("Waarvoor wordt olijfolie-gin gebruikt?", "Een savoury Dirty Martini",
      ["Een Gin Fizz met extra schuim", "Een zoete dessertcocktail", "Een Negroni zonder bitter"],
      "Olijfolie versterkt de hartige kant."),
    q("Hoeveel vet gebruik je volgens de richtlijn per fles?", "Ongeveer 50 ml",
      ["Ongeveer 10 ml", "Ongeveer 200 ml", "Evenveel vet als spirit"],
      "Te veel vet is lastig volledig te scheiden."),
  ],
  clarificatie: [
    q("Hoe begin je een melk-clarificatie?", "De zure cocktail toevoegen aan warme volle melk",
      ["Melk toevoegen aan een ijskoude cocktail zonder citrus", "Agar door de melk mengen", "Room door de cocktail mengen en invriezen"],
      "Het zuur laat de melkeiwitten schiften; zonder zuur gebeurt er niets."),
    q("Wat verandert er naast de helderheid door melk-clarificatie?", "Een zachter mondgevoel en iets minder zuur",
      ["Een hoger alcoholpercentage door het indampen", "Meer bitterheid in de afdronk door de wrongel", "Een licht bruisend mondgevoel door de melkzuren"],
      "De wrongel trekt ook een deel van de scherpte mee."),
    q("Wat zijn de stappen bij agar-clarificatie?", "Agar oplossen, laten geleren, gel breken, invriezen, langzaam ontdooien boven een filter",
      ["Agar oplossen in de cocktail en die direct door een koffiefilter zeven", "Invriezen, dan agar toevoegen, dan kort opkoken en afkoelen", "Melk en agar door de cocktail mengen en laten schiften tot wrongel"],
      "De heldere vloeistof druipt eruit; de troebele deeltjes blijven in het gel-netwerk."),
    q("Hoe lang duurt agar-clarificatie ongeveer?", "1-2 dagen",
      ["Enkele minuten", "Enkele uren", "Een week"],
      "Invriezen en langzaam ontdooien kost tijd; melk-clarificatie duurt enkele uren."),
    q("Waarom is een geclarificeerde cocktail niet langer houdbaar dan het origineel?", "Clarificatie verwijdert deeltjes, geen bacteriën",
      ["Omdat er altijd melkresten in achterblijven die bederven", "Omdat de alcohol tijdens het lange zeven grotendeels verdampt", "Dat klopt niet: helder betekent onbeperkt houdbaar"],
      "Gekoeld bewaren en binnen een paar dagen gebruiken."),
  ],
  "carbonatie-rook": [
    q("Hoe ver vul je een soda-sifon?", "Tot twee derde",
      ["Helemaal vol", "Tot een derde", "Tot de helft, en daarna ijs erbij"],
      "De ruimte erboven is nodig voor het gas."),
    q("Welke cocktail leent zich het minst voor een sifon?", "Een troebele cocktail met veel vruchtvlees en suiker",
      ["Een heldere cocktail die goed gekoeld is", "Een geclarificeerde cocktail uit de koelkast", "Een gekoelde, gezeefde highball-basis"],
      "Pulp en veel suiker laten de sifon overschuimen."),
    q("Hoe voeg je rook toe volgens de les?", "Via de neus: een paar seconden onder een cloche of omgekeerd glas",
      ["Via de vloeistof: minuten roken tot hij naar rook smaakt", "Met een rokerige siroop die je door de cocktail roert", "Via ijsblokjes die je vooraf boven houtsnippers hebt gerookt"],
      "Seconden, geen minuten."),
    q("Waarom begon de cursus volgens deze les met glaswerk?", "Presentatie is een structureel onderdeel van de ervaring",
      ["Glaswerk is het goedkoopste onderdeel van een thuisbar", "Glaswerk is het makkelijkste onderwerp om mee te beginnen", "Het glas bepaalt hoeveel alcohol je per cocktail schenkt"],
      "Beeld en geur zijn het eerste contact, nog vóór de smaak."),
    q("Wat lossen rook, carbonatie en clarificatie op volgens de pro-tip?", "Niets wat een goed gebalanceerd recept niet al oploste",
      ["Een onbalans tussen zoet en zuur die je anders niet recht krijgt", "Te weinig verdunning door te kort schudden of roeren", "Een cocktail die te sterk is voor de meeste gasten"],
      "Eerst balans, dan pas theater."),
  ],
};

// Eindtoets: 5 vragen per deel, geïntegreerd en met rekenwerk; niet
// dezelfde vragen als in de lessen.
export const FINAL_EXAM_QUESTIONS = [
  // Deel I
  q("Wat hebben een Manhattan en een Sazerac met de definitie uit 1806 te maken?", "Beide zijn varianten op sterkedrank, suiker, water en bitters",
    ["Beide zijn eigenlijk punches waarvan de citrus is weggelaten", "Beide zijn ontstaan tijdens de drooglegging in Parijs en Havana", "Beide stammen uit de tiki-traditie van Donn Beach"],
    "Wie de vierdelige formule kent, herkent de familie."),
  q("Je bedient 8 gasten die elk 3 cocktails drinken. Hoeveel ijs heb je nodig?", "Ongeveer 3,6 kg",
    ["Ongeveer 1,2 kg", "Ongeveer 2,4 kg", "Ongeveer 8 kg"],
    "24 cocktails × 150 g = 3,6 kg."),
  q("Welke combinatie is functioneel het minst logisch?", "Een Mojito met crushed ijs in een coupe",
    ["Een Daiquiri up in een coupe", "Een Old Fashioned op een groot blok in een rocks-glas", "Een champagnecocktail in een flute"],
    "Een coupe is voor cocktails zonder ijs."),
  q("Je schenkt een sour (60 ml sterk, 25 ml zuur, 20 ml zoet) vrijhandig en het zoet komt 20% te hoog uit. Wat proef je?", "Een merkbaar te zoete, platte sour",
    ["Geen verschil, 4 ml maakt niets uit", "Een zuurdere sour", "Een sterkere sour"],
    "24 ml zoet tegen 25 ml zuur verschuift de balans duidelijk."),
  q("Een Clover Club met eiwit wordt up geserveerd. Welke zeven gebruik je?", "Hawthorne-zeef plus fijne zeef (dubbel zeven)",
    ["Alleen de julep-zeef, want die is fijner", "Geen zeef: het schuim moet er helemaal in", "Alleen de fijne zeef, zonder hawthorne"],
    "Geschud en up: dubbel zeven."),
  // Deel II
  q("Welke bewering over bourbon klopt NIET?", "Bourbon moet uit Kentucky komen",
    ["Bourbon bevat minstens 51% maïs", "Bourbon rijpt op nieuwe, verkoolde eikenvaten", "Bourbon is doorgaans zoet en rond"],
    "Bourbon mag overal in de VS gemaakt worden; Kentucky is een misvatting."),
  q("Je hebt geen falernum. Welke smaken moet een vervanger ongeveer hebben?", "Limoen, gember, amandel en kruidnagel",
    ["Amandel en oranjebloesemwater", "Honing, gember en citroen", "Vanille, anijs en kaneel"],
    "Amandel met oranjebloesem is orgeat."),
  q("Welke geopende fles verliest het snelst aan kwaliteit?", "Droge vermout",
    ["Campari", "Angostura bitters", "London Dry gin"],
    "Vermout is wijn en oxideert; de rest is sterk genoeg om stabiel te blijven."),
  q("Welke garnering heeft een smaakfunctie en niet alleen een aromafunctie?", "Een olijf in een Dirty Martini",
    ["Een uitgeknepen citroentwist", "Een parasolletje met kersen", "Een ananasblad op de rand"],
    "De twist werkt via de neus; de olijf voegt een zoute noot toe aan de smaak."),
  q("Waarom smaakt een sour met limoensap uit een fles platter, ook als de verhouding klopt?", "De vluchtige aromatische oliën ontbreken",
    ["Flessensap bevat nauwelijks zuur", "Flessensap is geconcentreerd en dus te sterk", "Flessensap laat het ijs sneller smelten"],
    "De verhouding klopt, de aroma's niet."),
  // Deel III
  q("Recept: 50 ml gin, 25 ml citroen, 20 ml siroop en een eiwit. Wat is de juiste bereiding?", "Dry shake, dan met ijs schudden, dan dubbel zeven in een coupe",
    ["Roeren met ijs in een mengglas en zeven in een coupe", "Bouwen op ijs in een highball en kort doorroeren", "Alleen 30 seconden met ijs schudden en ongezeefd serveren"],
    "Eiwit vraagt om een dry shake; geschud en up vraagt om dubbel zeven."),
  q("Je batcht 12 Manhattans van 60 ml rye en 30 ml vermout. Hoeveel drank en water bij 20% verdunning?", "1080 ml drank en ongeveer 215 ml water",
    ["1080 ml drank en 1080 ml water", "720 ml drank en ongeveer 145 ml water", "1080 ml drank en ongeveer 50 ml water"],
    "12 × 90 = 1080 ml; 20% daarvan ≈ 216 ml."),
  q("Een sour met 50 ml bourbon volgens 2 : ¾ : ¾. Hoeveel citrus?", "Ongeveer 19 ml",
    ["Ongeveer 25 ml", "Ongeveer 12 ml", "Ongeveer 38 ml"],
    "50 ÷ 2 × ¾ ≈ 19 ml."),
  q("Welke drank heeft het meeste baat bij swizzelen?", "Een Chartreuse Swizzle met crushed ijs",
    ["Een Martini, geroerd en up", "Een Espresso Martini met schuim", "Een Irish Coffee met room"],
    "Swizzelen is voor crushed-ice-cocktails."),
  q("Na 15 seconden hard schudden schud je nog 30 seconden door. Wat is het resultaat?", "Vooral extra water, en nauwelijks kouder",
    ["Veel kouder, en daardoor ook sterker", "Meer schuim bij dezelfde verdunning", "Warmer door de wrijving van het ijs"],
    "De koelcapaciteit is dan al grotendeels op."),
  // Deel IV
  q("Een sour smaakt dun en trekt je wangen samen. Wat doe je?", "Een klein beetje siroop erbij en opnieuw proeven",
    ["Meer citroen erbij, voor meer frisheid", "Langer shaken voor meer verdunning", "Een sterkere drank als basis kiezen"],
    "Te zuur vraagt om iets meer zoet, in kleine stappen."),
  q("Een gast vindt je nieuwe cocktail \"plat\". Welke aanpassing past het best bij de lessen?", "Een tegenwicht toevoegen, bijvoorbeeld een bittere noot of een paar korrels zout",
    ["Meer van hetzelfde zoete ingrediënt toevoegen", "Vijf nieuwe ingrediënten tegelijk proberen", "De cocktail langer laten staan voor meer smaak"],
    "Plat betekent vaak: geen tegenwicht."),
  q("Je drankje is te bitter. Wat helpt zonder dat het zwaar en zoet wordt?", "Een paar korrels zout",
    ["Een flinke scheut suikersiroop", "Meer van de bittere likeur", "Een andere garnering"],
    "Zout verzacht bitter; suiker maakt het snel plakkerig."),
  q("Je maakt een twist op een Margarita. Wat is de beste aanpak?", "Eén onderdeel wisselen, proeven en opschrijven wat je deed",
    ["Alles tegelijk vervangen, dan is het echt nieuw", "Twee extra likeuren toevoegen voor diepte", "De verhoudingen omdraaien: meer limoen dan tequila"],
    "Eén wissel tegelijk, zodat je weet wat het verschil maakt."),
  q("Een menu van vijf cocktails voor twintig gasten. Wat past bij de lessen?", "Fris, sterk en zacht, één alcoholvrije optie en minstens één cocktail die je vooraf klaarzet",
    ["Vijf sours, omdat die snel en voor iedereen lekker zijn", "Vijf sterke cocktails, omdat die allemaal vooraf kunnen", "Alleen wat jij zelf het lekkerst vindt, met één alcoholvrije"],
    "Iets voor iedereen, en werkbaar voor jou."),
  // Deel V
  q("Wat kun je NIET goed de dag van tevoren doen?", "Limoensap persen",
    ["Suikersiroop maken", "Glazen per type klaarzetten", "Kaneelstokjes klaarleggen"],
    "Citrussap verliest binnen 24 uur merkbaar aan frisheid."),
  q("30 gasten, een feest van 4 uur. Hoeveel drankjes en ijs heb je nodig?", "Ongeveer 150 drankjes en 22,5 kg ijs",
    ["Ongeveer 120 drankjes en 18 kg ijs", "Ongeveer 90 drankjes en 13,5 kg ijs", "Ongeveer 240 drankjes en 36 kg ijs"],
    "Per gast 2 + 1 + 1 + 1 = 5 → 150 drankjes × 150 g = 22,5 kg."),
  q("Welke taakverdeling helpt het meest bij een groot feest?", "Eén persoon schenkt, een ander garneert en serveert",
    ["Iedereen maakt zijn eigen cocktail met jouw uitleg", "Eén persoon doet alles, dat voorkomt verwarring", "Gasten wachten tot een hele ronde tegelijk klaar is"],
    "Eén persoon voor alles is een gegarandeerde bottleneck."),
  q("Welke volgorde hoort bij een signature cocktail?", "Idee → familie en basisspirit → kernformule → finesse → naam en verhaal → vastleggen",
    ["Naam → garnering → ingrediënten → idee → kernformule → vastleggen", "Finesse → kernformule → idee → familie → naam → vastleggen", "Duurste fles → vijf ingrediënten → naam → verhaal → proeven"],
    "Het idee stuurt; de finesse komt pas na een werkende kern."),
  q("Waarom verpest ijstekort volgens de lessen elke volgende ronde?", "Je gaat ijs hergebruiken of zuinig doen, waardoor elke ronde sneller verwatert",
    ["Minder ijs maakt cocktails sterker, en dat valt bij gasten juist in de smaak", "Het glas kan knappen als je te weinig ijs gebruikt voor warme dranken", "Hergebruikt ijs maakt de volgende drank zoeter door suikerresten"],
    "Reken ruim: 150 g per drankje."),
  // Deel VI
  q("Wat trekt langer: steranijs of verse tijm?", "Steranijs: dagen tot weken; tijm: uren",
    ["Tijm: dagen tot weken; steranijs: uren", "Beide ongeveer precies 24 uur", "Beide een aantal weken"],
    "Harde, houtige ingrediënten trekken langzaam; delicate kruiden snel."),
  q("Wat betekenen de vetsporen die na fat-washing achterblijven?", "Het eindproduct moet gekoeld worden en binnen weken op",
    ["Het wordt daardoor juist onbeperkt houdbaar", "Het blijft troebel, maar is wel langer houdbaar", "Het kan daarna niet meer in de vriezer"],
    "Vet wordt sneller ranzig dan pure alcohol."),
  q("Je wilt clarificeren en de smaak zo dicht mogelijk bij het origineel houden. Welke methode?", "Agar",
    ["Melk", "Beide geven exact dezelfde smaak", "Geen van beide: alleen filteren"],
    "Melk-clarificatie maakt zachter en minder zuur."),
  q("Welke combinatie werkt het best bij carboneren?", "Een heldere, ijskoude cocktail; sifon voor twee derde gevuld",
    ["Een warme, troebele cocktail in een helemaal gevulde sifon", "Een pulpige sour op kamertemperatuur, sifon half gevuld", "Een roomcocktail met ijsblokjes erin, sifon tot de rand"],
    "Koud lost meer CO2 op en schuimt minder."),
  q("Hoe maak je een matige cocktail beter?", "Eerst de balans op orde brengen, pas daarna technieken inzetten",
    ["Er een paar seconden rook overheen blazen onder een cloche", "Hem clarificeren, zodat hij zachter en ronder wordt", "Hem carboneren, zodat hij frisser en levendiger smaakt"],
    "Geavanceerde technieken redden geen slecht recept."),
];
