// "Van Basis tot Pro", de Thuisbar-cursus, in-app versie.
// Volledig eigen geschreven lesprogramma (zie ook de PDF-versie), gebaseerd op
// algemene, vakgebied-brede bartending-kennis; geen enkel onderdeel is
// overgenomen uit een bestaand boek of bestaande cursus.
//
// Elk lesson-object: { id, part, number, title, intro, blocks[], takeaways[], quiz[] }
// blocks: { type: "p" } | { type: "h3", text } | { type: "box", kind, label, text } | { type: "table", headers, rows }
// quiz: { q, options[4], correct (index), explain } — zie courseQuiz.js

import { LESSON_QUIZZES, FINAL_EXAM_QUESTIONS } from "./courseQuiz.js";

export const COURSE_PARTS = [
  { id: "fundamenten", title: "Fundamenten", subtitle: "Deel I" },
  { id: "ingredienten", title: "De ingrediënten", subtitle: "Deel II" },
  { id: "techniek", title: "Techniek", subtitle: "Deel III" },
  { id: "smaak", title: "Smaak & compositie", subtitle: "Deel IV" },
  { id: "vak", title: "Het vak van bartender", subtitle: "Deel V" },
  { id: "geavanceerd", title: "Geavanceerde technieken", subtitle: "Deel VI" },
];

export const COURSE_LESSONS = [
  {
    id: "geschiedenis",
    part: "fundamenten",
    number: 1,
    title: "De geschiedenis van de cocktail",
    intro: "Elke cocktail die je ooit zult maken staat in een lijn die terugloopt tot scheepsartsen, apothekers en barmannen die problemen oplosten, niet tot mensen die simpelweg lekkere drankjes wilden bedenken.",
    blocks: [
      { type: "h3", text: "Vóór de cocktail: punch en medicinale mengsels" },
      { type: "p", text: "Lang voordat het woord \"cocktail\" bestond, mengden zeevarende naties al drank met andere ingrediënten. De punch, vermoedelijk vernoemd naar het Hindi-woord voor \"vijf\" (pānch) naar de vijf ingrediënten sterkedrank, suiker, citrus, water en specerijen, reisde vanaf de zeventiende eeuw met de Britse Oost-Indische Compagnie mee naar Europa." },
      { type: "p", text: "Citrus en suiker waren geen luxe maar praktische noodzaak: ruwe sterkedrank was scherp om te drinken, en scheurbuik was een reëel gevaar op lange zeereizen. Een scheutje citroen in de dagelijkse rum- of jeneverrantsoen loste twee problemen tegelijk op. Bijna niets in de cocktailgeschiedenis is ooit puur voor de lol bedacht." },
      { type: "h3", text: "1806: het jaar dat het woord een definitie kreeg" },
      { type: "p", text: "Pas in 1806 gaf een Amerikaanse krant, The Balance and Columbian Repository, een expliciete definitie: een cocktail was \"sterkedrank van welke soort dan ook, suiker, water en bitters.\" Dat is, in de kern, nog steeds de Old Fashioned, en alles wat we sindsdien cocktail noemen is een variatie op die vierdelige formule." },
      { type: "p", text: "Zie je die verwantschap, dan wordt de hele cocktailwereld overzichtelijk: een Manhattan is een Old Fashioned met vermout, een Sazerac is een Old Fashioned met een absint-wassing en een eigen bitter. Je leert geen honderden losse recepten, je leert een klein aantal families en hun varianten." },
      { type: "h3", text: "De Gouden Eeuw en de drooglegging" },
      { type: "p", text: "De tweede helft van de negentiende eeuw was de eerste grote bloeiperiode: Jerry Thomas' \"How to Mix Drinks\" (1862) was het eerste echte cocktailboek. Van 1920 tot 1933 verbood de Amerikaanse drooglegging alcohol volledig, een ramp die onbedoeld wereldwijd effect had: duizenden Amerikaanse barmannen verhuisden naar Europa en Cuba, waar bars als Harry's New York Bar en El Floridita uitgroeiden tot broedplaatsen van nieuwe klassiekers." },
      { type: "h3", text: "Tiki, de dip, en de renaissance" },
      { type: "p", text: "Na de oorlog ontstond tiki, een complete fantasiewereld rond Polynesische exotiek, bedacht door pioniers als Donn Beach en Trader Vic. De jaren '70-'80 gelden als dieptepunt (kant-en-klare mixen, verlies van vakmanschap), tot eind jaren '90 een kleine groep bartenders in New York en Londen terugkeerde naar negentiende-eeuwse technieken en verse ingrediënten: de \"craft cocktail-revival\" waar jij nu, met deze cursus, het resultaat van leert." },
      { type: "box", kind: "history", label: "Tijdlijn in het kort", text: "1650-1800 punch · 1806 eerste definitie van \"cocktail\" · 1862 Jerry Thomas' eerste barboek · 1920-1933 drooglegging & de Europese uittocht · jaren '30-'50 tiki-opkomst · jaren '70-'80 kwaliteitsdip · sinds ~2000 craft-cocktailrevival." },
    ],
    takeaways: [
      "De vierdelige formule uit 1806 (sterkedrank, suiker, water, bitters) is de wortel van bijna elke cocktail die je later leert.",
      "Citrus en suiker waren ooit functionele oplossingen, geen smaakgrapjes, dat verklaart waarom balans nog steeds centraal staat.",
      "Cocktailgeschiedenis verloopt in golven van bloei en verval; de stijl die je nu leert is zelf een reactie op een eerdere periode van verval.",
    ],
  },
  {
    id: "uitrusting",
    part: "fundamenten",
    number: 2,
    title: "De bar-uitrusting: jouw gereedschapskist",
    intro: "Je hebt geen dure barwagen nodig om goed te beginnen, maar met de verkeerde tools kost elke stap onnodig veel moeite. Dit is de uitrusting die er echt toe doet.",
    blocks: [
      { type: "h3", text: "De shaker: drie families, één doel" },
      { type: "p", text: "Een shaker mengt, koelt en verdunt ingrediënten met ijs. De Boston shaker (metalen beker + glazen/metalen tin) is de keuze van vrijwel elke professional vanwege snelheid en afdichting. De cobbler shaker (driedelig, met ingebouwde zeef) is prima voor beginners maar lekt sneller en verstopt bij munt of vruchtvlees. De Franse shaker zit er qua vorm tussen in." },
      { type: "h3", text: "De jigger: nauwkeurigheid is geen luxe" },
      { type: "p", text: "Een jigger is een dubbelzijdig maatbekertje. Vrijhandig schenken oogt indrukwekkend maar zelfs ervaren bartenders wijken zonder jigger tot 20% af van hun bedoelde receptuur. Bij een cocktail die op een precieze zoet-zuur-balans steunt, is dat het verschil tussen geweldig en matig." },
      { type: "h3", text: "De bar spoon en zeven" },
      { type: "p", text: "Een bar spoon heeft een lange, gedraaide steel zodat hij soepel tussen je vingers ronddraait tijdens het roeren. De hawthorne-zeef (met veerrand) hoort op een shaker; de julep-zeef hoort op een roerglas; een fijne theezeef gebruik je voor \"dubbel zeven\" bij muntblaadjes of vruchtvlees." },
      { type: "h3", text: "Overige onmisbare stukken" },
      { type: "p", text: "Een muddler (stamper zonder gelakte afwerking) voor kruiden of fruit, een channel knife of dunschiller voor citrusschil, een zwaar mixing glass specifiek voor stirred-down-cocktails, en losse ijsvormen voor grote ijsblokken." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Begin met vier dingen: een Boston-shaker-set, een jigger, een bar spoon en een hawthorne-zeef. Dat dekt letterlijk elk recept in deze cursus." },
    ],
    takeaways: [
      "Een jigger is geen beginnershulpmiddel maar de manier waarop professionals consistent goede cocktails maken.",
      "Elk zeeftype heeft een eigen taak: hawthorne voor shaken, julep voor roeren, fijne zeef voor de laatste polish.",
      "Vier basisstukken dekken vrijwel alles; investeer pas verder als je merkt waar je zelf tegenaan loopt.",
    ],
  },
  {
    id: "glaswerk",
    part: "fundamenten",
    number: 3,
    title: "Glaswerk: de juiste vorm voor het juiste doel",
    intro: "Een glas is geen decoratie: de vorm bepaalt hoe snel een drank opwarmt, hoe aroma je neus bereikt, en hoeveel ijs er logisch in past.",
    blocks: [
      { type: "h3", text: "De coupe en Nick & Nora" },
      { type: "p", text: "De coupe, een ondiepe, brede schaal op een steel, is het glas voor \"up\" geserveerde cocktails zoals een Daiquiri of Martini. De brede opening laat aroma snel vrijkomen. Het Nick & Nora-glas (kleiner, meer gebogen) behoudt de koude langer en wordt door veel moderne bartenders geprefereerd." },
      { type: "h3", text: "Rocks, highball en Collins" },
      { type: "p", text: "Een rocks-glas (kort, dikke bodem) is voor drankjes over ijs, met ruimte om te muddelen zonder te breken. Highball en Collins-glazen zijn hoog en rechte, met genoeg volume voor voldoende koelend ijs bij longdrinks." },
      { type: "h3", text: "Specialistische vormen" },
      { type: "p", text: "Een flute behoudt koolzuurbubbels langer dan een breed glas, essentieel voor champagnecocktails. Een koperen beker bij een Moscow Mule geleidt kou uitzonderlijk goed, waardoor de buitenkant zichtbaar beslaat. Tiki-cocktails krijgen vaak thematische bekers, puur voor de theatrale traditie van dat genre." },
      { type: "table", headers: ["Glas", "Gebruik voor", "Waarom"], rows: [
        ["Coupe / Nick&Nora", "\"Up\" cocktails zonder ijs", "Aroma vrij, geen ijs nodig na schudden/roeren"],
        ["Rocks", "On-the-rocks, muddled", "Stevige bodem, ruimte voor groot ijsblok"],
        ["Highball/Collins", "Longdrinks", "Volume voor voldoende koelend ijs"],
        ["Flute", "Champagnecocktails", "Behoudt koolzuur"],
      ] },
    ],
    takeaways: [
      "Glasvorm bepaalt aroma-afgifte, opwarmsnelheid én hoeveelheid ijs. Het is functioneel, niet decoratief.",
      "\"Up\" cocktails zijn al gekoeld vóór het inschenken; longdrinks hebben juist volume nodig om zelf koud te blijven.",
      "Een set van 4 (coupe, rocks, highball, wijnglas) dekt vrijwel elk recept.",
    ],
  },
  {
    id: "ijs",
    part: "fundamenten",
    number: 4,
    title: "IJs: de onderschatte hoofdingrediënt",
    intro: "Beginnende thuisbartenders behandelen ijs als bijzaak. Professionals behandelen het als een ingrediënt met een eigen receptuur.",
    blocks: [
      { type: "h3", text: "Waarom verdunning geen fout is" },
      { type: "p", text: "Een cocktail zonder verdunning smaakt onaangenaam geconcentreerd. Tijdens shaken of roeren smelt bewust 20-30% van het ijs mee in de drank; die waterlaag \"opent\" de smaken en houdt alcohol, zuur en zoet in balans. Dit is waarom bartenders een exacte schud- of roertijd aanhouden in plaats van \"tot het koud aanvoelt.\"" },
      { type: "h3", text: "IJsvormen en hun functie" },
      { type: "p", text: "Standaard kubusijs is het werkpaard voor shaken en de meeste longdrinks. Groot-formaat ijs (één blok van 4-5 cm) smelt trager en is de standaard voor Old Fashioned-achtige drankjes: langer goed gekoeld zonder snel waterig te worden. Crushed ijs smelt juist razendsnel en wordt bewust gebruikt bij Mojito's, Juleps en tiki-cocktails voor een intense, snelle verdunning." },
      { type: "h3", text: "Praktische vuistregel" },
      { type: "p", text: "Reken op ongeveer 150 gram ijs per geserveerde cocktail. Dit dekt zowel het ijs in de shaker als het ijs waarover je serveert. Kom je ijs tekort tijdens een feest, dan verwatert elke volgende ronde merkbaar sneller." },
      { type: "box", kind: "warning", label: "Veelgemaakte fout", text: "IJs hergebruiken dat al in een glas heeft gezeten. Dat ijs is al deels gesmolten en verdund met de vorige drank. Gebruik voor elke stap vers ijs." },
    ],
    takeaways: [
      "Verdunning door ijs is een opzettelijk onderdeel van de receptuur, niet een neveneffect om te minimaliseren.",
      "Grof ijs = trage verdunning (Old Fashioned-stijl), fijn/crushed ijs = snelle verdunning (Mojito/tiki-stijl).",
      "Reken ruim: te weinig ijs tijdens een feest verpest elke volgende ronde.",
    ],
  },

  {
    id: "gedistilleerd",
    part: "ingredienten",
    number: 5,
    title: "Gedistilleerde dranken: de basis van elke cocktail",
    intro: "Vrijwel elke cocktail heeft een basisspirit. Ken je de hoofdcategorieën, dan kun je bij elk nieuw recept meteen inschatten wat je gaat proeven.",
    blocks: [
      { type: "h3", text: "Hoe distilleren werkt" },
      { type: "p", text: "Alle gedistilleerde drank begint als een gegist mengsel met een laag alcoholpercentage. Distilleren verhit dat mengsel tot het punt waarop alcohol verdampt (bij een lagere temperatuur dan water), waarna die damp wordt opgevangen en weer vloeibaar gemaakt: een geconcentreerd eindproduct. Basismateriaal en rijping bepalen samen de categorie en het smaakprofiel." },
      { type: "h3", text: "Whiskey: graan, rijping en regels" },
      { type: "p", text: "Bourbon moet voor minstens 51% uit maïs bestaan en rijpen in nieuwe, verkoolde eikenvaten, wat 'm zoet en rond maakt. Rye gebruikt overwegend rogge en levert een drogere, pittigere whiskey, de klassieke basis voor Manhattan en Sazerac. Scotch (Islay-stijl) heeft vaak een rokerige noot; Irish whiskey is doorgaans zachter en driemaal gedistilleerd." },
      { type: "h3", text: "Gin, rum en agave-dranken" },
      { type: "p", text: "Gin is neutrale alcohol herdistilleerd met jeneverbessen en andere botanicals. Witte rum is licht en ideaal voor Daiquiri's; donkere/gerijpte rum brengt karamel- en houttonen voor tiki. Tequila (alleen blauwe agave, industrieel gestoomd) en mezcal (diverse agavesoorten, traditioneel geroosterd in ondergrondse ovens) zijn twee compleet verschillende productiefilosofieën. Mezcal is geen \"sterkere tequila.\"" },
      { type: "h3", text: "Wodka en cognac" },
      { type: "p", text: "Wodka wordt bewust zo neutraal mogelijk gedistilleerd: een drager voor andere smaken, geen tekortkoming. Cognac is gedistilleerde druivenwijn uit een beschermde Franse regio; vóór de druifluis phylloxera eind negentiende eeuw was cognac zelfs de dominante cocktailbasis in Amerika, wat verklaart waarom sommige negentiende-eeuwse klassiekers ooit met cognac werden gemaakt." },
      { type: "table", headers: ["Categorie", "Basismateriaal", "Karakter"], rows: [
        ["Bourbon / Rye", "Maïs / rogge", "Zoet-rond / droog-kruidig"],
        ["Gin", "Graanalcohol + botanicals", "Kruidig, jeneverbes"],
        ["Witte / donkere rum", "Suikerriet / melasse", "Licht-fris / karamel"],
        ["Tequila / Mezcal", "Blauwe agave / diverse agave", "Plantaardig / rokerig"],
        ["Wodka", "Graan / aardappel", "Neutraal"],
      ] },
    ],
    takeaways: [
      "Basismateriaal + rijping bepalen samen de smaakcategorie. Ken je die logica, dan kun je nieuwe dranken al deels inschatten.",
      "Tequila en mezcal zijn geen \"sterk/zwak\"-paar maar twee verschillende productiefilosofieën.",
      "Wodka's neutraliteit is functioneel: het is een drager voor andere smaken, geen smaakloos gebrek.",
    ],
  },
  {
    id: "likeuren-bitters",
    part: "ingredienten",
    number: 6,
    title: "Versterkte wijnen, likeuren en bitters",
    intro: "Als sterkedrank de ruggengraat van een cocktail is, zijn deze drie categorieën het zenuwstelsel: ze sturen de smaak subtiel bij en voegen complexiteit toe.",
    blocks: [
      { type: "h3", text: "Vermout: de meest onderschatte fles in huis" },
      { type: "p", text: "Vermout is wijn versterkt met extra alcohol en op smaak gebracht met kruiden. Droge vermout is licht en kruidig (essentieel voor een Martini); zoete vermout is voller en zoeter (de ruggengraat van een Manhattan of Negroni). Cruciaal detail: vermout is wijn, geen sterkedrank. Eenmaal geopend oxideert het en verliest het binnen weken (gekoeld bewaard) merkbaar aan frisheid." },
      { type: "h3", text: "Amari en kloosterlikeuren" },
      { type: "p", text: "\"Amaro\" is een Italiaanse verzamelnaam voor bittere kruidenlikeuren. Campari is bitterder en dieper rood; Aperol lichter en zoeter. Chartreuse (groen en geel) wordt sinds de zeventiende eeuw gedistilleerd door kartuizer monniken volgens een receptuur met meer dan honderd kruiden, tot vandaag slechts bij twee monniken tegelijk bekend." },
      { type: "h3", text: "Bitters: het zout-en-peper van de cocktailwereld" },
      { type: "p", text: "Bitters zijn zeer geconcentreerde tincturen, gebruikt in \"dashes\" (een paar druppels), niet in millilitersvolumes. Angostura (kruidig, kaneelachtig) en Peychaud's (lichter, anijsachtig) zijn de bekendste. Net als zout in koken benadrukken bitters andere smaken in plaats van zelf te overheersen." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Bewaar alle versterkte wijnen (vermout, sherry, port) na opening in de koelkast, en vervang ze elke 4-6 weken als je ze regelmatig gebruikt: de meest impactvolle, goedkoopste verbetering die je kunt doorvoeren." },
    ],
    takeaways: [
      "Vermout is wijn, geen sterkedrank: behandel het (koeling, houdbaarheid) dienovereenkomstig.",
      "Amari en bitters spelen dezelfde rol als zout in koken: ze scherpen andere smaken aan in plaats van zelf te overheersen.",
      "Kleine hoeveelheden (dashes, een paar ml likeur) hebben vaak een onevenredig grote invloed op het eindresultaat.",
    ],
  },
  {
    id: "vers",
    part: "ingredienten",
    number: 7,
    title: "Vers: citrus, siropen en zuivel",
    intro: "Dit zijn de ingrediënten die je zelf het meest controleert, en waar de meeste winst te behalen valt tussen een matige en een uitstekende cocktail.",
    blocks: [
      { type: "h3", text: "Citrus: altijd vers, altijd op tijd geperst" },
      { type: "p", text: "Vers citroen- of limoensap oxideert binnen enkele uren merkbaar en mist bovendien de vluchtige aromatische oliën die net-geperst sap wél heeft. De vuistregel: pers citrus dezelfde dag, idealiter binnen een paar uur voor gebruik. Dit is, meer dan enige andere regel, de reden waarom professioneel gemaakte sours zo anders smaken dan een thuisversie met flessensap." },
      { type: "h3", text: "Suikersiroop en specialistische siropen" },
      { type: "p", text: "Gewone kristalsuiker lost niet goed op in koude, geshakete cocktails. Suikersiroop (gelijke delen suiker en water) lost direct en volledig op. Orgeat (amandelsiroop met oranjebloesemwater) en falernum (limoen, gember, amandel, kruidnagel) zijn tiki-signatuursiropen met een eigen, herkenbaar smaakprofiel, geen simpele zoetmakers." },
      { type: "h3", text: "Eiwit en zuivel" },
      { type: "p", text: "Eiwit geeft textuur, geen smaak: het vereist een \"dry shake\" (eerst hard schudden zonder ijs om te emulgeren) vóór het gewone shaken met ijs. Sla je die stap over, dan krijg je een dunnere schuimlaag. Room en roomlikeuren geven dessertcocktails hun volle textuur, maar zijn gevoeliger en vragen om vers, gekoeld gebruik." },
      { type: "box", kind: "warning", label: "Veelgemaakte fout", text: "Suikersiroop of citrussap dagen van tevoren klaarmaken om tijd te besparen. Citrussap verliest binnen 24 uur al merkbaar aan frisheid. Maak het zo dicht mogelijk bij het moment van serveren." },
    ],
    takeaways: [
      "Vers citrussap is misschien wel de grootste kwaliteitssprong die je kunt maken, belangrijker dan een duur flesje sterkedrank.",
      "Suikersiroop lost op waar kristalsuiker dat niet doet: een simpel, essentieel technisch detail.",
      "Eiwit is een textuur-ingrediënt: de dry shake is niet optioneel als je het gewenste schuimeffect wilt.",
    ],
  },
  {
    id: "garnering",
    part: "ingredienten",
    number: 8,
    title: "Garnering: functie boven decoratie",
    intro: "Een garnering die alleen maar mooi oogt maar niets aan smaak of aroma toevoegt, is een gemiste kans. De beste garneringen doen minstens één functioneel ding.",
    blocks: [
      { type: "h3", text: "De citrustwist: aroma, geen smaak" },
      { type: "p", text: "Een schil sinaasappel of citroen die je boven de cocktail uitknijpt, verspreidt een wolkje aromatische oliën direct over het drankoppervlak, de eerste geur die je ruikt bij elke slok. Dezelfde cocktail met en zonder deze twist proeft merkbaar anders, ook al verandert er niets aan de vloeistof zelf." },
      { type: "h3", text: "Munt, olijven en zilveruitjes" },
      { type: "p", text: "Munt werkt het best als je de blaadjes eerst tussen je handen klapt (een korte, stevige klap) om aroma te activeren zonder ze te beschadigen: beschadigde munt oxideert en wordt bitter. Olijven en zilveruitjes bij een Dirty Martini of Gibson voegen een zoute, hartige noot toe: een bewust contrast, geen versiering." },
      { type: "h3", text: "De tiki-traditie: sfeer als doel op zich" },
      { type: "p", text: "In tiki-cocktails is garnering vaak bewust overdreven (parasolletjes, ananasstukken, meerdere kersen) als onderdeel van de theatrale, op beleving gerichte traditie van dat genre. Hier is het effect grotendeels sfeer, niet smaak, en dat is prima zolang je weet welk doel een garnering dient." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Vraag jezelf bij elke garnering af: voegt dit aroma, smaak of temperatuur toe, of is het puur sfeer? Beide zijn legitiem, maar een bewuste keuze levert altijd een overtuigender resultaat." },
    ],
    takeaways: [
      "De beste garneringen hebben een functie: aroma (twist), smaakaccent (olijf) of sfeer (tiki-decor).",
      "Een citrustwist verandert de geur, en dus de beleving, van een cocktail zonder de vloeistof zelf aan te passen.",
      "Klap munt, plet het niet: beschadigde blaadjes oxideren en worden bitter.",
    ],
  },

  {
    id: "basistechnieken",
    part: "techniek",
    number: 9,
    title: "De zes basistechnieken",
    intro: "Elke cocktail ter wereld wordt gemaakt met een combinatie van een handvol basistechnieken. Beheers deze zes, en je kunt in principe elk recept uitvoeren.",
    blocks: [
      { type: "h3", text: "Shaken en dry shake" },
      { type: "p", text: "Shaken gebruik je voor cocktails met troebele ingrediënten (sap, eiwit, room) die grondig gemengd én sterk gekoeld moeten worden: vul voor twee derde met ijs, schud kort en hard (10-15 sec). Bij eiwit- of roomcocktails schud je eerst zonder ijs (dry shake, 15-20 sec) om te emulgeren, dan pas met ijs verder." },
      { type: "technique-demo", technique: "shaken" },
      { type: "h3", text: "Stirren en bouwen" },
      { type: "p", text: "Stirren gebruik je voor cocktails die uitsluitend uit heldere, alcoholische ingrediënten bestaan (Martini, Manhattan, Negroni): je wilt koelen en verdunnen zonder lucht erin te kloppen. Bouwen is de simpelste techniek: ingrediënten direct in het glas, over ijs, eventueel kort roeren, voor longdrinks als een Gin Tonic." },
      { type: "technique-demo", technique: "stirred" },
      { type: "h3", text: "Muddelen en swizzelen" },
      { type: "p", text: "Muddelen kneust kruiden of fruit om aroma en sap vrij te maken vóór de rest van de bereiding. Swizzelen is een Caribische techniek voor crushed-ice-cocktails: een swizzle stick wordt snel tussen de handpalmen gedraaid tot het glas van buiten beslaat, voor een zeer koude, licht verdunde drank." },
      { type: "technique-demo", technique: "muddle" },
      { type: "table", headers: ["Techniek", "Gebruik bij", "Waarom"], rows: [
        ["Shaken", "Sap, eiwit, room, siroop", "Grondig mengen + snel koelen"],
        ["Dry shake", "Eiwit-/roomcocktails", "Emulgeren vóór het ijs"],
        ["Stirren", "Alleen heldere ingrediënten", "Koelen zonder troebelheid"],
        ["Bouwen", "Longdrinks", "Geen extra menging nodig"],
        ["Muddelen", "Kruiden, fruit", "Aroma en sap vrijmaken"],
        ["Swizzelen", "Crushed-ice-cocktails", "Snel, intens koelen"],
      ] },
    ],
    takeaways: [
      "De keuze tussen shaken en stirren hangt af van of er troebele ingrediënten in zitten, niet van persoonlijke voorkeur.",
      "Kort en hard schudden geeft betere resultaten dan lang en zacht.",
      "Elke techniek bestaat om een specifiek probleem op te lossen. Ken je het probleem, dan onthoud je de techniek vanzelf.",
    ],
  },
  {
    id: "verdunning-temperatuur",
    part: "techniek",
    number: 10,
    title: "De wetenschap van verdunning en temperatuur",
    intro: "Waarom smaakt dezelfde cocktail soms anders, ook al gebruik je exact dezelfde ingrediënten? Het antwoord zit bijna altijd in verdunning en temperatuur.",
    blocks: [
      { type: "h3", text: "De drie variabelen die je controleert" },
      { type: "p", text: "Bij elke shake- of roerbeweging speel je met tijd, ijshoeveelheid en beweging. Meer tijd of hardere beweging betekent meer verdunning én een lagere temperatuur, tot een bepaald punt, waarna extra tijd vooral extra water toevoegt zonder nog merkbaar kouder te worden." },
      { type: "h3", text: "Waarom \"tot het koud aanvoelt\" geen goede maatstaf is" },
      { type: "p", text: "Het shakerglas voelt binnen seconden koud aan door geleiding, ruim voordat de vloeistof erin de gewenste temperatuur en verdunning heeft bereikt. Vertrouw op tijd (10-15 sec hard schudden, 20-30 sec rustig roeren) in plaats van op het gevoel van de buitenkant." },
      { type: "h3", text: "Voorkoelen van het glas" },
      { type: "p", text: "Een cocktail geserveerd in een glas op kamertemperatuur verliest onmiddellijk koeling aan het glas zelf. Zet glazen voor \"up\" cocktails een paar minuten in de vriezer of vul ze met ijswater tijdens het maken, en giet het water er pas vlak vóór het inschenken uit." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Twijfel je of een cocktail al genoeg verdund is? Proef een klein slokje direct uit de shaker vóór je zeeft. Met oefening leer je binnen een paar pogingen exact aanvoelen wanneer een drank \"af\" is." },
    ],
    takeaways: [
      "Verdunning en temperatuur zijn twee kanten van dezelfde medaille, bepaald door tijd, ijshoeveelheid en beweging.",
      "Vertrouw op tijd, niet op hoe koud de buitenkant van je shaker aanvoelt.",
      "Voorkoelen van het glas is een kleine moeite met een merkbaar effect op de drinktemperatuur.",
    ],
  },
  {
    id: "sour-formule",
    part: "techniek",
    number: 11,
    title: "De sour-formule: zoet, zuur en sterk in balans",
    intro: "Vrijwel elke \"sour\"-stijl cocktail volgt exact dezelfde onderliggende wiskunde. Begrijp deze formule, en je kunt oneindig veel varianten zelf bedenken.",
    blocks: [
      { type: "h3", text: "De klassieke verhouding" },
      { type: "p", text: "De basisformule is: 2 delen sterkedrank, 3/4 deel zuur (vers citrus), 3/4 deel zoet (suikersiroop of een zoete likeur). Vertaald: ongeveer 60 ml sterkedrank, 22-25 ml citrus, 20-25 ml zoet. Deze verhouding zie je terug in vrijwel elke sour, soms met kleine aanpassingen per specifieke drank." },
      { type: "h3", text: "Waarom deze verhouding werkt" },
      { type: "p", text: "Zuur en zoet in bijna-gelijke hoeveelheden neutraliseren elkaars extremen: puur citrussap is te scherp, puur suikersiroop te plakkerig-zoet, maar samen ontstaat een gebalanceerde smaak die de sterkedrank ondersteunt in plaats van overschreeuwt. De sterkedrank blijft in volume de grootste component." },
      { type: "h3", text: "Bijstellen op basis van je ingrediënten" },
      { type: "p", text: "Niet elk zuur en elk zoet is even sterk: limoensap is scherper dan citroensap, honingsiroop intenser dan neutrale suikersiroop, en een zoete likeur (zoals triple sec in een Margarita) telt deels mee als \"zoet\"-element. Proef altijd tijdens het maken en stel desnoods een paar milliliter bij." },
      { type: "table", headers: ["Onderdeel", "Richtlijn", "Voorbeeld"], rows: [
        ["Sterkedrank", "~60 ml", "Bourbon, witte rum, tequila"],
        ["Zuur", "~22-25 ml", "Vers citroen- of limoensap"],
        ["Zoet", "~20-25 ml", "Suikersiroop of zoete likeur"],
      ] },
    ],
    takeaways: [
      "De sour-formule (2:3/4:3/4) is de meest herbruikbare vuistregel in de hele cocktailwereld.",
      "Zuur en zoet neutraliseren elkaars extremen; samen creëren ze balans die los niet werkt.",
      "Proef en stel bij: de formule is een startpunt, geen absolute wet.",
    ],
  },
  {
    id: "finesse",
    part: "techniek",
    number: 12,
    title: "Dubbel zeven, laagjes en andere finesse",
    intro: "Dit zijn de technieken die het verschil maken tussen \"correct volgens recept\" en \"professioneel afgewerkt\".",
    blocks: [
      { type: "h3", text: "Dubbel zeven en de drijflaag" },
      { type: "p", text: "Naast de gewone hawthorne-zeef giet je de cocktail óók door een fijne theezeef, om kleine ijssplinters of vruchtvlees op te vangen, onmisbaar bij elke \"up\" geserveerde geshakete cocktail. Een drijflaag (bijvoorbeeld rode wijn boven een whiskeysour) ontstaat door een ingrediënt voorzichtig over de bolle achterkant van een bar spoon te gieten, zodat het door een dichtheidsverschil blijft drijven." },
      { type: "h3", text: "Laagjes-shooters" },
      { type: "p", text: "Bij een cocktail als de B-52 worden meerdere likeuren strak gescheiden in laagjes opgebouwd. De volgorde is cruciaal: begin met de zwaarste (suikerrijkste) likeur onderin, werk naar steeds lichtere likeuren, giet langzaam over de achterkant van een lepel." },
      { type: "h3", text: "De citrus-expressie" },
      { type: "p", text: "Vlak voor het serveren buig je een stukje citrusschil boven het glas zodat de aromatische oliën richting het drankoppervlak spuiten. Deze stap kost drie seconden maar heeft een merkbaar effect op het allereerste dat je ruikt bij het opheffen van het glas." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Oefen de citrus-expressie eerst boven de gootsteen in plaats van boven een net afgemaakte cocktail: de hoek en druk vergen een paar pogingen." },
    ],
    takeaways: [
      "Dubbel zeven is de standaard, niet de uitzondering, voor elke \"up\" geserveerde geshakete cocktail.",
      "Gelaagde effecten draaien om dichtheidsverschil en een langzame, gecontroleerde giettechniek.",
      "De citrus-expressie is een kleine handeling met een onevenredig grote invloed op de eerste indruk.",
    ],
  },

  {
    id: "families",
    part: "smaak",
    number: 13,
    title: "De negen cocktailfamilies",
    intro: "In plaats van honderden losse recepten te onthouden, leer je negen families herkennen. Elke cocktail past vrijwel altijd in (of combineert elementen van) een van deze categorieën.",
    blocks: [
      { type: "h3", text: "De negen families" },
      { type: "p", text: "Sours (sterk-zuur-zoet, zoals Whiskey Sour), highballs (sterk + veel mixer, zoals Gin Tonic), spirit-forward/Old Fashioned-stijl (sterk met suiker/bitters, zoals Negroni), stirred-down/Martini-familie (sterk + vermout, zonder citrus), fizz & flip (sours + koolzuur of ei, zoals Tom Collins), tiki & tropisch (meerdere rums + exotische siropen), moderne klassiekers (na 2000, zoals Paper Plane), zuivel & dessert (room/eidooier, zoals White Russian), en warme cocktails (zoals Irish Coffee)." },
      { type: "box", kind: "history", label: "Waarom dit indelingssysteem werkt", text: "Elke familie lost een ander \"probleem\" op dat teruggaat op de geschiedenis: sours ontstonden om ruwe drank drinkbaar te maken, highballs om drank te strekken en verfrissend te houden, stirred-down-cocktails om puur, sterk karakter te tonen zonder verdunning door sap. Ken je het probleem, dan onthoud je de familie moeiteloos." },
    ],
    takeaways: [
      "Negen families dekken vrijwel de complete cocktailwereld, je hoeft geen honderden losse recepten uit je hoofd te leren.",
      "Elke familie heeft een eigen technische logica (shaken vs. roeren, wel/geen citrus, wel/geen koolzuur).",
      "Een nieuwe cocktail leren gaat sneller zodra je 'm eerst indeelt in een familie.",
    ],
  },
  {
    id: "smaakcombinatie",
    part: "smaak",
    number: 14,
    title: "Smaakcombinatie: hoe klassiekers zijn opgebouwd",
    intro: "Waarom werkt gin met citrus, campari met sinaasappel, mezcal met ananas? Dit hoofdstuk legt de onderliggende principes bloot.",
    blocks: [
      { type: "h3", text: "Complementair versus contrasterend" },
      { type: "p", text: "Complementaire smaken versterken elkaar: citroen en citroenschil-likeur, munt en groene Chartreuse. Dit is de veiligste manier om een cocktail te ontwerpen. Contrasterende smaken creëren juist spanning: bitter tegenover zoet (Campari en sinaasappelsap), rokerig tegenover fruitig (mezcal en ananas), romig tegenover scherp (room en koffie). Contrast houdt een cocktail interessant over meerdere slokken." },
      { type: "h3", text: "Aromatische bruggen en textuurcontrast" },
      { type: "p", text: "Sommige ingrediënten werken als \"brug\" tussen twee smaken die normaal niet vanzelfsprekend samengaan: Angostura bitters bevat bijvoorbeeld noten die zowel bij fruitige als bij houtige sterkedranken passen. Balans gaat ook over textuur: het schuim van eiwit, de prik van koolzuur, de gladheid van room. Een cocktail die zowel qua smaak als textuur precies één ding doet, voelt al snel eendimensionaal aan." },
      { type: "h3", text: "Een klassieker \"lezen\"" },
      { type: "p", text: "Bij de Penicillin vormen honing en gember een warme, complementaire basis, citroen brengt zuur-contrast, en een drijflaag rokerige whisky levert een scherp contrast met de zoete basis eronder. Bijna elke goede klassieker laat zich zo \"uit elkaar halen\" in complementaire en contrasterende elementen." },
    ],
    takeaways: [
      "Complementaire combinaties versterken een thema; contrasterende combinaties creëren spanning. Beide zijn legitieme strategieën.",
      "Sommige ingrediënten (zoals bitters) werken als aromatische brug tussen smaken die anders niet vanzelfsprekend samengaan.",
      "Textuur is een even belangrijke smaakdimensie als zoet/zuur/bitter, en wordt vaak over het hoofd gezien.",
    ],
  },
  {
    id: "ontwerpen",
    part: "smaak",
    number: 15,
    title: "Zelf een cocktail ontwerpen: de bouwstenen-methode",
    intro: "Dit is het moment waarop je van \"recepten volgen\" naar \"recepten bedenken\" gaat: een gestructureerde methode, geen willekeurig experimenteren.",
    blocks: [
      { type: "h3", text: "Stap 1 & 2: familie en basisspirit" },
      { type: "p", text: "Begin niet met een compleet nieuw idee, maar met een van de negen families als startpunt, dat geeft je meteen een werkende structuur. Kies daarna een basisspirit die past bij wat je wilt bereiken: rokerige mezcal vraagt om iets zoets en fruitigs als contrast, kruidige rye combineert van nature met andere kruidige tonen, neutrale wodka geeft je maximale vrijheid." },
      { type: "h3", text: "Stap 3 & 4: kernformule, dan proeven en herhalen" },
      { type: "p", text: "Werk eerst de basisverhouding uit volgens de gekozen familie en proef die simpelste versie eerst. Pas als die basis al lekker is, voeg je een tweede laag toe (een likeur, wat bitters, garnering). Proef kritisch, benoem specifiek wát niet klopt, en pas telkens één variabele tegelijk aan, nooit meerdere tegelijk." },
      { type: "h3", text: "Stap 5: het verhaal" },
      { type: "p", text: "Een cocktail die je aan gasten voorzet, wint bij een kort verhaal of duidelijke identiteit: een goede naam en een zin uitleg verhoogt de waardering van gasten voor exact dezelfde vloeistof in het glas." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Verander bij het bijstellen van een recept telkens in stappen van 5 ml of minder. Grotere sprongen laten je gemakkelijk van \"te weinig\" naar \"te veel\" schieten." },
    ],
    takeaways: [
      "Begin bij een bekende familie-structuur, niet bij een blanco vel, dat voorkomt onbalans van meet af aan.",
      "Bouw eerst een simpele, werkende kernformule op voordat je finesse-lagen toevoegt.",
      "Pas telkens één variabele per keer aan tijdens het proeven, en noteer wat je verandert.",
    ],
  },
  {
    id: "menu",
    part: "smaak",
    number: 16,
    title: "Een menu samenstellen als een pro",
    intro: "Eén goede cocktail maken is één vaardigheid; een compleet, uitgebalanceerd menu voor gasten samenstellen is een andere.",
    blocks: [
      { type: "h3", text: "De smaakmatrix: vier hoeken plus één" },
      { type: "p", text: "De meeste doordachte menu's dekken vier smaakhoeken ongeveer gelijkmatig: fris & verfrissend, sterk & aromatisch, avontuurlijk, en comfort, aangevuld met altijd minstens één volwaardige alcoholvrije optie. Een menu dat op één hoek leunt voelt al snel eendimensionaal voor een gemengd gezelschap." },
      { type: "h3", text: "Hoeveel opties en batchbaarheid" },
      { type: "p", text: "Een bar biedt 10-12 cocktails voor een breed publiek; voor een housefeest zijn 3-6 goed gekozen opties ruim genoeg. Gestirde cocktails zonder vers sap, eiwit of zuivel kun je uren van tevoren mixen (zonder ijs) en gekoeld bewaren. Kies bewust minstens één of twee batchbare opties zodat je tijdens het feest niet overbelast raakt." },
      { type: "h3", text: "Pour cost en gedeelde ingrediënten" },
      { type: "p", text: "Professionele bars rekenen met \"pour cost\" (kostprijs als percentage van verkoopprijs, doorgaans 18-24%). Voor thuisgebruik: een fles van 700 ml levert bij 45 ml per cocktail ongeveer 15-16 cocktails op. Kies bewust cocktails die ingrediënten delen, dat scheelt inkoopkosten zonder dat het menu minder gevarieerd aanvoelt." },
    ],
    takeaways: [
      "Een uitgebalanceerd menu dekt meerdere smaakhoeken, niet alleen wat de gastheer zelf het lekkerst vindt.",
      "Batchbaarheid is een net zo belangrijke planningsfactor als smaak wanneer je zelf ook van het feest wilt genieten.",
      "Een fles van 700 ml levert ongeveer 15-16 cocktails: een simpele, bruikbare inkoopvuistregel.",
    ],
  },

  {
    id: "mise-en-place",
    part: "vak",
    number: 17,
    title: "Mise en place: voorbereiding is alles",
    intro: "\"Mise en place\", Frans voor \"alles op zijn plek\", is een keukentraditie die professionele bars één op één hebben overgenomen.",
    blocks: [
      { type: "h3", text: "Wat hoort er bij bar-mise en place?" },
      { type: "p", text: "Vóór de eerste gast arriveert: alle benodigde flessen binnen handbereik en in de juiste volgorde, citrus geperst (zo dicht mogelijk bij het moment zelf), siropen klaar, garneringen gesneden en op ijs bewaard, voldoende ijs binnen handbereik, glazen voorgekoeld waar nodig, en een schone werkplek." },
      { type: "h3", text: "Recepten uit je hoofd en een logische werkplek" },
      { type: "p", text: "Voor een feest van meer dan een paar gasten is het onhoudbaar om bij elke cocktail een recept op te zoeken. Oefen je menu vooraf tot je de verhoudingen kent. Een efficiënte bar-opstelling volgt de volgorde van bereiding: sterkedrank het dichtst bij je shaker, dan versterkte wijnen/likeuren, dan bitters, dan verse ingrediënten, met glaswerk en ijs binnen een armlengte." },
      { type: "h3", text: "Wat kan wachten, wat niet" },
      { type: "p", text: "Siropen en de meeste garneringen kunnen uren tot een dag vooraf klaar worden gemaakt en gekoeld bewaard. Citrussap en muntblaadjes juist niet: die verliezen binnen uren aan kwaliteit. Ken dit onderscheid en je voorkomt zowel onnodig laatste-moment-werk als kwaliteitsverlies." },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Maak een checklist per feest met daarop: ijs, glazen per type, te snijden garnering, en welke cocktails je vooraf kunt batchen. Tien minuten planning scheelt uren improviseren." },
    ],
    takeaways: [
      "Mise en place is geen keukenjargon voor bartenders: het is dezelfde discipline, direct toepasbaar aan de bar.",
      "Ken je recepten uit je hoofd voor het menu dat je die avond serveert.",
      "Onderscheid wat vooraf kan (siropen, de meeste garnering) van wat pas op het laatste moment mag (citrussap, munt).",
    ],
  },
  {
    id: "batchen-groepen",
    part: "vak",
    number: 18,
    title: "Batchen en grote groepen bedienen",
    intro: "Zodra je voor meer dan een handvol gasten schenkt, verandert de opgave: je maakt niet langer één cocktail perfect, je maakt tientallen cocktails consistent.",
    blocks: [
      { type: "h3", text: "Wat batchen wél en niet oplost" },
      { type: "p", text: "Batchen (vooraf mengen zonder ijs, gekoeld bewaard tot het serveermoment) bespaart tijd en zorgt voor consistente kwaliteit. Het werkt het best bij gestirde cocktails zonder vers sap, eiwit of zuivel. Cocktails die afhankelijk zijn van net-geshakete textuur verliezen die kwaliteit zodra je ze te vroeg klaarmaakt." },
      { type: "h3", text: "Hoe je een batch berekent" },
      { type: "p", text: "Vermenigvuldig de verhoudingen van je recept met het gewenste aantal porties, en voeg apart een berekende hoeveelheid water toe (doorgaans 20-25% van het totale drankvolume) om het verdunningseffect van ijs te simuleren, aangezien de batch zelf zonder ijs wordt gemengd." },
      { type: "h3", text: "Tempo, ijs-logistiek en taakverdeling" },
      { type: "p", text: "Reken op ongeveer twee drankjes per gast in het eerste uur, daarna gemiddeld één per uur. Reken op 150 gram ijs per cocktail. Bij grote groepen is ijs vaak de eerste bottleneck, niet drank. Bij grotere groepen werkt het beter om taken te splitsen (iemand die schenkt, iemand die garneert en serveert) dan om alles door één persoon te laten doen." },
      { type: "box", kind: "warning", label: "Veelgemaakte fout", text: "Een volledige batch, inclusief de verdunningswater-toevoeging, te vroeg klaarmaken en uren laten wachten. Maak een batch idealiter dezelfde dag." },
    ],
    takeaways: [
      "Batchen werkt het best bij gestirde cocktails zonder vers sap, eiwit of zuivel.",
      "Reken vooraf: 2 drankjes per gast het eerste uur, daarna 1 per uur, en 150 g ijs per drankje.",
      "Splits taken bij grotere groepen: één persoon die alles doet, is een gegarandeerde bottleneck.",
    ],
  },
  {
    id: "gastvrijheid",
    part: "vak",
    number: 19,
    title: "Gastvrijheid: het onzichtbare ingrediënt",
    intro: "De beste bartenders ter wereld worden niet alleen geroemd om technische vaardigheid, maar om hoe ze gasten laten voelen.",
    blocks: [
      { type: "h3", text: "Vragen stellen en het verhaal vertellen" },
      { type: "p", text: "In plaats van een cocktail op te leggen, vraag je naar voorkeuren: bitter of zoet, sterk of licht. Een cocktail met een kort, oprecht verhaal (waar hij vandaan komt, waarom je 'm hebt gekozen) wordt door gasten anders gewaardeerd dan exact dezelfde drank zonder die context. Kennis delen is zelf onderdeel van de gastvrijheidservaring." },
      { type: "h3", text: "Tempo lezen en iedereen een volwaardige optie geven" },
      { type: "p", text: "Een goede gastheer voelt aan wanneer een gezelschap toe is aan de volgende ronde. Gasten die niet drinken verdienen een even doordachte, volwaardige optie als de rest, geen fris uit een pak terwijl iedereen anders een zorgvuldig gemaakte cocktail krijgt." },
      { type: "h3", text: "Jezelf niet vergeten" },
      { type: "p", text: "Een gastheer die de hele avond alleen maar drankjes voor anderen maakt en zelf nooit kan genieten, is geen duurzaam model. Batchtechnieken bestaan voor een groot deel precies om dit te voorkomen: hoe meer je vooraf voorbereidt, hoe meer ruimte je zelf overhoudt." },
    ],
    takeaways: [
      "Vragen naar voorkeur vóór het serveren voorkomt een misser en toont aandacht.",
      "Een kort verhaal bij een cocktail verandert hoe gasten 'm waarderen: kennis delen is onderdeel van de ervaring.",
      "Gastvrijheid geldt ook richting jezelf: goede voorbereiding is wat jou in staat stelt om ook zelf van het feest te genieten.",
    ],
  },
  {
    id: "signature",
    part: "vak",
    number: 20,
    title: "Je eigen signature cocktail",
    intro: "De laatste les is geen nieuwe theorie, maar een opdracht: alles wat je hebt geleerd samenbrengen in één cocktail die echt van jou is.",
    blocks: [
      { type: "h3", text: "Stap 1 & 2: verhaal en basisspirit" },
      { type: "p", text: "Een signature cocktail begint niet bij een ingrediënt, maar bij een idee: een herinnering, een seizoen, een gevoel dat je wilt oproepen. Dat verhaal stuurt daarna je ingrediëntkeuzes. Gebruik de bouwstenen-methode uit Les 15 om een familie en basisspirit te kiezen die bij dat verhaal passen." },
      { type: "h3", text: "Stap 3 & 4: bouwen en benoemen" },
      { type: "p", text: "Volg het iteratieve proces: eerst de kernformule, dan pas finesse, telkens één variabele per keer aanpassen, en noteer elke versie. Reken op minstens vijf tot tien testrondes; zelfs professionals bereiken zelden hun beste versie in de eerste poging. Geef je cocktail daarna een naam en een kort, authentiek ontstaansverhaal." },
      { type: "h3", text: "Stap 5: vastleggen" },
      { type: "p", text: "Voeg je definitieve recept toe aan je eigen receptenverzameling zodat het niet verloren gaat, en zodat je het net zo makkelijk kunt opschalen voor een groep als elke andere cocktail in je collectie." },
      { type: "box", kind: "tip", label: "Laatste pro-tip van deze cursus", text: "De beste signature cocktails ontstaan zelden uit een poging om origineel te zijn om het origineel-zijn. Ze ontstaan uit een oprechte poging om een specifiek probleem op te lossen of een specifiek gevoel op te roepen." },
    ],
    takeaways: [
      "Een goede cocktail begint bij een idee of gevoel, niet bij een willekeurige ingrediëntenlijst.",
      "Elke techniek en elk principe uit de vorige negentien lessen komt hier samen in één praktische opdracht.",
      "Van basis naar pro is geen eindpunt maar een herhaalbaar proces: proeven, bijstellen, vastleggen, en opnieuw beginnen.",
    ],
  },

  // Deel VI is een optionele, verdiepende module: technieken die je in high-end
  // bars ziet maar niet nodig zijn om een goede thuisbartender te worden. Wie
  // de cursus na Les 20 afsluit, heeft al "van basis tot pro" doorlopen.
  {
    id: "infusies",
    part: "geavanceerd",
    number: 21,
    title: "Infusies: zelf smaken maken",
    intro: "Een infusie is de simpelste manier om een smaak te maken die je nergens kant-en-klaar kunt kopen: je laat een sterkedrank gewoon zijn werk doen als oplosmiddel.",
    blocks: [
      { type: "h3", text: "Waarom zelf infuseren" },
      { type: "p", text: "Alcohol is een uitstekend oplosmiddel voor aromatische stoffen: kruiden, specerijen, fruitschil en zelfs groente geven hun smaak langzaam af aan een spirit. Het resultaat is een basis die niemand anders precies zo heeft, en die je op maat kunt maken voor één specifieke cocktail." },
      { type: "h3", text: "Methode en trektijd" },
      { type: "p", text: "Los materiaal (bijv. gedroogde specerijen, citrusschil) in een afgesloten pot bij kamertemperatuur, dagelijks proeven vanaf dag één. Harde, houtige ingrediënten (kaneel, steranijs) hebben vaak dagen tot weken nodig; delicate ingrediënten (verse kruiden, bloemen) trekken binnen uren over en worden daarna bitter of vlak. Zeef zodra de smaak precies goed is, niet later." },
      { type: "h3", text: "Veiligheid en bewaring" },
      { type: "p", text: "Puur-alcoholische infusies (boven ~20% ABV) met droge of gedroogde ingrediënten zijn stabiel bij kamertemperatuur. Zodra er vers, waterig materiaal (fruit, verse kruiden) in zit, koel je de infusie zoals je vers sap zou bewaren: in de koelkast, binnen een week op. Infuseer nooit rauwe knoflook of ander laag-zuur vers materiaal in olie of laag-alcoholische mixen bij kamertemperatuur, dat is een bekende voedingsbodem voor botulisme." },
      { type: "table", headers: ["Ingrediënt", "Trektijd", "Let op"], rows: [
        ["Citrusschil (droog getrokken)", "1-3 dagen", "Alleen de gele/oranje schil, geen wit (bitter)"],
        ["Specerijen (kaneel, kardemom)", "3-7 dagen", "Dagelijks proeven, snel te sterk"],
        ["Verse kruiden (rozemarijn, tijm)", "2-6 uur", "Koel bewaren, snel bitter na te lang trekken"],
        ["Vers fruit", "1-3 dagen, gekoeld", "Beperkt houdbaar, binnen een week op"],
      ] },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Begin met een kleine testfles (100 ml) voordat je een hele fles opoffert: infusietijden zijn per merk en oogst net iets anders." },
    ],
    takeaways: [
      "Trektijd hangt af van hoe delicaat het ingrediënt is, niet van een vaste regel; proef vanaf dag één.",
      "Puur-alcoholische, droge infusies zijn kamerstabiel; alles met vers of waterig materiaal hoort in de koelkast.",
      "Rauwe, laag-zuur ingrediënten (zoals knoflook) nooit bij kamertemperatuur in olie of laag-alcoholische mixen laten trekken.",
    ],
  },
  {
    id: "fat-washing",
    part: "geavanceerd",
    number: 22,
    title: "Fat-washing: vet als smaakdrager",
    intro: "Fat-washing gebruikt een truc uit de scheikunde om een spirit te laten smaken naar iets dat normaal nooit in een fles zit: boter, spek, olijfolie of kokosvet.",
    blocks: [
      { type: "h3", text: "Het principe" },
      { type: "p", text: "Vet lost vetoplosbare aromastoffen op die water en alcohol alleen niet goed vasthouden, denk aan de volle smaak van gebakken boter of spek. Je mengt het vet warm door de sterkedrank, laat het aroma overtrekken, en vriest het mengsel daarna in. Vet blijft bij vriestemperaturen vast terwijl alcohol vloeibaar blijft, waardoor je het vet er simpelweg af kunt scheppen." },
      { type: "h3", text: "Stap voor stap" },
      { type: "p", text: "Smelt of verwarm het vet licht, meng het door de spirit (richtlijn: 50 ml vet per fles), laat 2-4 uur op kamertemperatuur of een nacht gekoeld trekken, en zet het mengsel dan minstens 6 uur in de vriezer. Schep de vaste vetlaag eraf en zeef de rest door een fijne doek of koffiefilter om ook de laatste kleine vetdeeltjes te verwijderen." },
      { type: "h3", text: "Klassieke combinaties" },
      { type: "p", text: "Bacon-bourbon (gebakken spekvet door bourbon) is de bekendste; browned butter-rum geeft een nootachtige, warme toets; olijfolie-gin wordt gebruikt voor een intens savoury Dirty Martini. Begin altijd met een neutralere spirit erbij te proeven voordat je je beste fles opoffert." },
      { type: "box", kind: "warning", label: "Let op", text: "Werk met voedselveilige, verse vetten, bewaar het eindresultaat gekoeld, en gebruik het binnen een paar weken: ook na het zeven blijven er sporen vet achter die sneller ranzig worden dan pure alcohol." },
    ],
    takeaways: [
      "Fat-washing werkt omdat vet vast wordt bij vriestemperaturen terwijl alcohol vloeibaar blijft, dat scheidingsprincipe is de hele techniek.",
      "Warm mengen, laten trekken, invriezen, afscheppen, zeven: die volgorde bepaalt het resultaat.",
      "Ook na zeven blijft een fat-washed spirit een vers product dat gekoeld en op tijd opgemaakt hoort te worden.",
    ],
  },
  {
    id: "clarificatie",
    part: "geavanceerd",
    number: 23,
    title: "Clarificatie: van troebel naar kristalhelder",
    intro: "Clarificatie maakt een troebele, vruchtige cocktail glashelder als water, zonder de smaak te verliezen: puur theater voor het oog, met een verrassend zacht mondgevoel als bonus.",
    blocks: [
      { type: "h3", text: "Waarom clarificeren" },
      { type: "p", text: "Een clarified cocktail ziet eruit als water maar smaakt vol en complex, een visueel effect dat gasten altijd verrast. Het proces filtert niet alleen deeltjes eruit, het verandert ook het mondgevoel: veel mensen omschrijven een clarified drank als opvallend zacht en rond, zonder de scherpe randjes van het origineel." },
      { type: "h3", text: "Melk-clarificatie (milk punch)" },
      { type: "p", text: "De oudste methode, al eeuwenoud: voeg een zure cocktail (met citrussap) toe aan warme volle melk. De zuurgraad laat de melkeiwitten schiften tot vaste klontjes (wrongel) die alle troebele deeltjes en een deel van de bitterheid met zich meetrekken. Zeef minstens twee keer door een kaasdoek of fijn koffiefilter tot de vloeistof volledig helder is; dat kan enkele uren duren." },
      { type: "h3", text: "Agar-clarificatie" },
      { type: "p", text: "Een modernere, snellere methode: los een klein beetje agar-agar (een uit zeewier gewonnen geleermiddel) op in een deel van de cocktail, laat het opstijven tot gel, en breek de gel daarna met een garde. Vries het gebroken mengsel in en laat het langzaam ontdooien boven een zeef of koffiefilter: de heldere vloeistof druipt eruit terwijl de troebele deeltjes in het gel-netwerk achterblijven." },
      { type: "table", headers: ["Methode", "Tijd", "Resultaat"], rows: [
        ["Melk-clarificatie", "Enkele uren, weinig actieve tijd", "Zeer helder, zachter mondgevoel, iets minder zuur"],
        ["Agar-clarificatie", "1-2 dagen (invriezen + langzaam ontdooien)", "Kristalhelder, smaak blijft dichtst bij het origineel"],
      ] },
      { type: "box", kind: "tip", label: "Pro-tip", text: "Bewaar de afgezeefde wrongel of gel niet, maar bewaar wél de heldere vloeistof gekoeld en gebruik 'm binnen een paar dagen: clarificatie verwijdert deeltjes, geen bacteriën." },
    ],
    takeaways: [
      "Clarificatie verandert niet alleen het uiterlijk maar ook het mondgevoel: zachter en ronder dan het origineel.",
      "Melk-clarificatie is de klassieke, langzamere methode; agar-clarificatie is moderner en blijft dichter bij de oorspronkelijke smaak.",
      "Een clarified cocktail is nog steeds een vers product en hoort net zo gekoeld en tijdig opgemaakt te worden als het origineel.",
    ],
  },
  {
    id: "carbonatie-rook",
    part: "geavanceerd",
    number: 24,
    title: "Carbonatie, rook en presentatie",
    intro: "De laatste 10% van een cocktail, de bubbels, de rook, het eerste beeld en de eerste geur, is precies het deel dat een drank onvergetelijk maakt in plaats van alleen goed.",
    blocks: [
      { type: "h3", text: "Carbonatie thuis" },
      { type: "p", text: "Een soda-sifon met CO2-patronen forceert koolzuur in een gekoelde, heldere cocktail (geen pulp of veel suiker, dat geeft overschuimen). Vul de sifon voor twee derde met een goed gekoelde cocktail, sluit af, schud kort, en laat even rusten voor je opent. Hoe kouder de vloeistof, hoe meer CO2 erin oplost en hoe minder de sifon schuimt bij het openen." },
      { type: "h3", text: "Rook als aroma, niet als smaak" },
      { type: "p", text: "Een smoking gun of een omgekeerd glas met houtsnippers voegt rookaroma toe via de neus, niet via de vloeistof zelf: kort roken (seconden, geen minuten) onder een cloche of omgekeerd glas geeft een subtiele, aromatische laag. Te lang roken overheerst de cocktail volledig en maakt elk ander ingrediënt onherkenbaar." },
      { type: "h3", text: "Presentatie als laatste stap" },
      { type: "p", text: "Het eerste contact met een cocktail is niet de smaak maar het beeld en de geur: een schoon glas, een verse garnering die je ook echt ruikt bij de eerste slok, en het juiste glas voor de juiste stijl. Deze cursus begon bij glaswerk in Les 3 om precies deze reden, presentatie is geen decoratie achteraf, het is een structureel onderdeel van de ervaring." },
      { type: "box", kind: "tip", label: "Laatste pro-tip", text: "Rook, carbonatie en clarificatie zijn indrukwekkend, maar los geen enkel probleem op dat een goed gebalanceerd recept niet al had opgelost. Gebruik ze om een al goede cocktail gedenkwaardig te maken, niet om een matige cocktail te redden." },
    ],
    takeaways: [
      "Hoe kouder de cocktail, hoe beter hij CO2 opneemt en hoe minder een soda-sifon schuimt.",
      "Roken is een aromatechniek voor de neus, seconden zijn genoeg; te lang roken overheerst alles.",
      "Geavanceerde technieken maken een al goede cocktail gedenkwaardig, ze redden geen slecht gebalanceerd recept.",
    ],
  },
];

// Toetsvragen staan in courseQuiz.js (5 per les + eindtoets van 30).
COURSE_LESSONS.forEach(l => { l.quiz = LESSON_QUIZZES[l.id] || []; });
export const FINAL_EXAM = FINAL_EXAM_QUESTIONS;
